ibm-mas/ansible-devops

build/bin/.env.sh
build/bin/initbuild.sh
ibm/mas_devops/roles/ocp_login/tasks/login-roks.yml
ibm/mas_devops/roles/ocp_setup_mas_deps/tasks/main.yml

- Increase timeout for SBO InstallPlan creation
- Fix ROKS login retry logic
- Build system update: drop min release level to "build"

[patch] Increase timeout for InstallPlan creation

---

ibm/mas_devops/roles/suite_verify/tasks/main.yml

Added a task to get the Admin-dashboard URL. 
https://github.com/ibm-mas/ansible-devops/issues/12

[patch] Lookup admin route

---

.travis.yml
CONTRIBUTING.md
docs/playbooks/fullstack-roks.md
docs/playbooks/lite-core-roks.md
docs/playbooks/lite-health-roks.md
docs/playbooks/lite-manage-roks.md
ibm/mas_devops/galaxy.yml
ibm/mas_devops/playbooks/lite-health-roks.yml
ibm/mas_devops/playbooks/lite-iot-roks.yml
ibm/mas_devops/playbooks/lite-manage-roks.yml
ibm/mas_devops/roles/cp4d_db2wh/tasks/main.yml
ibm/mas_devops/roles/cp4d_db2wh/templates/suite_jdbccfg.yml
ibm/mas_devops/roles/cp4d_db2wh_manage_hack/tasks/main.yml
ibm/mas_devops/roles/ocp_setup_mas_deps/templates/development-catalogs.yaml
ibm/mas_devops/roles/suite_app_configure/tasks/main.yml
ibm/mas_devops/roles/suite_app_configure/vars/iot.yml
ibm/mas_devops/roles/suite_app_install/tasks/main.yml
ibm/mas_devops/roles/suite_app_install/templates/application.yml.j2
ibm/mas_devops/roles/suite_app_install/templates/operator-group.yml.j2
ibm/mas_devops/roles/suite_app_install/templates/subscription.yml.j2
ibm/mas_devops/roles/suite_app_install/vars/health.yml
ibm/mas_devops/roles/suite_app_install/vars/iot.yml
ibm/mas_devops/roles/suite_app_install/vars/manage.yml
ibm/mas_devops/roles/suite_verify/tasks/main.yml

- Correct branch that pages site builds on
- Remove airgap support from ROKS playbooks (if you are on ROKS you are not going to need airgap support)
- Add link to Manage 8.1 technote regarding defect after successful deploy
- Use correct Db2 certificate for JDBCCfg resource
- Remove redundant permission grant from manage db2 hack
- Increase wait timeout for app configuration

[patch] Multiple fixes

---

.travis.yml
build/bin/.env.sh
build/bin/initbuild.sh

Didn't quite get the travis config right, tags are building when they should not

[patch] Build system fixes

---

ibm/mas_devops/roles/suite_app_configure/tasks/main.yml

Wait for the app workspace CR to be ready, is wrong and never complete with success.

[patch] Fix wait condition in suite_app_configure role

---

docs/playbooks/bas.md
docs/playbooks/fullstack-roks.md
docs/playbooks/lite-core-roks.md
docs/playbooks/lite-health-roks.md
docs/playbooks/lite-manage-roks.md
ibm/mas_devops/playbooks/bas/install-bas.yml
ibm/mas_devops/playbooks/fullstack-roks.yml
ibm/mas_devops/playbooks/lite-core-roks.yml
ibm/mas_devops/playbooks/lite-health-roks.yml
ibm/mas_devops/playbooks/lite-iot-roks.yml
ibm/mas_devops/playbooks/lite-manage-roks.yml
ibm/mas_devops/roles/bas_install/README.md
ibm/mas_devops/roles/bas_install/tasks/main.yml
ibm/mas_devops/roles/bas_install/templates/bascfg.yml.j2

Fixes for #65, #66 and #69:
- enforcing storage classes for BAS on ROKS (not using env vars anymore)
- bas and grafana passwords will be randomly generated if no env vars exported.
- make contact email, first name and last name required.
- fixed ansible vars with prefix `bas_`
- replicated the fixes across other common playbooks i.e lite-core-roks.yml
- fixes for readme

[patch] - Fix issue65

---

.github/workflows/ansible.yml
.github/workflows/release.yml
.github/workflows/tekton.yml
build/bin/initbuild.sh

- #85
- Also, set artifact retention period to 30 days

[patch] Fix automatic semantic versioning support for GitHub Actions

---

.github/workflows/ansible.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/tekton.yml
ibm/mas_devops/roles/ocp_provision/defaults/main.yml
ibm/mas_devops/roles/ocp_setup_mas_deps/templates/development-catalogs.yml

- Change default OCP worker config (prefer many small worker nodes over fewer large worker nodes)
- Naming consistency for installed development catalogs
- Disable Actions builds for tags

[patch] Multiple small tweaks

---

docs/playbooks/cp4d.md
docs/playbooks/ocp.md
ibm/mas_devops/playbooks/ocp/provision-quickburn.yml
ibm/mas_devops/playbooks/ocp/provision-roks.yml
ibm/mas_devops/roles/ocp_provision/README.md
ibm/mas_devops/roles/ocp_provision/defaults/main.yml
ibm/mas_devops/roles/ocp_provision/tasks/main.yml
ibm/mas_devops/roles/ocp_provision/tasks/providers/quickburn.yml
ibm/mas_devops/roles/ocp_provision/tasks/providers/roks.yml
ibm/mas_devops/roles/ocp_provision/templates/quickburn.json
pipelines/README.md
pipelines/bin/install-pipelines.sh

- `username` / `password` -> `fyre_username` / `fyre_password`
- Move defaults out of playbooks into the role
- Documentation updates

[patch] Documentation updates & defaults tidyup for provision role

---

ibm/mas_devops/playbooks/cp4d/install-services-db2.yml
ibm/mas_devops/playbooks/cp4d/install-services-fullstack.yml
ibm/mas_devops/playbooks/cp4d/install-services-watsonstudio.yml
ibm/mas_devops/roles/cp4d_install/defaults/main.yml
ibm/mas_devops/roles/cp4d_install/tasks/main.yml
pipelines/CONTRIBUTING.md
pipelines/README.md
pipelines/samples/sample-pipeline.yaml
pipelines/samples/sample-pipelinerun-dev.yaml
pipelines/samples/sample-pipelinerun-mas86.yaml
pipelines/samples/sample-pipelinerun.yaml
pipelines/tasks/cp4d/create-db2-instance.yaml

The pipeline doesn't work currently, multiple fixes including:
- Doc updates for #3
- Pipeline ordering fixes for cp4d, which should not run until after cfg-ocp
- Parameter fixes for cp4d task (storage classes), global settings in the pipeline secret should not be duplicated in the tasks.  It's an either/or scenario .. set them global or per task, not both.
- Make the pipeline stages conditional on the applications that have been chosen to be deployed ... #117
- CP4D playbooks are missing support for the optional `mas_version` variable

[minor] Conditional application deployment + misc fixes for tekton pipelines

---

CONTRIBUTING.md
ibm/mas_devops/galaxy.yml
ibm/mas_devops/roles/cp4d_db2wh/tasks/cpd35/provision-instance.yml
pipelines/CONTRIBUTING.md
pipelines/README.md

[patch] Fix set_fact of db2wh_svc_fqn

---

CONTRIBUTING.md
ibm/mas_devops/galaxy.yml
ibm/mas_devops/roles/suite_app_configure/tasks/main.yml
ibm/mas_devops/roles/suite_app_configure/vars/manage.yml
pipelines/CONTRIBUTING.md
pipelines/README.md

[patch] Increase timeout 50% for manage ws cfg

---

docs/playbooks/dependencies.md
ibm/mas_devops/playbooks/dependencies/install-bas.yml
ibm/mas_devops/roles/bas_install/README.md
ibm/mas_devops/roles/bas_install/defaults/main.yml
ibm/mas_devops/roles/bas_install/templates/fulldeployment.yaml
ibm/mas_devops/roles/mongodb/README.md

- Moved vars from BAS playbook to BAS role
- Added a new BAS attribute `bas_event_scheduler_frequency`
- Review role and playbook docs to follow new format

BAS Scheduler Event + Docs

---

CONTRIBUTING.md
ibm/mas_devops/galaxy.yml
ibm/mas_devops/roles/bas_install/README.md
image/ansible-devops/env.sh
pipelines/CONTRIBUTING.md
pipelines/README.md
pipelines/samples/sample-pipelinesettings-roks.yaml
pipelines/samples/sample-pipelinesettings.yaml

Additional fixes for PR #136 / Issue #134
- Minor doc correction
- Add missing support for new parameter in Tekton Pipelines

[patch] Fixes for BAS event scheduler frequency support

---

ibm/mas_devops/roles/suite_app_install/vars/iot.yml

[patch] Allow IoT 1 hour timeout for installation

---

ibm/mas_devops/roles/cp4d_db2wh/README.md
ibm/mas_devops/roles/cp4d_db2wh/tasks/main.yml
ibm/mas_devops/roles/cp4d_db2wh/tasks/setup_norootsquash.yml
ibm/mas_devops/roles/cp4d_db2wh/templates/norootsquash_daemonset.yml

Specifically with support for NFS-based Db2 meta volumes in mind.

[patch] Create norootsquash daemonset for NFS support

---

docs/playbooks/fullstack-roks.md
ibm/mas_devops/playbooks/fullstack-roks.yml
ibm/mas_devops/roles/cp4d_install_services/README.md
ibm/mas_devops/roles/cp4d_install_services/defaults/main.yml
ibm/mas_devops/roles/cp4d_install_services/tasks/watsonstudiocfg.yml
ibm/mas_devops/roles/cp4d_install_services/templates/create_wsl_project.json.j2
ibm/mas_devops/roles/suite_app_configure/vars/defaultspecs/hputilities.yml

This PR will address the WSL project creation gap we have in ansible collection to enable HPU app to be activated in workspace.
It also enables the HPU app to be fully installed and configured in `fullstack-roks.yml`
It doesn't cover the changes needed for the fvt pipeline yet - this is an extra effort that needs to be done afterwards.

[minor] Create WSL project and enable HPU deploy

---

docs/index.md
ibm/mas_devops/README.md
ibm/mas_devops/roles/cp4d_db2wh/README.md
ibm/mas_devops/roles/db2u/README.md

Updates the db2u documentation to make it clearer on a few points.

[patch] Update Db2u documentation 

---

multicloud-bootstrap/azure/master-arm/mainTemplate.json
multicloud-bootstrap/helper.sh
multicloud-bootstrap/init.sh
multicloud-bootstrap/pre-validate.sh

- Added checks in pre-validation.sh
- Added Role assignment in ARM template.

[patch] prevalidation script changes

---

multicloud-bootstrap/azure/master-arm/mainTemplate.json
multicloud-bootstrap/init.sh

Removed few parameters from ARM template and getting those values in shell script using az cli.

[patch] arm template parameter change (#253)

---

ibm/mas_devops/playbooks/ocp_roks_provision.yml
ibm/mas_devops/roles/ocp_roks_upgrade_registry_storage/files/configImgRegStorage.sh
ibm/mas_devops/roles/ocp_roks_upgrade_registry_storage/tasks/main.yml

Also, flip the registry upgrade and worker node reboot to opt-in instead of opt-out

[patch] Ansible-ify the registry storage upgrade role

---

CONTRIBUTING.md
ibm/mas_devops/roles/cp4d_install_services/tasks/cpd35/wait_for_services.yml
ibm/mas_devops/roles/cp4d_install_services/tasks/cpd40/install-services.yml
ibm/mas_devops/roles/cp4d_install_services/tasks/cpd40/wait_for_services.yml
ibm/mas_devops/roles/cp4d_install_services/tasks/cpd40/wait_for_subscriptions.yml
ibm/mas_devops/roles/cp4d_upgrade/tasks/cpd_upgrade/db2wh/wait_for_db2wh_instances_upgrade.yml
ibm/mas_devops/roles/cp4d_upgrade/tasks/cpd_upgrade/upgrade_cpd40.yml
ibm/mas_devops/roles/cp4d_upgrade/tasks/cpd_upgrade/wait_for_services.yml
ibm/mas_devops/roles/cp4d_upgrade/tasks/cpd_upgrade/wait_for_subscriptions.yml
ibm/mas_devops/roles/ocp_deprovision/tasks/main.yml
ibm/mas_devops/roles/ocp_deprovision/tasks/providers/quickburn.yml
ibm/mas_devops/roles/ocp_deprovision/tasks/providers/roks.yml
ibm/mas_devops/roles/ocp_provision/tasks/main.yml
ibm/mas_devops/roles/ocp_provision/tasks/providers/quickburn.yml
ibm/mas_devops/roles/ocp_provision/tasks/providers/roks.yml
ibm/mas_devops/roles/ocp_upgrade/tasks/wait_workers_upgrade.yml
ibm/mas_devops/roles/ocp_verify/tasks/main.yml
ibm/mas_devops/roles/sbo/tasks/main.yml
ibm/mas_devops/roles/sbo_upgrade/tasks/sbo_upgrade/wait_for_spec_application.yml
ibm/mas_devops/roles/suite_app_config/tasks/main.yml
ibm/mas_devops/roles/suite_app_install/tasks/main.yml
ibm/mas_devops/roles/suite_dns/tasks/providers/cis/dns_mgmt.yml
ibm/mas_devops/roles/suite_install/tasks/main.yml
ibm/mas_devops/roles/suite_upgrade/tasks/wait/wait_for_app_upgrade.yml
ibm/mas_devops/roles/suite_upgrade/tasks/wait/wait_for_app_ws_upgrade.yml

[patch] Convert use of fail/when to assert/that

---

ibm/mas_devops/roles/suite_install/README.md
pipelines/tasks/suite-install.yaml

- Added optional parameters to the task
- Updated role README on how to use this task

[patch] Add optional parameters to suite-install task

---

docs/index.md
ibm/mas_devops/roles/cert_manager/defaults/main.yml
ibm/mas_devops/roles/cert_manager/tasks/main.yml
ibm/mas_devops/roles/ibm_catalogs/tasks/main.yml
ibm/mas_devops/roles/ocp_verify/defaults/main.yml
ibm/mas_devops/roles/ocp_verify/tasks/main.yml
ibm/mas_devops/roles/sbo/defaults/main.yml
ibm/mas_devops/roles/sbo/tasks/main.yml
ibm/mas_devops/roles/sls/defaults/main.yml
ibm/mas_devops/roles/sls/tasks/install/main.yml
ibm/mas_devops/roles/uds/defaults/main.yml
ibm/mas_devops/roles/uds/templates/foundation-services/analyticsproxy.yaml

The original branch where these changes were made is now so out of date it's easier to re-create the original work than to try to merge master into that branch.
- https://github.com/ibm-mas/ansible-devops/pull/289

[patch] Various fixes for air gap support

---

docs/changes.md
ibm/mas_devops/README.md
pipelines/tasks/sls.yaml

Add support to customise catalog source and subscription channel selection to `mas-devops-sls` Tekton task

[minor] Add support for source & channel selection to mas-devops-sls Tekton task

---

ibm/mas_devops/roles/uds/README.md
pipelines/tasks/uds.yaml

These params are not supported in the uds tekton task:
- mas_segment_key
- uds_event_scheduler_frequency

[patch] Fix missing support for UDS optional params

---

ibm/mas_devops/roles/db2/README.md

[patch] Fix wrong env var in doc

---

.github/CODEOWNERS
docs/index.md
docs/playbooks/oneclick-core.md
docs/playbooks/oneclick-iot.md
docs/playbooks/oneclick-manage.md
docs/playbooks/oneclick-monitor.md

Update the docs with the latest docker version.
Also remove me from codeowners as I am out of the office for 6 weeks or more.

[patch] Update docs with new ver + codeowners

---

.github/workflows/ansible.yml
.github/workflows/docker-publish.yml
.github/workflows/docker.yml
.github/workflows/tekton-publish.yml
.github/workflows/tekton.yml
ibm/mas_devops/playbooks/oneclick_add_iot.yml
ibm/mas_devops/playbooks/oneclick_add_manage.yml
ibm/mas_devops/playbooks/oneclick_add_monitor.yml
ibm/mas_devops/playbooks/oneclick_core.yml
ibm/mas_devops/roles/suite_db2_setup_for_manage/defaults/main.yml
ibm/mas_devops/roles/uds/README.md

[patch] Fix support for env vars in one-click playbooks

---

docs/changes.md
ibm/mas_devops/README.md
ibm/mas_devops/roles/cp4d_service/defaults/main.yml
ibm/mas_devops/roles/cp4d_service/tasks/gencfg/gencfg-wd.yml
ibm/mas_devops/roles/cp4d_service/tasks/gencfg/gencfg-wsl.yml
ibm/mas_devops/roles/cp4d_service/tasks/install.yml
ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wd.yml
ibm/mas_devops/roles/cp4d_service/templates/wd/wds.json.j2
ibm/mas_devops/roles/cp4d_service/templates/wd/wdscfg.yml.j2

[minor] Support Watson Discovery Instance Creation

---

docs/playbooks/oneclick-core.md
ibm/mas_devops/playbooks/oneclick_core.yml
ibm/mas_devops/roles/uds/README.md

Addresses issues raised in:
- #366 
- #370

[patch] More documentation updates

---

.github/workflows/docker-publish.yml
docs/index.md
docs/playbooks/oneclick-core.md
docs/playbooks/oneclick-iot.md
docs/playbooks/oneclick-manage.md
docs/playbooks/oneclick-monitor.md

[patch] Publish "latest" tag for ibmmas/ansible-devops image

---

LICENSE

[patch] Create LICENSE

---

ibm/mas_devops/roles/ocp_deprovision/tasks/providers/ipi.yml
ibm/mas_devops/roles/ocp_provision/tasks/providers/ipi.yml

- fix path to openshift-install program

[patch] Fix path to openshift-install command

---

ibm/mas_devops/playbooks/cp4d.yml
ibm/mas_devops/roles/cp4d_service/tasks/prereqs/prereqs-wd.yml
ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wd-detectimagepullbackoff.yml
ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wd.yml

The workarounds for installing Watson Discovery need some fixes ... also sets the default CP4D product version to 4.0.9.

[patch] Discovery installation fix

---

docs/playbooks/oneclick-core.md
ibm/mas_devops/roles/suite_install/README.md

ibm-mas-operators reference removed issue # 10171

[patch] Remove ibm-mas-operators reference from docs

---

docs/changes.md
docs/playbooks/oneclick-optimizer.md
docs/playbooks/oneclick-visualinspection.md
ibm/mas_devops/README.md
ibm/mas_devops/playbooks/cp4d.yml
ibm/mas_devops/playbooks/ocp_roks_provision.yml
ibm/mas_devops/playbooks/oneclick_add_assist.yml
ibm/mas_devops/playbooks/oneclick_add_iot.yml
ibm/mas_devops/playbooks/oneclick_add_manage.yml
ibm/mas_devops/playbooks/oneclick_add_monitor.yml
ibm/mas_devops/playbooks/oneclick_add_optimizer.yml
mkdocs.yml

- Add oneclick_add_optimizer.yml playbook
- [Fix default versions in numerous playbooks](https://github.com/ibm-mas/ansible-devops/pull/456/commits/8dee093dda8f087b58398477944f7bc3399e23bc)

[minor] Add Maximo Optimizer playbook

---

ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wd-detectimagepullbackoff.yml
ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wd.yml

Urgh, yet more attempts to workaround CP4D lack of support for namespace-scoped image pull secrets.

[patch] More workarounds for CP4D install

---

ibm/mas_devops/playbooks/oneclick_core.yml

[patch] Correct default MAS Core subscription channel

---

ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/health.yml
ibm/mas_devops/roles/suite_app_config/vars/health.yml

https://github.ibm.com/maximo/Asset-Health-Insight/issues/12945

[patch] Fix Health standalone install

---

ibm/mas_devops/roles/mirror_case_prepare/tasks/iot-860-fix.yml

Simple typo in the directory name

[patch] Fix IoT 8.6.0 image mirroring

---

ibm/mas_devops/roles/cos/templates/ibm/objectstoragecfg.yml.j2

remove duplicate "label" specifier in objectstoragecfg

[patch] Fix duplicate label field in metadata

---

ibm/mas_devops/roles/ocp_roks_upgrade_registry_storage/tasks/main.yml

- have observed examples when 20 retries is not sufficient

[patch] Increase retry count on ROKS image registry PVC lookup

---

docs/index.md

Updates the documentation to include a new install approach via the automation operator we discussed @durera

[patch] Doc updates for new automation operator install

---

ibm/mas_devops/roles/db2/tasks/main.yml

The debug in the db2 role is dreadful, with many key variables omitted from the debug statements.

[patch] Improved Db2 role debug

---

ibm/mas_devops/roles/suite_verify/tasks/main.yml

Corrects the suite verify task name for authentication summary

[patch] Correct suite verify task name

---

docs/playbooks/oneclick-predict.md
ibm/mas_devops/playbooks/cp4d.yml
ibm/mas_devops/playbooks/oneclick_add_predict.yml
ibm/mas_devops/roles/cp4d_service/README.md

This PR for:
- fix spss role
- fix CPD role to align all playbooks
- update all vars CP4D_ to CPD_

[patch] Fix CP4D_ var prefixes to CPD_

---

ibm/mas_devops/roles/uds/tasks/install_suds/main.yml
ibm/mas_devops/roles/uds/tasks/main.yml
ibm/mas_devops/roles/uds/tasks/uninstall_suds/main.yml
ibm/mas_devops/roles/uds/templates/bascfg-suds.yml.j2

Install SUDS - Generates a BASCfg yaml file that will be applied by the MAS Operator to install and configure SUDS
Uninstall SUDS - Patches an installed BASCfg to uninstall SUDS

[patch] Updates to support SUDS

---

ibm/mas_devops/roles/cp4d/tasks/create-subscriptions.yml
ibm/mas_devops/roles/db2/tasks/rotate_ldap_user_password.yml
ibm/mas_devops/roles/kafka/tasks/provider/ibm/create-eventstreams-service-credentials.yml
ibm/mas_devops/roles/suite_manage_attachments_config/defaults/main.yml
ibm/mas_devops/roles/suite_manage_attachments_config/tasks/main.yml
ibm/mas_devops/roles/suite_manage_attachments_config/tasks/wait_bundle_pods.yml
ibm/mas_devops/roles/suite_manage_bim_config/defaults/main.yml
ibm/mas_devops/roles/suite_manage_bim_config/tasks/main.yml

make the attachments and bim configurations to be flexible for it can be reused for health standalone

[patch] Fix attachments config for Health Standalone

---

ibm/mas_devops/common_vars/casebundles/v8-230217-amd64.yml
ibm/mas_devops/roles/mirror_extras_prepare/vars/db2u_1.0.2.yml

Added updated digests for version 4.5.3 dbuoperator

[patch] Fix db2u extras for February catalog update

---

.github/CODEOWNERS

Add Andre, Sanjay, Terence, and Andrew to the list of people authorized to review pull requests to master branch.

[patch] Add new codeowners

---

ibm/mas_devops/common_vars/compatibility_matrix.yml

Update the compatibility matrix for applications and MAS 8.10
https://github.com/ibm-mas/ansible-devops/issues/741

[patch] fix application compatibility matrix for MAS 8.10

---

Makefile
docs/changes.md
docs/playbooks/oneclick-core.md
ibm/mas_devops/README.md
ibm/mas_devops/galaxy.yml
ibm/mas_devops/roles/convert_to_olm/README.md
ibm/mas_devops/roles/convert_to_olm/defaults/main.yml
ibm/mas_devops/roles/convert_to_olm/tasks/main.yml
ibm/mas_devops/roles/ibm_catalogs/README.md
ibm/mas_devops/roles/ibm_catalogs/defaults/main.yml
ibm/mas_devops/roles/ibm_catalogs/tasks/install/development-catalog.yml
ibm/mas_devops/roles/ibm_catalogs/tasks/install/main.yml
ibm/mas_devops/roles/install_operator/defaults/main.yml
ibm/mas_devops/roles/install_operator/tasks/main.yml
ibm/mas_devops/roles/install_operator/templates/ibm-entitlement-with-artifactory.json.j2
ibm/mas_devops/roles/mirror_case_prepare/defaults/main.yml
ibm/mas_devops/roles/mirror_case_prepare/tasks/prepare-dev.yml
ibm/mas_devops/roles/mirror_extras_prepare/defaults/main.yml
ibm/mas_devops/roles/mirror_extras_prepare/tasks/catalog.yml
ibm/mas_devops/roles/mirror_extras_prepare/vars/catalog.yml
ibm/mas_devops/roles/mirror_images/defaults/main.yml
ibm/mas_devops/roles/sls/README.md
ibm/mas_devops/roles/suite_app_install/README.md
ibm/mas_devops/roles/suite_install/README.md

Update all files to change artifactory_apikey to artifactory_token. We need this because airgap dev is blocked by it due to the name change and it's failing. Thank you

[major] Switch to ARTIFACTORY_TOKEN

---

ibm/mas_devops/common_vars/casebundles/v8-230414-amd64.yml
ibm/mas_devops/playbooks/mirror_add_hputilities.yml
ibm/mas_devops/playbooks/mirror_add_predict.yml

[patch] Add support for Watson Machine Learning and Analytics Engine (Spark)

---

.github/workflows/ansible.yml
build/bin/.functions.sh
build/bin/artifactory-release.sh

Pre-requistite build update to enable pre-release builds of the MAS CLI to automatically pick up the latest pre-release build of this Ansible collection:
- https://github.com/ibm-mas/cli/issues/222

[patch] Upload ansible-devops tar.gz to Artifactory

---

ibm/mas_devops/roles/ocp_simulate_disconnected_network/defaults/main.yml

Verified in fvt-airgap dev environment

[patch] update blocked address for artifactory

---

.github/workflows/ansible.yml
build/bin/.functions.sh
build/bin/artifactory-release.sh

Fixes Artifactory upload functionality in the GitHub Actions workflow.

[patch] Improve build system

---

ibm/mas_devops/common_vars/casebundles/v8-230526-amd64.yml

update predict version to install with channel 8.8.x

[patch] Update predict version

---

docs/playbooks/oneclick-predict.md

Update playbook documentation for Predict v 8.9

[patch]  Update Predict 8.9 documentation for playbook deployment #14825

---

Makefile
docs/changes.md
ibm/mas_devops/README.md
ibm/mas_devops/galaxy.yml
ibm/mas_devops/playbooks/mirror_add_assist.yml
ibm/mas_devops/playbooks/mirror_add_hputilities.yml
ibm/mas_devops/playbooks/mirror_add_iot.yml
ibm/mas_devops/playbooks/mirror_add_manage.yml
ibm/mas_devops/playbooks/mirror_add_monitor.yml
ibm/mas_devops/playbooks/mirror_add_optimizer.yml
ibm/mas_devops/playbooks/mirror_add_predict.yml
ibm/mas_devops/playbooks/mirror_add_visualinspection.yml
ibm/mas_devops/playbooks/mirror_core.yml
ibm/mas_devops/playbooks/mirror_dependencies.yml

The combination of `--mirror-xxx` and `--skip-xxx` options has proven overly confusing, everything is now purely "include x", rather than an combintion of "include x, while excluding y" statements.

[major] Overhaul image mirroring logic

---

docs/playbooks/oneclick-predict.md
ibm/mas_devops/playbooks/oneclick_add_predict.yml

https://github.ibm.com/maximo/Asset-Health-Insight/issues/14907
- fix predict playbook and change CDP variable to false (defaul)
- update documentation for predict playbook

[patch]  Fix predict ansible playbooks #14907

---

build/bin/copy-role-docs.sh
mkdocs.yml

[patch] Add missing ocp_efs doc

---

ibm/mas_devops/playbooks/oneclick_add_manage.yml

[patch] Fix CP4D_X env var naming (should be CPD_X)

---

docs/playbooks/oneclick-predict.md

[patch] Various doc corrections

---

ibm/mas_devops/common_vars/casebundles/v8-230616-amd64.yml
ibm/mas_devops/common_vars/casebundles/v8-230627-amd64.yml

Fix version for common services to mirror 3.23.2 instead of 3.23.1

[patch] Fix mirror version for common services

---

ibm/mas_devops/roles/aws_ec2_documentdb/README.md
ibm/mas_devops/roles/aws_ec2_documentdb/defaults/main.yml
ibm/mas_devops/roles/aws_ec2_documentdb/tasks/main.yml
ibm/mas_devops/roles/aws_ec2_documentdb/templates/docdb_instance_user_credentials_secret.yaml.j2
ibm/mas_devops/roles/aws_ec2_documentdb/templates/ec2-add-user.sh.j2
ibm/mas_devops/roles/aws_ec2_documentdb/templates/ec2-cleanup-resource.sh.j2
ibm/mas_devops/roles/aws_ec2_documentdb/templates/ec2-remove-user.sh.j2
ibm/mas_devops/roles/aws_ec2_documentdb/templates/ec2.sh.j2
ibm/mas_devops/roles/aws_ec2_documentdb/utils/create_security_group.yml
ibm/mas_devops/roles/aws_ec2_documentdb/utils/create_subnet.yml
ibm/mas_devops/roles/aws_ec2_documentdb/utils/ec2.yml
ibm/mas_devops/roles/aws_ec2_documentdb/utils/validate.yml
ibm/mas_devops/roles/aws_ec2_documentdb/vars/main.yml

[patch] role to provision ec2 instance and create additional docdb instance user

---

ibm/mas_devops/playbooks/ocp_fyre_provision.yml
ibm/mas_devops/playbooks/ocp_roks_provision.yml

Fixes for FYRE and ROKS provisioning playbooks.

[patch] Fix playbook errors introduced in #954

---

ibm/mas_devops/roles/ocp_provision/defaults/main.yml
ibm/mas_devops/roles/suite_app_config/README.md
ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/manage.yml
ibm/mas_devops/roles/suite_app_config/vars/health.yml
ibm/mas_devops/roles/suite_app_config/vars/manage.yml

PRs:
- ansible-devops: https://github.com/ibm-mas/ansible-devops/pull/957
- ansible-fvt: https://github.ibm.com/maximoappsuite/ansible-fvt/pull/260
- cli: https://github.com/ibm-mas/cli/pull/418
Please refer to CLI PR for a complete description of the new binding requested by Health team.

[minor] Optional Watson Studio bind to Health

---

ibm/mas_devops/roles/mongodb/tasks/providers/aws/uninstall.yml

https://jsw.ibm.com/browse/MASCORE-119

[patch] logic added to wait till all instances and cluster deletes completely

---

ibm/mas_devops/roles/kafka/tasks/provider/aws/uninstall.yml
ibm/mas_devops/roles/kafka/tasks/provider/aws/utils/create-subnet.yml

[patch] Immediate deletion of kms_key

---

ibm/mas_devops/roles/ocp_provision/tasks/providers/rosa.yml
ibm/mas_devops/roles/ocp_provision/templates/rosa/rosa-details.yml.j2

Autogenerate rosa_cluster_admin_password if not set + update to ROSA details template

[patch] autogenerate rosa_cluster_admin_password if not set

---

ibm/mas_devops/roles/mongodb/tasks/providers/community/install.yml

Verify the common-vars/casebundles file exists before loading it.

[patch] Mongodb check if casebundle file exists before loading

---

docs/playbooks/oneclick-update.md
ibm/mas_devops/common_vars/casebundles/v8-231004-amd64.yml
ibm/mas_devops/playbooks/mirror_add_assist.yml
ibm/mas_devops/playbooks/mirror_add_hputilities.yml
ibm/mas_devops/playbooks/mirror_add_iot.yml
ibm/mas_devops/playbooks/mirror_add_manage.yml
ibm/mas_devops/playbooks/mirror_add_monitor.yml
ibm/mas_devops/playbooks/mirror_add_optimizer.yml
ibm/mas_devops/playbooks/mirror_add_predict.yml
ibm/mas_devops/playbooks/mirror_add_visualinspection.yml
ibm/mas_devops/playbooks/mirror_core.yml
ibm/mas_devops/playbooks/mirror_dependencies.yml
ibm/mas_devops/playbooks/oneclick_update.yml

Support catalog `v8-231004-amd64` - https://github.ibm.com/maximoappsuite/ibm-maximo-operator-catalog/pull/311

[minor] support October 4th catalog with 8.11.1 and SLS 3.8.1

---

ibm/mas_devops/roles/ocp_contentsourcepolicy/defaults/main.yml
ibm/mas_devops/roles/ocp_contentsourcepolicy/tasks/main.yml
ibm/mas_devops/roles/ocp_contentsourcepolicy/tasks/update-pull-secret-dev.yml
ibm/mas_devops/roles/ocp_contentsourcepolicy/templates/imagecontentsourcepolicy.yml.j2

This change only impacts internal development, this change allows us to better execute testing in a disconnected environment and has no external facing impact.

[patch] Use edge as the "mirror" for Artifactory

---

ibm/mas_devops/roles/suite_app_upgrade/tasks/upgrade.yml

[patch] Another delay timing fix

---

docs/playbooks/oneclick-update.md
ibm/mas_devops/common_vars/casebundles/v8-231031-amd64.yml
ibm/mas_devops/playbooks/mirror_add_assist.yml
ibm/mas_devops/playbooks/mirror_add_hputilities.yml
ibm/mas_devops/playbooks/mirror_add_iot.yml
ibm/mas_devops/playbooks/mirror_add_manage.yml
ibm/mas_devops/playbooks/mirror_add_monitor.yml
ibm/mas_devops/playbooks/mirror_add_optimizer.yml
ibm/mas_devops/playbooks/mirror_add_predict.yml
ibm/mas_devops/playbooks/mirror_add_visualinspection.yml
ibm/mas_devops/playbooks/mirror_core.yml
ibm/mas_devops/playbooks/mirror_dependencies.yml
ibm/mas_devops/playbooks/oneclick_update.yml

Support for october 30 catalog - https://github.ibm.com/maximoappsuite/ibm-maximo-operator-catalog/pull/322

[minor] Support v8-231031-amd64 Catalog update

---

ibm/mas_devops/roles/uds/README.md
ibm/mas_devops/roles/uds/defaults/main.yml
ibm/mas_devops/roles/uds/tasks/install-suds/main.yml
ibm/mas_devops/roles/uds/tasks/main.yml
ibm/mas_devops/roles/uds/tasks/uninstall-suds/main.yml

Also replace "_" with "-" in "_suds" actions for consistency.

[patch] UDS role blindly runs the action provided, even if it's invalid

---

ibm/mas_devops/common_vars/casebundles/v8-231031-amd64.yml
ibm/mas_devops/playbooks/mirror_dependencies.yml

- Support mirroring new mongo versions

[minor] support mirroring new mongo versions

---

ibm/mas_devops/common_vars/casebundles/v8-231004-amd64.yml
ibm/mas_devops/common_vars/casebundles/v8-231031-amd64.yml

Rebuild of these catalogs is to fix the channel upgrade graphs.
Note: No content have changed.

[minor] Re-issue October 04 and 31 catalog

---

ibm/mas_devops/playbooks/oneclick_add_assist.yml
ibm/mas_devops/playbooks/oneclick_add_iot.yml
ibm/mas_devops/playbooks/oneclick_add_manage.yml
ibm/mas_devops/playbooks/oneclick_add_monitor.yml
ibm/mas_devops/playbooks/oneclick_add_optimizer.yml
ibm/mas_devops/playbooks/oneclick_add_predict.yml
ibm/mas_devops/playbooks/oneclick_add_visualinspection.yml
ibm/mas_devops/roles/suite_certs/defaults/main.yml

quick fixes for the following issues:
- https://github.com/ibm-mas/ansible-devops/issues/1041
- https://github.com/ibm-mas/ansible-devops/issues/1076

[patch] Fix playbook defaults and suite_dns default handling

---

ibm/mas_devops/common_vars/casebundles/v8-231128-amd64.yml

Update to November catalog casebundle https://github.ibm.com/maximoappsuite/ibm-maximo-operator-catalog/pull/327

[minor] Update v8-231128-amd64 catalog casebundle

---

ibm/mas_devops/roles/gencfg_jdbc/tasks/main.yml

Fix for: 
- https://github.com/ibm-mas/ansible-devops/issues/1122

[patch] Fix "jdbc_tls_crt is undefined"

---

ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2

Workaround for https://issues.redhat.com/browse/OCPBUGS-385

[patch] Include default channels in ImageSetConfiguration

---

ibm/mas_devops/plugins/action/verify_workloads.py

Watson Discovery has proven to be an unreliable product in general, particularly this deployment, which will often be found in this state indefinitely, and will hold up our strict verification of the cluster state following an install, update, or upgrade:
```
```
As we can not fix the problem in Discovery, we will ignore this deployment when validating "is the workload in the cluster healthy?".

[patch] Ignore wd-discovery-ranker-rest deployment

---

ibm/mas_devops/roles/dro/tasks/main.yml

Updated condition for when dro.gencfg need to be executed.

[patch] Fixed DRO gencfg condition

---

ibm/mas_devops/roles/dro/tasks/gencfg/main.yml
ibm/mas_devops/roles/dro/tasks/main.yml
ibm/mas_devops/roles/uds/defaults/main.yml
ibm/mas_devops/roles/uds/tasks/main.yml

https://jsw.ibm.com/browse/MASCORE-1825
- added lower case check for dro_migration variable.
- Ensure UDS role does not install during mas update

[patch] change dro_migration flag to lower case 

---

ibm/mas_devops/roles/dro/tasks/install-dro/main.yml

Added ibm_entitlement_key lookup check for DRO_MIGRATION

[patch] dro-migration fix ibm_entitlement_key lookup

---

ibm/mas_devops/roles/dro/tasks/gencfg/main.yml
ibm/mas_devops/roles/dro/tasks/gencfg/migrate.yml
ibm/mas_devops/roles/dro/tasks/main.yml

Updated dro_migration check for dro gencfg tasks.
Local Testing was successful. Attaching logs
[dro_update.log](https://github.com/ibm-mas/ansible-devops/files/14436251/dro_update.log)

[patch] dro_migration check updated

---

ibm/mas_devops/roles/cp4d_service/tasks/install.yml

Missed to add the zen fix in cp4d_service role.
So reusing the fix here from cp4d role.

[patch] apply same cp4d zen fix for cp4d_service role

---

ibm/mas_devops/roles/cp4d_service/tasks/install.yml

The path was mixed up in the prev commit.

[patch] fix olm-utils-cm path in cp4d_service role

---

build/bin/build-collection.sh
ibm/mas_devops/common_vars/casebundles/v8-240405-amd64.yml

Catalog - https://github.ibm.com/maximoappsuite/ibm-maximo-operator-catalog/pull/373

[minor] Support 240405 catalog with MAS 8.11.9

---

docs/index.md

Addresses https://github.com/ibm-mas/ansible-devops/issues/1294.

[patch] Update link to download oc client

---

ibm/mas_devops/roles/grafana/tasks/install/main.yml
ibm/mas_devops/roles/grafana/templates/cluster-monitoring-config.yml.j2

... if it's not already enabled

[patch] Allow grafana role to enable user workload monitoring

---

.github/CODEOWNERS

sanjay's id changed to sanjayprab

[patch] update codeowners

---

ibm/mas_devops/roles/grafana/tasks/update/main.yml

Fix for issue https://github.com/ibm-mas/ansible-devops/issues/1333

[patch] Fix include_tasks for grafana update process

---

build/bin/build-collection.sh
docs/playbooks/oneclick-update.md
ibm/mas_devops/common_vars/casebundles/v9-240625-amd64.yml
ibm/mas_devops/common_vars/compatibility_matrix.yml
ibm/mas_devops/playbooks/mirror_add_assist.yml
ibm/mas_devops/playbooks/mirror_dependencies.yml
ibm/mas_devops/roles/cp4d/tasks/determine-ibmcatalog-tag.yml
ibm/mas_devops/roles/mongodb/tasks/determine-ibmcatalog-tag.yml
ibm/mas_devops/roles/mongodb/tasks/providers/community/install-mongo.yml
ibm/mas_devops/roles/suite_app_upgrade/tasks/check_app_compatibility.yml
ibm/mas_devops/roles/suite_upgrade/tasks/check_core_compatibility.yml

Catalog 240625 - https://github.ibm.com/maximoappsuite/ibm-maximo-operator-catalog/pull/411

[minor] Support June catalog with MAS 9.0

---

ibm/mas_devops/roles/suite_app_config/tasks/main.yml

Refer to https://ibm-watson-iot.slack.com/archives/C046FAZ3KJR/p1719530273453929

[patch] Fix task paths in suite-app-config

---

ibm/mas_devops/roles/suite_app_config/tasks/main.yml
ibm/mas_devops/roles/suite_app_config/tasks/manage/post-config/main.yml
ibm/mas_devops/roles/suite_app_config/tasks/manage/pre-config/main.yml

`include_role` should be called with a fully qualified name, this update corrects two instances where this was not happening.

[patch] Update to use complete name of the roles

---

ibm/mas_devops/roles/suite_certs/defaults/main.yml
ibm/mas_devops/roles/suite_certs/templates/dnsentries.yml.j2

Make changes so that arcgis public certs can be generated so that it works with suite manual cert

[minor] Support manual certs for arcgis

---

ibm/mas_devops/playbooks/mirror_add_assist.yml
ibm/mas_devops/playbooks/mirror_add_iot.yml
ibm/mas_devops/playbooks/mirror_add_manage.yml
ibm/mas_devops/playbooks/mirror_add_monitor.yml
ibm/mas_devops/playbooks/mirror_add_optimizer.yml
ibm/mas_devops/playbooks/mirror_add_predict.yml
ibm/mas_devops/playbooks/mirror_add_visualinspection.yml
ibm/mas_devops/playbooks/mirror_core.yml
ibm/mas_devops/playbooks/oneclick_add_assist.yml
ibm/mas_devops/playbooks/oneclick_add_iot.yml
ibm/mas_devops/playbooks/oneclick_add_manage.yml
ibm/mas_devops/playbooks/oneclick_add_monitor.yml
ibm/mas_devops/playbooks/oneclick_add_optimizer.yml
ibm/mas_devops/playbooks/oneclick_add_predict.yml
ibm/mas_devops/playbooks/oneclick_add_visualinspection.yml
ibm/mas_devops/playbooks/oneclick_core.yml

Changing default channel to 9.0.x and cpd 4.8.0 in playbooks
Resolved Issues - 
- https://github.com/ibm-mas/ansible-devops/issues/1358
- https://github.com/ibm-mas/ansible-devops/issues/1357

[patch] change default channel in playbooks to 9.0.x

---

build/bin/build-collection.sh
ibm/mas_devops/roles/ibm_catalogs/README.md
ibm/mas_devops/roles/ibm_catalogs/defaults/main.yml

Missed to change the default to latest v9 catalog version

[patch] fix default catalog version

---

ibm/mas_devops/roles/aws_documentdb_user/README.md
ibm/mas_devops/roles/aws_documentdb_user/defaults/main.yml
ibm/mas_devops/roles/aws_documentdb_user/tasks/main.yml

This PR has ansible role logic change to support multiple docdb host while connecting via mongosh

[minor] support for multiple docdb host and port

---

ibm/mas_devops/playbooks/ocp_aws_provision.yml

[patch] Documentation fix for env variables in ocp_aws_provision

---

ibm/mas_devops/playbooks/oneclick_add_manage.yml

[patch] Update stale comment in manage playbook

---

ibm/mas_devops/roles/suite_install/defaults/main.yml
ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2

This PR addresses the issue where SSO was not adhering to the specification settings. Additionally, it introduces new configurable fields to the suite.
- https://github.com/ibm-mas/python-devops/pull/17
- 
- https://jsw.ibm.com/browse/MASCORE-3320
I set up a personal FYRE environment and followed the MAS installation process to configure both default and personal settings. Please refer to the images below for details:

[patch] Fix SSO out of settings property

---

CONTRIBUTING.md
docs/playbooks/ocp.md
ibm/mas_devops/playbooks/ocp_fyre_provision.yml
ibm/mas_devops/playbooks/ocp_roks_provision.yml
ibm/mas_devops/playbooks/ocp_rosa_provision.yml
ibm/mas_devops/roles/mirror_ocp/README.md
ibm/mas_devops/roles/ocs/tasks/install/main.yml

Add OCP 4.15 option as the default

[patch] Set default OCP version to 4.15

---

ibm/mas_devops/roles/ocp_contentsourcepolicy/README.md

Add explicit list of registries and repos to the ICSP role documentation.

[skip ci] Update ICSP docs

---

ibm/mas_devops/common_tasks/backup_restore/create_run_tasks_job.yml

[patch] Add MASBR_ACTION to Cronjob env

---

ibm/mas_devops/roles/cp4d/tasks/create-cpd-core-service-accounts.yml
ibm/mas_devops/roles/cp4d/tasks/install-cp4d.yml
ibm/mas_devops/roles/cp4d_service/tasks/create-cpd-service-accounts.yml
ibm/mas_devops/roles/cp4d_service/tasks/install.yml
ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-ccs.yml
ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-elasticsearch.yml
ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wml-etcd.yml

Changes seem to have broken FVT tests in stable even though they were testes and worked on local machine.
Will revert changes - must be some version dependency that will need further investigation

[patch] Revert Apply kubernetes changes server side 

---

ibm/mas_devops/roles/cos/tasks/providers/ibm/provision.yml

Reverts ibm-mas/ansible-devops#1469

Revert "[patch] debug statement for cos hmac"

---

ibm/mas_devops/roles/cp4d/tasks/wait/wait-zenmetastore-edb.yml
ibm/mas_devops/roles/cp4d_service/tasks/install.yml
ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-elasticsearch.yml

Fixes for a number of edge case failures and race conditions identified during CP4D 5.0 implementation
see https://jsw.ibm.com/browse/MASCORE-4049
**Testing**
Tested install in pfvtcpd5 and tested update in pfvtcpd48

[patch] fixes for CPD 5 edge cases and race conditions

---

ibm/mas_devops/roles/grafana/tasks/uninstall_grafanav4/main.yml
ibm/mas_devops/roles/grafana/tasks/update/main.yml

People shouldn't be on v4 anymore but we should still be able to update them to v5
Tested in daily update fvt

[patch] fixes for updating grafana from v4 to v5

---

ibm/mas_devops/common_vars/casebundles/v9-241107-amd64.yml

Catalog digest updated in v9-241107-amd64.yml

[patch] catalog digest update

---

ibm/mas_devops/roles/cp4d/templates/catalog_sources/5.0.0.yml

These are the correct digests needed for when we add support of CPD 5.0

[patch] Update CP4D 5.0 digests to correct values

---

.github/workflows/ansible-publish.yml
build/ee/requirements.yml

Fix the workflow action to trigger on release

[patch] Fix execution environment publish on release

---

ibm/mas_devops/roles/suite_app_upgrade/tasks/main.yml
ibm/mas_devops/roles/suite_uninstall/tasks/main.yml
ibm/mas_devops/roles/suite_upgrade/tasks/main.yml

- Fixed a bug of retrieving ibm-mas subscription
- Fixed bugs of wrong label_selectors pattern used

[patch] Fix label_selectors pattern

---

ibm/mas_devops/roles/suite_certs/templates/dnsentries.yml.j2
ibm/mas_devops/roles/suite_dns/templates/dnsentries.yml.j2
ibm/mas_devops/roles/suite_dns/templates/edge_certificate_routes.yml.j2

https://jsw.ibm.com/browse/MASAIB-494

[patch] update dns entries for aibroker

---

ibm/mas_devops/roles/aibroker/tasks/config_db2/main.yml
ibm/mas_devops/roles/aibroker/templates/aibroker/aibrokerapp.yml.j2
ibm/mas_devops/roles/aibroker/templates/jdbc/jdbc-admin-credentials.yml.j2
ibm/mas_devops/roles/aibroker/vars/main.yml

Changes in this PR
1. Updated secret name
2. Added url, certificate and other jdbc config in secret

[patch] Adding jdbccfg secret

---

ibm/mas_devops/common_tasks/backup_restore/copy_pod_files_to_storage.yml
ibm/mas_devops/common_tasks/backup_restore/copy_storage_files_to_pod.yml

this is to fix db2 restore role.
https://github.com/ibm-mas/ansible-devops/issues/1645

[patch] fix db2 restore on copying pod files to storage location #1645

---

ibm/mas_devops/roles/suite_app_backup_restore/README.md
ibm/mas_devops/roles/suite_backup_restore/README.md

[patch] docfix: ttps -> https

---

ibm/mas_devops/roles/aibroker/tasks/tenant/install/main.yml

Adding fix as per bug faced by Josef.

[patch] adding ssl cert fix

---

build/bin/build-collection.sh
ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2

Catalog PR: https://github.ibm.com/maximoappsuite/ibm-maximo-operator-catalog/pull/602

[minor] Support April Catalog Update

---

.github/CODEOWNERS

[patch] review codeowners

---

docs/playbooks/ocp.md
ibm/mas_devops/playbooks/ocp_convert_to_disconnected.yml
ibm/mas_devops/playbooks/ocp_fyre_provision.yml
ibm/mas_devops/playbooks/ocp_roks_provision.yml
ibm/mas_devops/roles/mirror_ocp/README.md
ibm/mas_devops/roles/ocp_cluster_monitoring/README.md
ibm/mas_devops/roles/ocp_provision/defaults/main.yml

[Jira MASCORE-5252](https://jsw.ibm.com/browse/MASCORE-5252)
Modified docs and code compatible for OCP 4.17
docs/playbooks/ocp.md
ibm/mas_devops/playbooks/ocp_convert_to_disconnected.yml
ibm/mas_devops/playbooks/ocp_fyre_provision.yml
ibm/mas_devops/playbooks/ocp_roks_provision.yml
ibm/mas_devops/roles/mirror_ocp/README.md
ibm/mas_devops/roles/ocp_cluster_monitoring/README.md
ibm/mas_devops/roles/ocp_provision/defaults/main.yml

ansible-devops supports for OCP 4.17

---

ibm/mas_devops/playbooks/oneclick_add_aibroker.yml
ibm/mas_devops/roles/aibroker/templates/aibroker/aibrokerapp.yml.j2
ibm/mas_devops/roles/aibroker_tenant/templates/aibroker/aibrokerworkspace.yml.j2

MASAIB-819
change IN_SAAS_ENV (or in_saas_env) to MAS_AIBROKER_SAAS (or mas_aibroker_saas) - there is vars duplicacy
Able to deploy aibroker application successfully.

[patch] change var IN_SAAS_ENV to  MAS_AIBROKER_SAAS - remove vars duplicacy

---

ibm/mas_devops/roles/aibroker_tenant/templates/aibroker/aibrokerworkspace.yml.j2

MASAIB-887
Remove two fields which are no longer required in the AI Broker Workspace CR.
<hr/>

[patch] remove unused CR fields

---

ibm/mas_devops/playbooks/deploy_private_registry.yml

Common services are no longer needed for cert manager installation and should be excluded from the code.
<hr/>

[patch] Update deploy_private_registry.yml to remove common_services

---

build/bin/build-collection.sh
docs/playbooks/ocp.md
ibm/mas_devops/playbooks/ocp_convert_to_disconnected.yml
ibm/mas_devops/playbooks/ocp_fyre_provision.yml
ibm/mas_devops/playbooks/ocp_roks_provision.yml
ibm/mas_devops/requirements.txt
ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-ccs.yml
ibm/mas_devops/roles/mirror_ocp/README.md
ibm/mas_devops/roles/ocp_cluster_monitoring/README.md
ibm/mas_devops/roles/ocp_provision/defaults/main.yml

Catalog PR: https://github.ibm.com/maximoappsuite/ibm-maximo-operator-catalog/pull/619

[minor] Support May Catalog Update

---

ibm/mas_devops/roles/aibroker_tenant/templates/rsl/rsl-secret.yml.j2

https://jsw.ibm.com/browse/MASAIB-911
Fix a bug in rsl secret template
This has been tested on quickburn cluster.
<hr/>

[patch] bug fix for rsl secret template

---

ibm/mas_devops/roles/aibroker_tenant/README.md

Document some new variables added to the `aibroker_tenant` role.

[docs] document new AI Service vars

---

ibm/mas_devops/playbooks/oneclick_add_facilities.yml

this fixes a template error in oneclick playbook.
<hr/>

[patch] fix template error in oneclick_add_facilities

---

ibm/mas_devops/roles/aibroker_tenant/templates/watsonx/secret.yml.j2

Change the key for watsonx secret.
<hr/>

[patch] Changing the key in watsonx secret

---

ibm/mas_devops/playbooks/oneclick_add_aibroker.yml
ibm/mas_devops/roles/aibroker/tasks/config_dro/main.yml
ibm/mas_devops/roles/aibroker/templates/aibroker/aibrokerapp.yml.j2
ibm/mas_devops/roles/aibroker_tenant/templates/aibroker/aibrokerworkspace.yml.j2

This PR fix:
- remove task for read DNS domain directly in playbook which is not good practice
- remove debug as we should not show sensitive information in logs
- fix encode ca for DRO, DB2, SLE to not show certificate in plain text 
<hr/>

[patch] Enable encode certificates content in CR for AIBroker

---

ibm/mas_devops/roles/suite_certs/templates/dnsentries.yml.j2
ibm/mas_devops/roles/suite_dns/templates/dnsentries.yml.j2
ibm/mas_devops/roles/suite_dns/templates/edge_certificate_routes.yml.j2

MASCORE-3438
DNS Entries missed in https://github.com/ibm-mas/ansible-devops/pull/1744
Tested on SRE environment

[patch] added missing facilities dnsentries

---

ibm/mas_devops/roles/minio/defaults/main.yml
ibm/mas_devops/roles/minio/tasks/main.yml
ibm/mas_devops/roles/minio/templates/minio/minio-deployment.yml.j2
ibm/mas_devops/roles/minio/templates/minio/minio-route.yml.j2
ibm/mas_devops/roles/minio/templates/minio/minio-service.yml.j2

[patch] Update minio deployment and route for TLS support

---

ibm/mas_devops/playbooks/mirror_dependencies.yml
ibm/mas_devops/roles/kmodels/defaults/main.yml
ibm/mas_devops/roles/kmodels/tasks/determine-ibmcatalog-tag.yml
ibm/mas_devops/roles/kmodels/tasks/main.yml
ibm/mas_devops/roles/kmodels/templates/kmodels-controller/deployment.yml.j2
ibm/mas_devops/roles/kmodels/templates/kmodels-store/deployment.yml.j2
ibm/mas_devops/roles/kmodels/templates/kmodels-watcher/deployment.yml.j2
ibm/mas_devops/roles/mirror_extras_prepare/vars/km_components_1.0.11.yml
ibm/mas_devops/roles/mirror_extras_prepare/vars/kmodels_1.0.11.yml

This pr update a way how we define digest or tag for KMODELS components 
<hr/>

[patch] Fix airgap support for kmodels in AI Service

---

ibm/mas_devops/playbooks/mirror_dependencies.yml

PR to set variable mirror_kmodels to false (default)
<hr/>

[patch] update var mirror_kmodels set as default to false

---

ibm/mas_devops/roles/arcgis/templates/ws-cluster-rbac.yml.j2

We are required to make these changes to incorporate the ESRI code base with their new version release.
<hr/>

[patch] Add required permission for netpol

---

ibm/mas_devops/roles/aiservice/tasks/config_db2/main.yml

modify jdbccfg file name for lookup in aiservice role.
<hr/>

[patch] fix file name for jdbccfg look up in aiservice role

---

ibm/mas_devops/roles/aiservice_kmodels/templates/kmodels-controller/configmap.yml.j2
ibm/mas_devops/roles/aiservice_kmodels/templates/kmodels-controller/deployment.yml.j2
ibm/mas_devops/roles/aiservice_kmodels/templates/kmodels-controller/network.yml.j2

[patch] remove http connection from km-controler

---

ibm/mas_devops/playbooks/aiservice.yml
ibm/mas_devops/roles/aiservice/tasks/config_db2/main.yml
ibm/mas_devops/roles/aiservice_tenant/templates/aiservice/aiserviceworkspace.yml.j2

As we lookup for jdbccfg file with naming convention like aiservice-{aiservice-instance-id} so we have to append aiservice-instance-id in db2_instance_name as well.
Aiservice Deployment Done Successfully.
<hr/>

[patch] Fix db2 config issue with Aiservice

---

ibm/mas_devops/roles/mirror_extras_prepare/vars/kmodels_1.0.14.yml

Add extra images for kmodels 1.0.14 for AI Service August release.
<hr/>

[patch] Add extra images for kmodels 1.0.14

---

ibm/mas_devops/roles/ocp_provision/tasks/main.yml

[MASR-5847](https://jsw.ibm.com/browse/MASR-5847) OCP 4.19 Rotation
Added OCP 4.19 to OCP rotation role

added OCP 4.19 to rotate
