ibm-mas/ansible-devops

- ibm/mas_devops/roles/ocp_provision/tasks/providers/roks.yml
Seeing timeouts but then the cluster is soon ready after that. A few more retries should do it.
> Update roks.yml to increase retries for deploy

- CONTRIBUTING.md
- build/README.md
- docs/index.md
- docs/roles/ocp_verify.md
- ibm/mas_devops/README.md
- ibm/mas_devops/galaxy.yml
- ibm/mas_devops/playbooks/lite-manage-roks.yml
- ibm/mas_devops/playbooks/ocp/verify-roks.yml
- ibm/mas_devops/roles/ocp_setup_mas_deps/README.md
- ibm/mas_devops/roles/ocp_verify/README.md
- ibm/mas_devops/roles/ocp_verify/meta/main.yml
- ibm/mas_devops/roles/ocp_verify/tasks/main.yml
Closes #20
- Create new role `ocp_verify` that checks (and waits) for the RedHat Operator Catalog to be ready.  This is primarily to avoid issues in IBM Cloud ROKS where it can be upwards of an hour after a cluster is provisioned until the catalog is available
- Create a new playbook `ocp/verify-roks.yml` that can be used to directly invoke this role
- Add the role as a dependency to the `ocp_setup_mas_deps` role to ensure that the cluster is ready before we attempt to insall SBO from the RedHat Operator Catalog.
> [minor] Add ocp_verify role and associated playbook

- ibm/mas_devops/roles/ocp_deprovision/tasks/providers/roks.yml
The loop is not exiting as expected when a cluster is already deprovisioned.
> [patch] Fix ROKS deprovision loop exit logic

- ibm/mas_devops/galaxy.yml
Error reported in the sponsored user program:
```
ansible-playbook playbooks/fullstack-roks.yml
[WARNING]: running playbook inside collection ibm.mas_devops
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! couldn't resolve module/action 'community.kubernetes.k8s_info'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/home/labs/.ansible/collections/ansible_collections/ibm/mas_devops/roles/ocp_verify/tasks/main.yml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: Check if Red Hat Catalog is ready
^ here
```
The metadata in our collection needs to declare a …
> [patch] Add kubernetes module to collection dependencies

- ibm/mas_devops/roles/suite_dns/templates/cis/production-cert.yml.j2
- ibm/mas_devops/roles/suite_dns/templates/cis/staging-cert.yml.j2
Per discussion with MAS team, the change to the templates will remove the current limitation in the certificate templates in order to allow for multiple CIS instances for different MAS instances in the same cluster.
> [patch] Fix CIS integration to support multiple MAS instances

- ibm/mas_devops/playbooks/ocp/configure-ocp.yml
- ibm/mas_devops/roles/ocp_setup_mas_deps/README.md
- ibm/mas_devops/roles/ocp_setup_mas_deps/defaults/main.yml
- ibm/mas_devops/roles/ocp_setup_mas_deps/templates/sbo/subscription.yaml
Currently the Service Binding Operator subscription is hard coded to the preview channel with a starting version of 0.8 and and update strategy of manual. As Maximo Application Suite matures the need to move away from Service Binding Operator v0.8 will be required. 
This PR externalizes three variables from the `oc_setup_mas_deps`role:
- sbo_channel
- sbo_startingcsv
- sbo_plan_approval
The defaults for these new variables will remain:
```yaml
sbo_channel: preview
sbo_startingcsv: service-binding-operator.v0.8.0
sbo_plan_approval: Manual
```
The configure-ocp playbook allows them to be overridden by checking for the following environment variables at runtime:
SBO_CHANNEL
SBO_STARTINGCSV
SBO_PLAN_APPROVAL
> [patch] externalize Service Binding Operator subscription settings

- ibm/mas_devops/roles/sls_install/tasks/bootstrap.yml
Update the {{sls_instance_name}}-bootstrap secret's key name "registration_key" to "registrationKey"
> [patch] fix sls secret registrationKey

- build/bin/.env.sh
- build/bin/docker-build.sh
- build/bin/git-release.sh
- build/bin/git-upload-asset.sh
- build/bin/initbuild.sh
A number of `TRAVIS_` environment variables remained unconverted to their `GITHUB_` equivalents.  This should resolve the problems with master branch builds generating `pre.master` builds instead of real release builds.
> [patch] Fixes for Travis -> Actions migration

- ibm/mas_devops/roles/bas_install/tasks/bascfg.yml
It's hard to determine what went wrong when the only error message is:
```
TASK [ibm.mas_devops.bas_install : Extract cluster name] ***********************
Thursday 09 December 2021 17:41:55 +0000 (0:00:00.996) 0:35:35.557 *****
ok: [localhost] => {
"msg": [
"Cluster Domain ...................... fvtdev-6f1620198115433da1cac8216c06779b-0000.eu-gb.containers.appdomain.cloud"
]
}
TASK [ibm.mas_devops.bas_install : set_fact] ***********************************
Thursday 09 December 2021 17:41:55 +0000 (0:00:00.034) 0:35:35.592 *****
ok: [localhost] => {"ansible_facts": {"temp": "fvtdev-6f1620198115433da1cac8216c06779b-0000"}, "changed": false}
TASK [ibm.mas_devops.bas_install : Lookup Certificate for BAS] *****************
Thursday 09 December 2021 17:41:55 +0000 (0:00:00.055) 0:35:35.647 …
```
> [patch] Additional debug for bascfg task

- ibm/mas_devops/roles/mongodb/files/ca.cnf
- ibm/mas_devops/roles/mongodb/tasks/providers/community.yml
This is a fix for:
https://github.com/ibm-mas/ansible-devops/issues/94
It will ensure that the self-signed CA and server certificate contain different CNs. If the CA and server certificate have the same CN hostname validation seems to fail in some instances when creating a secure connection.
> [patch] Do not duplicate CN in MongoCE CA and cert

- CONTRIBUTING.md
- docs/index.md
- ibm/mas_devops/README.md
- ibm/mas_devops/galaxy.yml
- ibm/mas_devops/roles/suite_app_configure/tasks/main.yml
- ibm/mas_devops/roles/suite_app_configure/vars/assist.yml
- ibm/mas_devops/roles/suite_app_configure/vars/health.yml
- ibm/mas_devops/roles/suite_app_configure/vars/iot.yml
- ibm/mas_devops/roles/suite_app_configure/vars/manage.yml
- ibm/mas_devops/roles/suite_app_configure/vars/monitor.yml
- ibm/mas_devops/roles/suite_app_configure/vars/mso.yml
- ibm/mas_devops/roles/suite_app_configure/vars/predict.yml
- ibm/mas_devops/roles/suite_app_configure/vars/safety.yml
- ibm/mas_devops/roles/suite_app_install/tasks/main.yml
- ibm/mas_devops/roles/suite_app_install/vars/assist.yml
- ibm/mas_devops/roles/suite_app_install/vars/health.yml
- ibm/mas_devops/roles/suite_app_install/vars/iot.yml
- ibm/mas_devops/roles/suite_app_install/vars/manage.yml
- ibm/mas_devops/roles/suite_app_install/vars/monitor.yml
- ibm/mas_devops/roles/suite_app_install/vars/mso.yml
- ibm/mas_devops/roles/suite_app_install/vars/predict.yml
- ibm/mas_devops/roles/suite_app_install/vars/safety.yml
- pipelines/samples/sample-pipeline.yaml
The time it takes various applications to install and configure can vary widly, implement support for per-application timeouts to make failure states less painful to the user by reducing the time they must wait before the ansible collection gives up retrying.
> [patch] Implement variable timeouts for app mgmt

- ibm/mas_devops/playbooks/dependencies/install-bas.yml
- ibm/mas_devops/roles/bas_install/README.md
- ibm/mas_devops/roles/bas_install/tasks/main.yml
The BAS install role does not check for required parameters being provided, when these are missed instead of providing the user with a nice clear error message the BAS install will fail and they must debug what happened.
This update will ensure that the installation is aborted instantly if either of the required storage classes are not defined.
> [patch] Add BAS storage classes validation

- ibm/mas_devops/roles/ocp_verify/tasks/main.yml
BAS install fails due to ROKS provisioning errors, we don't know why sometimes ROKS messes up this aspect of the cluster config, but it causes problems for one of our dependencies; BAS.
Add check in ocp verify that checks for one of the two secrets that we are expecting on ROKS.
- #102
> [patch] Verify default router secret is created in ROKS

- .gitignore
- ibm/mas_devops/roles/cp4d_db2wh/README.md
- ibm/mas_devops/roles/cp4d_db2wh/defaults/main.yml
- ibm/mas_devops/roles/cp4d_db2wh/tasks/cpd35/get_db2_certificate.yml
- ibm/mas_devops/roles/cp4d_db2wh/tasks/cpd35/get_db2_ssl_port.yml
- ibm/mas_devops/roles/cp4d_db2wh/tasks/cpd35/provision-instance.yml
- ibm/mas_devops/roles/cp4d_db2wh/tasks/cpd40/provision-instance.yml
- ibm/mas_devops/roles/cp4d_db2wh/tasks/main.yml
- ibm/mas_devops/roles/cp4d_db2wh/templates/cpd35/cp4d_db2_database_config.yaml.j2
- ibm/mas_devops/roles/cp4d_db2wh/templates/cpd35/create_db.json.j2
- ibm/mas_devops/roles/cp4d_db2wh/vars/cpd35.yml
- ibm/mas_devops/roles/cp4d_db2wh_manage_hack/README.md
- ibm/mas_devops/roles/cp4d_db2wh_manage_hack/tasks/main.yml
- ibm/mas_devops/roles/cp4d_db2wh_manage_hack/templates/setupdb.sh.j2
- pipelines/README.md
- pipelines/bin/install-pipelines.sh
- Previous approach was just to ignore errors, which masked real errors as well
- Add more missing documentation #3
- Intelligent defaulting of db2 version for 3.5 and 4.0 cp4d
- Insert multiple failure conditions into the code to correctly raise errors when expected conditions are not met
- consolidation of variable naming
- move setupdb definition into a template and use `oc cp` command to copy it into the container instead of stdin redirect with `oc exec`
- Fix username/password for cpd v3.5 JdbcCfg, as it was being set to entirely the wrong thing and would be unuseable for any applications
- #89
> [patch] Fix various issues with manage db2 support

- ibm/mas_devops/roles/cp4d_db2wh/tasks/cpd35/provision-instance.yml
- ibm/mas_devops/roles/suite_app_configure/vars/manage.yml
- pipelines/CONTRIBUTING.md
- pipelines/README.md
A couple of small fixes and updates to developer documentation:
- Add 1 hour to manage workspace config timeout.  Manage application workspace configuration takes a really long time, increase the timeout from 3 to 4 hours.
- Fix generation of `db2wh_svc_fqn` variable, this was still referring to a configmap lookup instead of simply computing it from the one value that we need to lookup - the instance ID.
> [patch] Increase manage appws timeout and fix db2wh_svc_fqn generation

- .github/workflows/ansible-publish.yml
- .github/workflows/tekton-publish.yml
- CONTRIBUTING.md
- ibm/mas_devops/galaxy.yml
- ibm/mas_devops/playbooks/mas/verify.yml
- ibm/mas_devops/roles/suite_verify/README.md
- ibm/mas_devops/roles/suite_verify/defaults/main.yml
- ibm/mas_devops/roles/suite_verify/tasks/main.yml
- pipelines/CONTRIBUTING.md
- pipelines/README.md
- Suite verify doesn't work with MAS 8.7 pre-release builds (due to the new OSDK introducing a `Failure` status condition)
- Update docs for suite_verify role #3
> [patch] Fix suite verify & add docs

- ibm/mas_devops/playbooks/dependencies/install-sls.yml
When trying to use the dev catalog for SLS the entitlement is not correctly set in the instal-lsls playbook. This change simply makes sure the vars:
artifactory_username
artifactory_apikey
are set correctly before trying to install SLS using the dev catalog.
> [patch] Entitlement vars not set for SLS dev catalogs

- ibm/mas_devops/roles/suite_app_configure/tasks/main.yml
- ibm/mas_devops/roles/suite_app_install/tasks/main.yml
The latest fvt pipelines are failing in the install application (specifically install-iot and install-manage).   The Created CRDs are showing the wait condition is true but it doesn't appear to be actually waiting and checking the conditions every minute as  expected.  The timestamps indicates that it ran in 45 seconds when it should have been waiting 10 mins for manage and 30 mins for IoT.   
The version of ansible was updated for the current build, and it may have resulted in the values of the variables to be modified.   
The changes that were made are:
- wait:  true     ===>   wait: yes
- delay: 0        ===>   delay: 5
> [patch] Change variables for wait on application code

- ibm/mas_devops/roles/amqstreams/tasks/main.yaml
Wait until the kafka listeners information is available in the status sub-resource.
- Fixes #163
> [patch] Improve wait logic for Kakfa cluster lookup

- ibm/mas_devops/roles/amqstreams/tasks/main.yaml
Got an issue with current master version of role `masdevops.amqstreams` while installing amq streams:
```
TASK [ibm.mas_devops.amqstreams : Lookup Kafka Resource] ***************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'kafka_cluster_lookup.resources | length > 0' failed. The error was: error while evaluating conditional (kafka_cluster_lookup.resources | length > 0): 'dict object' has no attribute 'resources'"}
```
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/amqstreams/tasks/main.yaml#L88
It seems it's just missing to include …
> [patch] Fix for undefined Kafka resource

- .github/workflows/ansible.yml
- ibm/mas_devops/roles/cp4d_db2wh/README.md
- ibm/mas_devops/roles/cp4d_db2wh/defaults/main.yml
- ibm/mas_devops/roles/cp4d_db2wh/tasks/setup_norootsquash.yml
The new task uses variables that are not declared within the role.
Added the following and updated the documentation:
```
cpd_registry: cp.icr.io
cpd_registry_user: cp
cpd_entitlement_key: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') }}"
```
- Bug fix for #172
- Also fixes a bug introduced into the build system in this commit: https://github.com/ibm-mas/ansible-devops/commit/b93a89c7cac82e29883a5f9969032e9ad862aea1 .. the Ansible workflow should only run on branch builds, not tags.
> [patch] Db2 norootsquash support uses undefined variables

- ibm/mas_devops/roles/cp4d_db2wh/tasks/setup_norootsquash.yml
Fix for the following failure in cp4d_db2wh role: the template file templates/norootsquash_deamonset.yml could not be found for the lookup
> [patch] Fix Deamonset / Daemonset typos

- ibm/mas_devops/roles/bas_install/tasks/main.yml
The BAS operator isn't very good.  It fails to install often, this hack addresses one main cause of install failure with BAS: the `createcluster` job fails and the BAS operator cannot handle the failure.
> [patch] Extra logic to recover from BAS install failures

- ibm/mas_devops/playbooks/ocp/login.yml
- ibm/mas_devops/roles/ocp_login/README.md
- ibm/mas_devops/roles/ocp_login/defaults/main.yml
- ibm/mas_devops/roles/ocp_login/tasks/login-quickburn.yml
- ibm/mas_devops/roles/ocp_login/tasks/login-roks.yml
- ibm/mas_devops/roles/ocp_login/tasks/login.yml
- ibm/mas_devops/roles/ocp_login/tasks/main.yml
- ibm/mas_devops/roles/ocp_verify/README.md
Implements the changes for issue#111 to allow the role `ocp_login` to be called with the environment variables `OCP_SERVER` and `OCP_TOKEN` to be used for the `oc login` command rather than a cluster type specific login.
Also makes changes to the `ocp_login` role to use asserts rather than fail module as per issue#124
> [minor] Allow ocp_server and ocp_token to be used for ocp_login

- image/ansible-devops/Dockerfile
- image/ansible-devops/ansible.cfg
- image/ansible-devops/requirements.txt
- We have two seperate pip installs for some reason (installing two different versions of openshift python package)
- Also locked all python packages to a set version, so we are not vulnerable to supply chain attacks (all the rage these days)
> [patch] Remove double pip install & lock versions

- bin/mas
It is not a requirement to provide additional configuration files, however the secret must exist for the pipeline to execute (it can be an empty secret with no data)
> [patch] Pipeline requires empty pipeline-additional-configs

- .github/CODEOWNERS
- bin/mas
- image/ansible-devops/Dockerfile
- pipelines/tasks/cp4d/create-db2-instance.yaml
- pipelines/tasks/cp4d/install-services-db2.yaml
- pipelines/tasks/cp4d/install-services-fullstack.yaml
- pipelines/tasks/cp4d/install-services-watsonstudio.yaml
- pipelines/tasks/dependencies/install-amqstreams.yaml
- pipelines/tasks/dependencies/install-mongodb-ce.yaml
- pipelines/tasks/dependencies/install-sls.yaml
- pipelines/tasks/dependencies/install-uds.yaml
- pipelines/tasks/mas/configure-app.yaml
- pipelines/tasks/mas/configure-suite.yaml
- pipelines/tasks/mas/gencfg-workspace.yaml
- pipelines/tasks/mas/hack-manage-db2.yaml
- pipelines/tasks/mas/install-app.yaml
- pipelines/tasks/mas/install-suite.yaml
- pipelines/tasks/mas/mustgather.yaml
- pipelines/tasks/ocp/configure-ocp.yaml
The playbooks are buried in Python's site-packages, create a symlink in the default directory.
- Update ClusterTasks to use the new simpler path /opt/apt-root/playbooks
- Add @whitfiea as codeowner for signoff to master branch privileges
> [patch] Create symlink to playbooks

- bin/mas-ansible.sh
- ibm/mas_devops/playbooks/cp4d/hack-worker-nodes.yml
- ibm/mas_devops/roles/ocp_setup_mas_deps/README.md
- ibm/mas_devops/roles/ocp_setup_mas_deps/defaults/main.yml
- ibm/mas_devops/roles/ocp_setup_mas_deps/tasks/certmanager/foundation-services.yml
- ibm/mas_devops/roles/ocp_setup_mas_deps/tasks/disable-ocp-upgrade.yml
- ibm/mas_devops/roles/ocp_setup_mas_deps/tasks/main.yml
- pipelines/samples/sample-pipeline.yaml
- Looks like a really bad merge in #187.  Foundation services install was moved into main, but has been restored to the cert-manager sub-task in that PR.
- Also, makes the modification to `ClusterVersion` controllable via a new parameter `ocp_disable_upgrade`, which defaults to false.
- Also, moves predict into a layer 3 in the pipeline so that it installs after both Monitor and Manage have installed.
> [patch] Fix breaking change in #187

- build/bin/copy-role-docs.sh
- mkdocs.yml
The role documentation for `gencfg_jdbc ` was missing from the original PR.
> [patch] Add missing gencfg_jdbc doc

- ibm/mas_devops/roles/gencfg_uds/templates/bascfg.yml.j2
The gencfg_uds role was incorrectly creating a CR that had the name {{ instance }}-uds-system but the monagent-mas within MAS is explicitly looking for {inst}-bas-system. As it doesn't find it then the suite CR is updated to say it has failed to integrate with BAS.
> [patch] BasCfg CR name has to be {inst}-bas-system

- ibm/mas_devops/roles/cp4d_install_services/tasks/main.yml
- ibm/mas_devops/roles/cp4d_install_services/tasks/watsonstudiocfg.yml
- ibm/mas_devops/roles/db2u/tasks/main.yml
- ibm/mas_devops/roles/db2u/tasks/suite_jdbccfg.yml
- ibm/mas_devops/roles/suite_app_install/tasks/main.yml
- ibm/mas_devops/roles/suite_install/tasks/ibm-common-services.yml
- ibm/mas_devops/roles/suite_install/tasks/main.yml
- image/ansible-devops/save-junit-to-mongo.py
- pipelines/samples/sample-pipelinesettings-roks.yaml
- pipelines/samples/sample-pipelinesettings.yaml
Fixes the IndexError seen in issue #245 caused by the fact that the testcase classname doesn't have ibm_mas/devops in the name for playbooks (it does for roles). The code now checks for the existence of the strong before chopping it. It also chops the playbook name so we end up with testcase classnames like the following for playbooks and roles:
This PR also changes the few places that still used the deprecated community.kubernetes module and changes to use kubernetes.core as per issue #250 
Final change was to add SLS_LICENSE_FILE to the sample pipeline settings as this is now required when bootstrapping.  
Tested in pipeline and manually set "TRAVIS_BUILD_NUMBER" and "DEVOPS_MONGO_URI" to push test results to mongo. Also ran pipeline against changed roles that changed to the …
> [patch] Fixes indexerror in save-to-junit script + change to use kubernetes.core

- CONTRIBUTING.md
- bin/mas-ansible.sh
- docs/index.md
- docs/playbooks/fullstack-roks.md
- docs/playbooks/lite-core-roks.md
- docs/playbooks/lite-manage-roks.md
- ibm/mas_devops/README.md
- ibm/mas_devops/galaxy.yml
- ibm/mas_devops/plugins/filter/filters.py
- ibm/mas_devops/roles/suite_app_configure/README.md
- ibm/mas_devops/roles/suite_app_configure/defaults/main.yml
- ibm/mas_devops/roles/suite_app_configure/tasks/main.yml
- ibm/mas_devops/roles/suite_app_configure/vars/defaultspecs/health.yml
- ibm/mas_devops/roles/suite_app_configure/vars/defaultspecs/hputilities.yml
- ibm/mas_devops/roles/suite_app_configure/vars/defaultspecs/manage.yml
- pipelines/CONTRIBUTING.md
- pipelines/README.md
Updates the changelogs for new release.
Fix a few doc issues related to SLS_LICENSE_FILE.
Fixes an issue where if MAS_APPWS_COMPONENTS is not set then the Manage and Health Workspace CRs fail as these require (from the CRDs) that the spec.components contains "base" for ManageWorkspace and "health" for health Workspace (even though the operator will install them anyway).
> [patch] Fix defaults for MAS_APPWS_COMPONENTS and update changelogs

- docs/playbooks/lite-core-quickburn.md
- docs/playbooks/lite-core-roks.md
- ibm/mas_devops/playbooks/lite-core-quickburn.yml
- ibm/mas_devops/playbooks/lite-core-roks.yml
Various readmes for playbooks didn't contain the requirement for the new SLS_LICENSE_FILE var that is needed.
Also the lite quickburn playbook didn't contain the role to setup ocs (storage) so no storage class was available when trying to deploy mongo to quickburn. This was raised in issue #258
> [patch] update readmes and call ocs setup role for quickburn

- image/ansible-devops/Dockerfile
- image/ansible-devops/ibmcloud-oc.sh
- image/ansible-devops/run-playbook.sh
Thought this was sorted a long time ago, clearly not.  The image as-is (and thus the pipeline which uses the image), will only be usable in a IBMCloud ROKS cluster.  Far from desirable.
The ansible-devops container currently runs a script (`ibmcloud-oc.sh`) as part of the `run-playbook.sh` script.  This is entirely redundant:
- When running in cluster (e.g. as part of a pipeline) the pod will already have access to the local OCP without a login
- When using the container as a route to manually execute commands, the end-user will be able to `oc login` to any cluster they want
I don't remember the details of why this existed in the first place, but it's definitely not required, and it limits the new one-click in-cluster install to only IBM Cloud ROKS clusters so must be removed.
> [patch] Remove ibmcloud-oc login hack

- build/bin/initbuild.sh
The current regex doesn't work for double digit version numbers (e.g. `10.0.0`).  Replacing `\d` with `[0-9]` seems to work.  The regex could be improved further to be honest, but that's out of the scope of this work.
> [patch] Fix build system semver regex

- ibm/mas_devops/playbooks/ocp_fyre_provision.yml
We renamed the `ocp_setup_ocs` role to simply `ocs`, the Fyre provision playbook wasn't updated to match this.
> [patch] Fix name of ocs role in fyre playbook

- ibm/mas_devops/roles/cert_manager/README.md
- ibm/mas_devops/roles/cluster_monitoring/README.md
- ibm/mas_devops/roles/common_services/README.md
- image/ansible-devops/save-junit-to-mongo.py
- pipelines/tasks/appconnect.yaml
- pipelines/tasks/cert-manager.yaml
- pipelines/tasks/cluster-monitoring.yaml
- pipelines/tasks/common-services.yaml
- pipelines/tasks/cos.yaml
- pipelines/tasks/cp4d.yaml
- pipelines/tasks/cp4d_service.yaml
- pipelines/tasks/db2.yaml
- pipelines/tasks/gencfg-workspace.yaml
- pipelines/tasks/ibm-catalogs.yaml
- pipelines/tasks/kafka.yaml
- pipelines/tasks/mongodb.yaml
- pipelines/tasks/nvidia-gpu.yaml
- pipelines/tasks/sbo.yaml
- pipelines/tasks/sls.yaml
- pipelines/tasks/suite-app-config.yaml
- pipelines/tasks/suite-app-install.yaml
- pipelines/tasks/suite-config.yaml
- pipelines/tasks/suite-db2-setup-for-manage.yaml
- pipelines/tasks/suite-dns.yaml
- pipelines/tasks/suite-install.yaml
- pipelines/tasks/suite-verify.yaml
- pipelines/tasks/uds.yaml
- Support more optional parameters in Tekton tasks
- Doc updates
- Include support for `devops_mongo_uri`, `devops_suite_name`, and `devops_build_number` in all tasks.  These are key to internal FVT, and allow for pipeline execution results to be saved to a mongo database.
> [patch] Miscellanous task and documentation updates

- ibm/mas_devops/playbooks/oneclick_add_manage.yml
- ibm/mas_devops/roles/suite_db2_setup_for_manage/tasks/main.yml
- The manage playbook doesn't define the required `db2_namespace` property
- The suite_db2_setup_for_manage role doesn't check for required properties being set
This results in confusing failure message when the role tries to copy files into the pod, especially if the user's active namespace if the `db2u` one as it will find the pod, but fail to copy to it.
> [patch] Fix handling of required properties in db2_setup role

- ibm/mas_devops/roles/sbo/tasks/install/stable.yml
Increasing number of attemps from 20 to 30
That is because operator took more than 20 minutes to be installed, which failed pipeline:
... and looking some time after,  Installplan instance was good and SBO overall has been installed successfully:
> [patch] Increase SBO timeout

- ibm/mas_devops/roles/db2/README.md
- ibm/mas_devops/roles/db2/tasks/main.yml
- ibm/mas_devops/roles/db2/tasks/setup_norootsquash.yml
- ibm/mas_devops/roles/db2/templates/db2ucluster.yml.j2
- ibm/mas_devops/roles/db2/templates/norootsquash_daemonset.yml.j2
Updates the db2 role so that the noroot_squash daemonset is created which is needed for file storage backed by NFS.
Also removes settings from the db2ucluster that linked the user registry for db2ucluster to an instance of cp4d. As there is no cp4d then this won't work and will also stop ldap user registry configuration.
Also deletes the db2 pod if the db2ucluster is newly created to workaround the issue with db2u not allowing TLS connects when it first started.
> [patch] db2u fix for NFS storage + remove cp4d settings

- CONTRIBUTING.md
- build/bin/initbuild.sh
- ibm/mas_devops/galaxy.yml
- ibm/mas_devops/roles/common_services/README.md
- ibm/mas_devops/roles/common_services/defaults/main.yml
- ibm/mas_devops/roles/common_services/templates/subscription.yml.j2
- pipelines/tasks/common-services.yaml
Exposes new **optional** parameter `common_services_catalog_source` and associated environment variable `COMMON_SERVICES_CATALOG_SOURCE`.  The primary use of these is when performing an air gap install.
> [patch] Make common-services catalog source configurable

- ibm/mas_devops/roles/ocp_provision/defaults/main.yml
Convert from six 8x32 worker nodes to three 16x64.300gb worker nodes.  This gives us a significant increase in local disk capacity on each worker (and a 50% increase in total disk capacity across the cluster) ... and it actually works out 10 cents/hour cheaper for customers for the same CPU and memory.
> [patch] Change default ROKS worker flavour

- docs/changes.md
- ibm/mas_devops/README.md
- image/ansible-devops/Dockerfile
- The docker image already installs the IBM Cloud CLI, but needs the IBM `container-service` plugin enabled as well to be able to do anything useful in the context of this collection.
- Also upgrades the Python runtime in the Docker image from 3.8 to 3.9
> [patch] Install container-service plugin

- ibm/mas_devops/roles/ocp_roks_upgrade_registry_storage/tasks/main.yml
There's a timing window where the PVC doesn't yet exist.  Addition of a simple retry loop should close this window.
> [patch] Loop until we find the registry PVC

- .github/workflows/ansible-publish.yml
Only the `ansible` workflow was updated to reference the changes to the Dockerfile in 10.1.0 ... this fix applies the same changes to `ansible-release`.
Additionally, the 10.1.0 container image has been manually pushed to quay.io to complete the 10.1.0 release.
> [patch] Fix ansible-publish github workflow

- ibm/mas_devops/roles/db2/templates/suite_jdbccfg.yml.j2
This PR contains changes to build the jdbccfg in the db2 role respecting the `mas_config_scope` provided.
> [patch] fixing jdbccfg template to consider scope

- docs/playbooks/oneclick-core.md
SLS_ENTITLEMENT_FILE was changed to SLS_LICENSE_FILE but the export was not taken out of the docs
> [patch] removed SLS_ENTITLEMENT_FILE

- ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
Data dictionary should install from development catalog if we are installing MAS from development catalogs.
> [patch] Fix DD support for development installs

- ibm/mas_devops/roles/suite_dns/tasks/main.yml
- ibm/mas_devops/roles/suite_install/tasks/main.yml
In issue https://github.com/ibm-mas/ansible-devops/issues/63 it is seen that when no cluster issuer is  set then the custom_cluster_issuer gets set to None rather than an empty string. Even when using the same ansible levels I wasn't able to reproduce this. The change is to cope with the value being None and treat it the same as empty string
> [patch] Cope with custom_cluster_issuer being None

- ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
This change will fix dataDictionary installation in our automated environment.
The Camel Case has been introduced to follow the standards.
> [patch] Fix settings.datadictionary to camelCase

- ibm/mas_devops/roles/suite_install/tasks/main.yml
During MAS install, if `mas_domain` is not set the code to generate a default domain based on the cluster's ingress is broken.  This fixes the regression introduced in #349
> [patch] Fix auto-generation of mas_domain

- ibm/mas_devops/roles/sbo/tasks/install/stable.yml
- ibm/mas_devops/roles/sbo/templates/subscription-stable.yml
- ibm/mas_devops/roles/sbo_upgrade/tasks/sbo_upgrade/stable.yml
- ibm/mas_devops/roles/sbo_upgrade/templates/sbo/subscription-stable.yml
The recent release of SBO v1.1.0 has broken ServiceBinding instances within MAS. This change will lock the SBO subscription at v1.0.1 when using the `stable` channel. This includes new installs and upgrades.
> [patch] lock sbo on stable channel to v1.0.1

- ibm/mas_devops/playbooks/ocp_rosa_deprovision.yml
- ibm/mas_devops/playbooks/ocp_rosa_provision.yml
- ibm/mas_devops/roles/ocp_deprovision/README.md
- ibm/mas_devops/roles/ocp_deprovision/defaults/main.yml
- ibm/mas_devops/roles/ocp_deprovision/tasks/main.yml
- ibm/mas_devops/roles/ocp_deprovision/tasks/providers/quickburn.yml
- ibm/mas_devops/roles/ocp_deprovision/tasks/providers/rosa.yml
- ibm/mas_devops/roles/ocp_login/README.md
- ibm/mas_devops/roles/ocp_login/defaults/main.yml
- ibm/mas_devops/roles/ocp_login/tasks/login-quickburn.yml
- ibm/mas_devops/roles/ocp_login/tasks/login-roks.yml
- ibm/mas_devops/roles/ocp_login/tasks/login-rosa.yml
- ibm/mas_devops/roles/ocp_login/tasks/login.yml
- ibm/mas_devops/roles/ocp_login/tasks/main.yml
- ibm/mas_devops/roles/ocp_provision/README.md
- ibm/mas_devops/roles/ocp_provision/defaults/main.yml
- ibm/mas_devops/roles/ocp_provision/tasks/main.yml
- ibm/mas_devops/roles/ocp_provision/tasks/providers/rosa.yml
New playbooks:
- `ibm.mas_devops.provision_rosa`
- `ibm.mas_devops.deprovision_rosa`
Updates to roles (including documenation) to add support for `cluster_type` = `rosa`
- `ibm.mas_devops.ocp_provision`
- `ibm.mas_devops.ocp_deprovision`
- `ibm.mas_devops.ocp_login`
There is still more work to do to support MAS on ROSA (e.g. enabling EFS storage class), this is just the starting point
> [minor] Support OCP on ROSA

- ibm/mas_devops/playbooks/oneclick_core.yml
When environment variable support was added to the oneclick playbooks, the `mas_channel` property was incorrectly linked to the `MAS_APP_CHANNEL` env var instead of `MAS_CHANNEL`
> [patch] Use correct env var for mas_channel

- ibm/mas_devops/roles/cp4d_service/templates/services/wsl.yml.j2
This is the final piece in being able to lock down the product version of Cloud Pak for data independant from the operator version.  With this update the `NotebookRuntimes` will be configured at the same product version that Watson Studio is deployed at.  This ensures that the breaking changes introduced in patch levels of the CP4D product do not break the installation.
> [patch] Add wsrt_operand_version to Watson Studio spec

- ibm/mas_devops/roles/db2/templates/norootsquash_daemonset.yml.j2
Required for private mirror registry support, otherwise the `ImageContentSourcePolicy` will not be used.
> [patch] Reference norootsquash image by digest

- ibm/mas_devops/roles/ocs/tasks/storage.yml
This role only works if you happen to already be set to the `openshift-storage` namespace as the default.
> [patch] Add missing namespace to StorageCluster lookup

- ibm/mas_devops/roles/db2/tasks/setup_norootsquash.yml
It can take a long time to create daemonset on all nodes, remove the wait on create and improve the polling to wait for all daemonset pods to be ready instead of only waiting for one to be ready.
> [patch] Improve norootsquash daemonset management

- ibm/mas_devops/roles/cp4d/tasks/install-cp4d.yml
- ibm/mas_devops/roles/ibm_catalogs/tasks/main.yml
Test evidence:
-----
Experienced that scenario in `fvt-dev` during cp4d task:
**Update**: `fvt-release` had the same behavior
```
FAILED - RETRYING: [localhost]: install-cp4d : Wait for controlPlaneStatus to be 'Completed' (2m delay) (38 retries left).
FAILED - RETRYING: [localhost]: install-cp4d : Wait for controlPlaneStatus to be 'Completed' (2m delay) (37 retries left).
ok: [localhost] => {"api_found": true, "attempts": 25, "changed": false, "resources": [{"apiVersion": "cpd.ibm.com/v1", "kind": "Ibmcpd", "metadata": {"annotations": {"kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"cpd.ibm.com/v1\",\"kind\":\"Ibmcpd\",\"metadata\":{\"csNamespace\":\"ibm-common-services\",\"name\":\"ibmcpd\",\"namespace\":\"ibm-cpd\"},\"spec\":{\"license\":{\"accept\":true,\"license …
```
> [patch] Improve catalog & CP4D installation checks

- ibm/mas_devops/roles/uds/tasks/install/main.yml
We've seen a significant increase in UDS install time causing the existing 40 minute timeout for UDS install to be hit on multiple occasions in testing.  This update increases the timeout while we wait for UDS to be ready to use following initial install so that the pipeline is more resiliant to these longer installs.  We now give UDS up to 1 hour to complete it's installation before considering it a failed installation.
> [patch] Increase install timeout for UDS

- ibm/mas_devops/roles/suite_db2_setup_for_manage/tasks/main.yml
Sometimes, when we run the `suite_db2_setup_for_manage` role, the Db2 pod is not yet ready so the attempt to copy the setup script into the pod fails.  Add `wait` to the `k8s_info` call to query the pod name so that hopefully the pod is always ready by the time we attempt to copy the file into the container.
> [patch] Wait for Db2 pod to be ready

- ibm/mas_devops/roles/sls/tasks/install/install_digest_cm.yml
- ibm/mas_devops/roles/suite_app_install/tasks/install_digest_cm.yml
- ibm/mas_devops/roles/suite_install/tasks/install_digest_cm.yml
To move beyond supporting a single specific version of MAS in an offline/air gap/private registry installation we need to take advantage of the `OperatorCondition` resource to dynamically determine the version of the Operator that is installed, so that we can lay down the correct version of the image digest map that current MAS versions rely on for such support.  Future releases of MAS will eventaully no longer need this additional configmap to the installed, but until then this is essential to enable offline installations.
> [patch] Use OperatorConditions to determine digest version

- ibm/mas_devops/roles/cp4d_service/defaults/main.yml
- ibm/mas_devops/roles/db2/defaults/main.yml
this is to fix a minor issue with the default name used for the provisioned wd instance:
also, updating the default db2 instance version to latest available
> [patch] fix for wd instance name

- ibm/mas_devops/roles/ibm_catalogs/defaults/main.yml
This update introduces the 220805 catalog source which provides bug fixes and security updates for `ibm-sls` and `ibm-mas-iot`.  The most significant update is that IoT should now be useable in an airgap environment with the 8.5.1 release.
> [minor] Catalog update for IoT airgap support fix

- .github/workflows/ansible-publish.yml
- .github/workflows/ansible.yml
We're being asked to run [OWASP dependency checker](https://owasp.org/www-project-dependency-check/) against our open source repositories.  It doesn't seem to do much for Ansible, but it ticks another box in a spreadsheet somewhere that we are running it anyway :)
We are running the GitHub Action available here: https://github.com/dependency-check/Dependency-Check_Action
> [patch] Integrate OWASP dependency check

- ibm/mas_devops/roles/ibm_catalogs/defaults/main.yml
We were still defaulting to the catalog with the `-amd64` arch suffix.
> [patch] Fix default catalog version/tag

- ibm/mas_devops/common_tasks/get_ingress_cert.yml
- ibm/mas_devops/roles/cos/tasks/providers/ocs.yml
- ibm/mas_devops/roles/ocp_verify/tasks/main.yml
- ibm/mas_devops/roles/uds/tasks/install/udscfg.yml
The cluster ingress certificate lookup doesn't work on ROSA.  This PR fixes that while centralizing the fixed logic for looking up the ingress cert secret.
```
TASK [ocp_verify : Debug cluster certificate secret search] *****************************************************************************************************************************************************************************************************************Friday 19 August 2022  12:47:16 +0100 (0:00:00.057)       0:00:04.883 *********
ok: [localhost] => {
"msg": [
"Found Router Default Secret ........... False",
"Found Cluster Ingress Secret .......... False",
"Found Cluster Primary Secret .......... True",
"Cluster Ingress Cert Secret Name ...... djprosa1-primary-cert-bundle-secret",
"Cluster Ingress Cert …
```
> [patch] Fix certificate secret check for ROSA

- ibm/mas_devops/common_tasks/get_ingress_cert.yml
- ibm/mas_devops/roles/cos/README.md
- ibm/mas_devops/roles/ocp_verify/README.md
- ibm/mas_devops/roles/uds/README.md
Add support for optional `OCP_INGRESS_TLS_SECRET_NAME` environment variable which will allow the user to explcitly control the name of the secret containing the OCP default ingress TLS certificate.  This is only required when the secret name does not match any of the known patterns that are supported out of the box by the collection.
> [patch] Support OCP_INGRESS_TLS_SECRET_NAME

- ibm/mas_devops/roles/appconnect/README.md
- ibm/mas_devops/roles/appconnect/defaults/main.yml
Current default version of App Connect is quite old now, and does not support OCP 4.10.  v4.2 is the latest version that offers support for all levels of OCP required in MAS.
> [patch] Correct support versions of IBM App Connect

- ibm/mas_devops/playbooks/oneclick_add_assist.yml
- ibm/mas_devops/roles/cos/tasks/providers/ibm.yml
- fixing default workspace_id to the set by variable just like other one click playbooks
- fixing cos creation to accept resource group param otherwise it will fail to lookup by resource group
> [patch] Fix Assist playbook & IBM COS resource creation

- ibm/mas_devops/roles/ocs/README.md
The documentation states that the default is `4.8`, but it's `4.10` in the code.
> [patch] Fix default OCP_RELEASE in OCS docs

- ibm/mas_devops/roles/appconnect/README.md
- ibm/mas_devops/roles/appconnect/defaults/main.yml
- ibm/mas_devops/roles/appconnect/tasks/main.yml
- ibm/mas_devops/roles/appconnect/templates/dashboard.yaml
The updates to the `appconnect` role do not work:
- The version set to `12.0` resolves to an inccorect version (the latest available `12.0`) that does not match the license (and does not match the version that HP Utilities claims to support.
- The role does not wait for the App Connect operator deployment to be ready, thus the admission controller webhook can not be reached when the dashboard is attempted to be created.
> [patch] Fix App Connect version management

- ibm/mas_devops/roles/cp4d/tasks/entitlement.yml
The `wd-minio-discovery-update-label` job pod will fail with image pull errors **sometimes** if the `prod-cred` secret referenced in it's deployment template is not present.  This update creates that secret.
```
"containers": [
{
"command": [
"/bin/bash",
"-c",
"kubectl label --overwrite pvc --selector app.kubernetes.io/instance=$MINIO_RELEASENAME,helm.sh/chart=ibm-minio velero.io/exclude-from-backup=$MINIO_EXCLUDE_FROM_BACKUP icpdsupport/empty-on-nd-backup=$MINIO_EMPTY_ON_BACKUP icpdsupport/ignore-on-nd-backup=$MINIO_IGNORE_ON_BACKUP "
],
"env": [
{ "name": "MINIO_RELEASENAME", "value": "wd-minio" },
{ "name": "MINIO_IGNORE_ON_BACKUP", "value": "true" },
{ "name": "MINIO_EMPTY_ON_BACKUP", "value": "true" },
{ "name": "MINIO_EXCLUDE_FROM_BACKUP", "value": "true" }
],
"image": …
```
> [patch] Create "prod-cred" secret sometimes used by Discovery

- ibm/mas_devops/roles/kafka/templates/masuser.yml.j2
The new FPL component of the IoT tool utilises idempotent Kafka producers.  This capability of the Kafka producer client requires that the Kafka user has cluster level ACLs in the Kafka cluster.
Without these permissions, attempts to publish events will fail and messages such as the following would be present in the logs of `fpl-pipelinerouter-<n>` and `fpl-functionsexecutor-<n>` pods:
```
[11/03/22 2:02:43:704 UTC] 53    com.ibm.wiotp.internal.pipeline.pipelinerouter.workflow.workers.EventPublisher SEVERE lambda$processInput$0 
[masdev]: failed to publish metric record: ProducerRecord(topic=fvtdev_fpl-repartition-events, ... 
becuase: Cluster authorization failed.
2022-11-03 02:02:47,816 INFO exited: iotapp (exit status 1; not expected)
```
Provided that users install or update MAS via …
> [patch] maskafka user needs cluster level ACLs for FPL producers

- ibm/mas_devops/roles/suite_app_install/tasks/install_digest_cm.yml
- ibm/mas_devops/roles/suite_app_upgrade/tasks/upgrade.yml
We fixed many examples of this timing window in the previous release, but missed a couple it seems.  When the OperatorCondition is not created promptly the code will fail, a small retry loop has been effective at eliminating this timing window:
```
TASK [ibm.mas_devops.suite_app_install : detect-airgap : Debug Airgap detection] ***
Friday 04 November 2022  14:38:09 +0000 (0:00:00.049)       0:00:21.774 ******* 
ok: [localhost] => {
"msg": "Airgap environment .................... True"
}
TASK [ibm.mas_devops.suite_app_install : Enable use of image digests] **********
Friday 04 November 2022  14:38:09 +0000 (0:00:00.039)       0:00:21.814 ******* 
included: /opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/suite_app_install/tasks/install_digest_cm.yml for …
```
> [patch] Fix timing window with OperatorCondition check

- ibm/mas_devops/roles/mongodb/tasks/providers/community.yml
This update fixes the following failure in the `mongodb` role:
```
The conditional check 'mongodb_statefulset.resources | length > 0' failed. The error was: error while evaluating conditional (mongodb_statefulset.resources | length > 0): 'dict object' has no attribute 'resources'
```
There's a small window where we can check for the stateful set when resources will not even be returned in the result.
> [patch] Fix timing window in Mongo install

- ibm/mas_devops/roles/install_operator/templates/ibm-entitlement-with-artifactory.json.j2
Previous commit changed the entry from `cp.icr.io/cp` to `icr.io` ... both should work based on previous tests, but why take the risk? :)
> [patch] Set ICR entitlement host to cp.icr.io/cp

- ibm/mas_devops/roles/cp4d_service/tasks/gencfg/gencfg-wsl.yml
- ibm/mas_devops/roles/cp4d_service/tasks/install.yml
Sometimes CPD admin user does not have the proper permission to create analytics projects. Root cause for that to happen is still unknown; problem has been identified in cpd 4.0.9 and 1 of 2 environments created with same settings (fvtdev and fvtstable) had the issue. It breaks `cp4d_service` (wsl) installation and then breaks the pipeline:
```
Forbidden error when calling api to create analytics project:
TASK [ibm.mas_devops.cp4d_service : gencfg-wsl : Create a analytics project if one is needed] ***
Thursday 10 November 2022  00:30:15 +0000 (0:00:00.088)       2:07:23.490 ***** 
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content_length": "100", "content_type": "text/html; charset=utf-8", "date": "Thu, 10 Nov 2022 00:30:16 GMT", "elapsed": 0, "etag": …
```
> [patch] Grant CPD admin user permission to create projects

- ibm/mas_devops/roles/ibm_catalogs/tasks/main.yml
- ibm/mas_devops/roles/ibm_catalogs/tasks/update-digest-maps.yml
- ibm/mas_devops/roles/suite_install_digest_cm/tasks/actions/merge.yml
- ibm/mas_devops/roles/suite_install_digest_cm/tasks/actions/new.yml
- ibm/mas_devops/roles/suite_install_digest_cm/tasks/main.yml
- ibm/mas_devops/roles/suite_install_digest_cm/templates/configmap.yml.j2
This update addressed a flaw discovered in the update process in a disconnected MAS install.
When a catalog source is updated in a connected install, that is the only action required.  The operators will update and will in turn update the operands under their control.
However, in a disconnected install the need for the additional configmap containing the digest map references must be updated before the operator is updated, otherwise when the operator updates it will fall back to using image tags instead of digests, and will be unable to resolve the container images from the mirror registry.
The need for this additional config map to be installed is in the process of being eliminated, but at present most MAS operators require this step.
This update integrates the action of updating the …
> [patch] Update digest maps before updating catalogsource

- docs/playbooks/oneclick-core.md
- docs/playbooks/oneclick-iot.md
- docs/playbooks/oneclick-manage.md
- docs/playbooks/oneclick-monitor.md
- docs/playbooks/oneclick-optimizer.md
- docs/playbooks/oneclick-predict.md
- docs/playbooks/oneclick-visualinspection.md
- ibm/mas_devops/roles/suite_mustgather_download/templates/deployment.yml
User reported various pages in the documentation that are still referencing the old container image (ibmmas/ansible-devops); this update fixes all references to point at `quay.io/ibmmas/cli`
> [patch] Remove refs to old container image

- ibm/mas_devops/roles/suite_upgrade/tasks/upgrade.yml
Fix for a simple typo in the `suite_upgrade` role.
> [patch] Fix unquoted string in "until" clause

- ibm/mas_devops/common_vars/casebundles/v8-220805-amd64.yml
- ibm/mas_devops/roles/ibm_catalogs/tasks/update-digest-maps.yml
- ibm/mas_devops/roles/suite_upgrade/tasks/upgrade.yml
Restructuring of the common vars left the update method non-functional in airgap environments; when we update the config map we need to make updates for multiple versions based on the different channels available to the user in the catalog.
> [patch] Fix update support for disconnected installs

- ibm/mas_devops/roles/suite_app_install/defaults/main.yml
- ibm/mas_devops/roles/suite_app_install/vars/iot.yml
- ibm/mas_devops/roles/suite_app_install/vars/visualinspection.yml
Defaults should be in defaults, setting env var lookups in var files will mean the env vars override any values passed in as ansible vars - even if the former are not set and the latter are.
> [patch] Fix application install role

- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wd.yml
- ibm/mas_devops/roles/sls/tasks/install/sls-verify.yml
Add extra retries while we wait for SLS and Watson Discovery instalation to complete.  Recent testing has shown that the current timeouts are no longer sufficient/the install time is too close to the timeout.
> [patch] Handle slow install for SLS and Discovery

- ibm/mas_devops/roles/mongodb/tasks/providers/community.yml
We're seeing in slower clusters that the stateful set can take more than the 30 minutes we currently allow for it to be ready.  This update increases the timeout 50% to 45 minutes.
> [patch] Increase timeout for mongo sts

- ibm/mas_devops/roles/ocp_simulate_disconnected_network/templates/mc2.yml.j2
Fix registry cert path so that it is being used to pull fvt test cases images from the registry.
> [patch] Fix registry CA cert path used when simulating airgap network

- ibm/mas_devops/roles/ocp_efs/templates/efs-csi-storage-class.yml.j2
This fixes the errors when deploying db2 on ROSA
> [patch] Fix permission error on EFS Storage class

- ibm/mas_devops/roles/cp4d_service/tasks/prereqs/prereqs-wd.yml
While waiting for WD prereqs, we wait for a field to contain a certain value but we do not wait for the field to first exist, so on a slow cluster the logic will fail as below:
```
TASK [ibm.mas_devops.cp4d_service : prereqs-wd : Wait for operand request to be processed] ***
Wednesday 21 December 2022  01:17:37 +0000 (0:00:01.194)       0:00:08.768 **** 
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'cpd_cr_lookup.resources[0].status.phase == \"Running\"' failed. The error was: error while evaluating conditional (cpd_cr_lookup.resources[0].status.phase == \"Running\"): 'dict object' has no attribute 'status'"}
```
> [patch] Close timing window in WD wait logic

- ibm/mas_devops/roles/db2/tasks/create_ldap_user.yml
This update increases the rety limit when setting up new LDAP users for Db2 to avoid failures in slower clusters.
> [patch] Increase retry count for Db2 LDAP users

- ibm/mas_devops/roles/uds/tasks/install/udscfg.yml
https://github.com/ibm-mas/ansible-devops/issues/564
The regex in the task `udscfg` causes a deprecation warning (and error in Python 3.11). 
Simply move the global flag that allows for matching newlines to the beginning of the regex.
> [patch] Fix regex in udscfg that manipulates certs

- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wd.yml
The `Wait for the wd-discovery-cn-postgres service account to appear` task times out on some clusters, yet on inspection of the cluster after the fact, we can see that the service account was eventually created; it just took a very long time.  This update increases the timeout to 2 hours (from 40 minutes) to accomodate the slower CP4D times.
```
TASK [ibm.mas_devops.cp4d_service : wait-wd : Wait for the wd-discovery-cn-postgres service account to appear] ***
Wednesday 21 December 2022  14:39:24 +0000 (0:00:00.069)       0:11:42.655 **** 
FAILED - RETRYING: [localhost]: wait-wd : Wait for the wd-discovery-cn-postgres service account to appear (40 retries left).
FAILED - RETRYING: [localhost]: wait-wd : Wait for the wd-discovery-cn-postgres service account to appear (39 retries left). …
```
> [patch] Increase timeout waiting for Discovery SA

- docs/changes.md
- ibm/mas_devops/roles/ocp_provision/README.md
- ibm/mas_devops/roles/ocp_provision/defaults/main.yml
- ibm/mas_devops/roles/ocp_provision/tasks/providers/fyre.yml
- ibm/mas_devops/roles/ocp_provision/templates/fyre/product_group.json.j2
- ibm/mas_devops/roles/ocp_provision/templates/fyre/quick_burn.json.j2
MAS Devops Ansible Collection to support enabling FIPS when provisioning an OCP cluster
fyre environment provision will be configured by setting an environment variable `OCP_FIPS = yes/no`
- https://github.ibm.com/wiotp/tracker/issues/11038
Have created quickburn cluster on fyre by providing environment variable `OCP_FIPS` and also ran without providing the env
> [minor] Support FIPS option on FYRE infrastructure

- ibm/mas_devops/roles/cert_manager/tasks/main.yml
Fixes this failure introduced by #563 
```
TASK [ibm.mas_devops.cert_manager : Increase common service cpu limit to account for increased cert privateKey sizings] ***
Thursday 22 December 2022  14:01:14 +0000 (0:00:01.490)       0:00:04.953 ***** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find or access 'templates/ibm-cert-manager-CommonService.yml'\nSearched in:\n\t/opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/cert_manager/templates/templates/ibm-cert-manager-CommonService.yml\n\t/opt/app-root/lib64/python3.9/site-packages/ansible_coll …
```
> [patch] Fix template name

- ibm/mas_devops/roles/cert_manager/tasks/main.yml
Following more issues with the updates from #563 after an initial fix in #572, the updates from that PR have now been disabled.
```
TASK [ibm.mas_devops.cert_manager : Increase common service cpu limit to account for increased cert privateKey sizings] ***
Thursday 22 December 2022  14:36:20 +0000 (0:00:01.412)       0:00:04.905 ***** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find exact match for operator.ibm.com/v1alpha1.CommonService by [kind, name, singularName, shortNames]"}
```
> [patch] Disable new task introduced in #563

- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wd.yml
We want to catch this pod getting stuck in image pull backoff, but lately it's taking longer to get into this state and we are missing it ... we patch the serviceaccount that it uses the expected imagePullSecret (Discovery team are aware of the bug, but no plans to fix it yet), but in most cases we won't patch it early enough for the pod to work first time; thus we watch for the pod to be in `ImagePullBackOff` and if we detect this, we delete pod, forcing it to pull using the now-patched service account.
```
wd-discovery-cn-postgres-1-initdb--1-lnqss         0/1     ImagePullBackOff   0               31m
```
> [patch] Increase ImagePullBackoff polling to 30 minutes

- ibm/mas_devops/roles/uds/tasks/install/main.yml
- ibm/mas_devops/roles/uds/templates/crunchy-postgres/subscription.yml
UDS installs the operator with a startingCSV set explicitly to 5.1.0 for some unknown reason, the best case scenario is that we go through needless upgrades, wasting time, to worst case scenario is that the upgrade path in the channel hits a bad version of Postgres (which is happening in December 2022)
Crunchy team have "fixed" the issue by releasing a new version, but the bad version is still in the channel graph, so when we automatically upgrade from 5.1.0 we hit the bad version and are unable to install intermediate version 5.2.0
```
Back-off pulling image "registry.connect.redhat.com/crunchydata/postgres-operator@sha256:4ad944f4f01a85249aa7678521e61fe48ed150ac43f3c38f33b42f7a32eb9961"
```
By installing the operator first ourselves, we prevent this happening as the operator will …
> [patch] Prevent UDS installing back-level Postgres

- ibm/mas_devops/common_vars/digests/ibm-mas-iot/8.6.0.yaml
Another CASE bundle packaging error that we need to work around for airgap support of IoT v8.6.0.
> [patch] Fix IoT v8.6.0 digest map

- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-spark.yml
This is another CP4D operator that reports a misleading install failure, when the reality is that the installation just takes a lot longer than the time outs built into the ae operator.  As a result we cannot monitor for failure, because during the normal course of an installation the operator will report that the install has failed when it has not.
> [patch] Ignore misleading analyticsengineStatus failed status

- ibm/mas_devops/roles/suite_app_install/tasks/install_digest_cm.yml
Visual Inspection does not use IBM Truststore Manager, so we do not need to perform steps 4, 5, and 6.
> [patch] Fix MVI airgap installation

- docs/playbooks/oneclick-iot.md
- docs/playbooks/oneclick-manage.md
- docs/playbooks/oneclick-monitor.md
- docs/playbooks/oneclick-optimizer.md
- docs/playbooks/oneclick-predict.md
- docs/playbooks/oneclick-visualinspection.md
- ibm/mas_devops/playbooks/oneclick_add_assist.yml
- ibm/mas_devops/playbooks/oneclick_add_optimizer.yml
- ibm/mas_devops/playbooks/oneclick_add_predict.yml
- ibm/mas_devops/playbooks/oneclick_add_visualinspection.yml
Multiple playbooks are set up to use MAS_ENTITLEMENT_KEY (development override) instead of the primary IBM_ENTITLEMENT_KEY environment variable.  This update corrects that.
> [patch] Fix playbook use of IBM_ENTITLEMENT_KEY

- ibm/mas_devops/plugins/filter/filters.py
Update the string2dict function to tolerate the string "None" and update the error message when an invalid parameter is passed to output "Failed to parse parameter: + string"
> [patch] Update string2dict to tolerate the string 'None'

- ibm/mas_devops/roles/cert_manager/tasks/main.yml
- ibm/mas_devops/roles/cert_manager/templates/ibm-cert-manager-common-service.yml
- ibm/mas_devops/roles/ibm_catalogs/defaults/main.yml
Fixing the task introduced in #563 that was then disabled in #573 
**The change has the same purpose as the [original PR (563)](https://github.com/ibm-mas/ansible-devops/pull/563) intended:**
With the new change to certificates in MAS that will need produce privateKey sizings of 4096 instead of 2048 we see that when installing a fresh install (new cluster, new cert-manager etc) around 5 times as long to get the suite ready due to the increased sizing. This change should provide a new Kubernetes CPU unit limit of 1000m instead of the previous of 80m ([as documented here](https://www.ibm.com/docs/en/cpfs?topic=services-configuring-foundational-by-using-custom-resource#cert_contr))
> [patch] Increase CertManagerController CPU limit

- ibm/mas_devops/roles/cert_manager/tasks/main.yml
- ibm/mas_devops/roles/cert_manager/templates/ibm-cert-manager-common-service.yml
Building on https://github.com/ibm-mas/ansible-devops/pull/605 - this change means that the sizing increase mentioned there will instead target the default certManager instance.
_See [relevant slack thread](https://ibm-watson-iot.slack.com/archives/C031Q7W21FZ/p1673955769867269)_
**Tested on active cluster as shown below:**
> [patch] Update cert-manager sizing call

- ibm/mas_devops/roles/cert_manager/templates/ibm-cert-manager-common-service.yml
This change will point the sizing increase towards the correct commonServices path - and increase the cpu and memory for both certManagerController and certManagerCAInjector.
_See [relevant slack thread](https://ibm-watson-iot.slack.com/archives/C031Q7W21FZ/p1674007082528409)_
**Tested on active cluster as shown below:**
> [patch] Further increases to cert-manager limits

- ibm/mas_devops/roles/suite_db2_setup_for_manage/README.md
- ibm/mas_devops/roles/suite_db2_setup_for_manage/defaults/main.yml
- ibm/mas_devops/roles/suite_db2_setup_for_manage/tasks/main.yml
- ibm/mas_devops/roles/suite_db2_setup_for_manage/templates/setupdb.sh.j2
This reverts commit 4045f32c944a4fa12f5ca327a95e25e845e0be8c.
We've been unable to successfully run maxinst since this update, so are reverting these changes:
> When I looked, it is complaining the maxdata tablespace is not there. I went to the db and found the tablespace indeed is not there. But when I tried to list the schema, the db is acting weird complaining resource not enough. I checked the automation, looks right, except the from the log I can't tell if it was run successfully. So I restarted the db2u pod, haven't checked back.
the setupdb.sh does show creating the schema name, and the db doesn't have this tablespace. Just manually created the bufferpool and schema.
```
BMXAA6814W - Maxinst Connection warning: com.ibm.db2.jcc.am.SqlWarning: DB2 SQL Warning: SQLCODE=0, …
```
> [patch] Revert "Refine setupdb.sh reviewed by DBA (#576)"

- ibm/mas_devops/roles/kafka/tasks/determine-storage-classes.yml
The main kafka_storage_class was correctly configured to use `default_storage_classes_rwo`, but `zookeeper_storage_class` was not.
> [patch] Fix zookeeper default storage class handling

- ibm/mas_devops/roles/cert_manager/templates/ibm-cert-manager-common-service.yml
[fvtdev is still struggling to install the new 4k certificate sizings](https://dashboard.masdev.wiotp.sl.hursley.ibm.com/tests/fvtdev/testsuite/ibm-mas-devops/suite-verify) with the following common services spec:
```
spec:
services:
- name: ibm-cert-manager-operator
spec:
certManager:
certManagerCAInjector:
resources:
limits:
cpu: 200m
memory: 1024Mi
certManagerController:
resources:
limits:
cpu: 1000m
memory: 1024Mi
size: starterset
```
This changes attempts to align the common-services spec to be the same as [this masmolecule instance ](https://console-openshift-console.masmolecule-6f1620198115433da1cac8216c06779b-0000.eu-gb.containers.appdomain.cloud/k8s/ns/ibm-common-services/operator.ibm.com~v3~CommonService/common-service/yaml)that has previously worked with the new cert sizings. …
> [patch] Further increase to cert-manager resources

- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wd.yml
When you set CPD product version to x you don't always get all the services at x .. in this case CPD v4.5.2 results in WD v4.5.1 being used.
Need to use the configmap in `ibm/mas_devops/roles/cp4d/templates/config_maps/olm-utils-cm-4.5.2.yml.j2` to determine the expected version of the service.  It appears WD is the only CPD service this logic was added to.
> [patch] Remove bad wait condition added in #466

- ibm/mas_devops/roles/db2/defaults/main.yml
- ibm/mas_devops/roles/db2/tasks/suite_jdbccfg.yml
For issue: https://github.com/ibm-mas/ansible-devops/issues/633
As MAS begins migrating to Java 11.0.16.1 an issue with older DB2 Java drivers can occur. For reference see the following:
https://github.com/ibmruntimes/Semeru-Runtimes/issues/22#issuecomment-1277051104
Until all the MAS services/containers affected can be updated with the latest DB2 driver documented here:
https://www.ibm.com/support/pages/db2-version-115-mod-8-fix-pack-0-linux-unix-and-windows
A work around of appending the following to any JDBC URL should be employed:
`sslVersion=TLSv1.2`
> [patch] Fix for Java 11.0.16.1 and older DB2 Driver support

- ibm/mas_devops/roles/suite_upgrade/tasks/upgrade.yml
OperatorCondition checking is timing out in suite_upgrade role:
Logs:
```
TASK [ibm.mas_devops.suite_upgrade : upgrade : Lookup OperatorCondition for ibm-mas] ***
Monday 30 January 2023  07:33:48 +0000 (0:00:00.040)       0:01:19.578 ******** 
FAILED - RETRYING: [localhost]: upgrade : Lookup OperatorCondition for ibm-mas (10 retries left).
FAILED - RETRYING: [localhost]: upgrade : Lookup OperatorCondition for ibm-mas (9 retries left).
FAILED - RETRYING: [localhost]: upgrade : Lookup OperatorCondition for ibm-mas (8 retries left).
FAILED - RETRYING: [localhost]: upgrade : Lookup OperatorCondition for ibm-mas (7 retries left).
FAILED - RETRYING: [localhost]: upgrade : Lookup OperatorCondition for ibm-mas (6 retries left).
FAILED - RETRYING: [localhost]: upgrade : Lookup OperatorCondition …
```
> [patch] Fix delay unit to check Operator Condition in upgrade role

- ibm/mas_devops/roles/suite_app_config/tasks/manage.yml
- ibm/mas_devops/roles/suite_manage_birt_report_config/tasks/main.yml
- ibm/mas_devops/roles/suite_manage_birt_report_config/tasks/setup-manage-birt-report.yml
- ibm/mas_devops/roles/suite_manage_doclinks_config/tasks/main.yml
- ibm/mas_devops/roles/suite_manage_doclinks_config/tasks/setup-manage-doclinks.yml
- ibm/mas_devops/roles/suite_manage_import_certs_config/tasks/main.yml
- ibm/mas_devops/roles/suite_manage_logging_config/tasks/main.yml
- ibm/mas_devops/roles/suite_manage_logging_config/tasks/setup-manage-logging.yml
- ibm/mas_devops/roles/suite_manage_pvc_config/tasks/configure-manage-pvcs.yml
- ibm/mas_devops/roles/suite_manage_pvc_config/tasks/main.yml
- ibm/mas_devops/roles/suite_switch_to_olm/tasks/ibm-common-services.yml
- ibm/mas_devops/roles/suite_switch_to_olm/tasks/main.yml
community.kubernetes has been deprecated and we need to use kubernetes.core instead.
> [patch] Replace use of community.kubernetes with kubernetes.core

- docs/playbooks/oneclick-manage.md
- ibm/mas_devops/playbooks/oneclick_add_manage.yml
- ibm/mas_devops/roles/gencfg_jdbc/defaults/main.yml
1) Updated configure_external_database env variable name to configure_external_db.
2) Added the ssl_enabled flag to gencfg_jdbc role.
> [patch] Update configure_external_db env var name

- ibm/mas_devops/roles/ocp_login/README.md
- ibm/mas_devops/roles/ocp_login/defaults/main.yml
- ibm/mas_devops/roles/ocp_login/tasks/login-roks.yml
- ibm/mas_devops/roles/ocp_provision/README.md
- ibm/mas_devops/roles/ocp_provision/defaults/main.yml
- ibm/mas_devops/roles/ocp_provision/tasks/providers/roks.yml
Support for https://test.cloud.ibm.com seems to have slipped away in the `ocp_login` and `ocp_provision` roles during a refactor at some point.
> [patch] Fix missing ibmcloud_endpoint variable

- ibm/mas_devops/roles/suite_install_digest_cm/tasks/main.yml
This update allows Manage 8.4.x versions in the Nov 22, Dec 22, and Jan 23 catalogs to be used in a disconnected install.
> [patch] New case versions as a workaround for mispelled image map name

- ibm/mas_devops/roles/db2/defaults/main.yml
- ibm/mas_devops/roles/db2/tasks/suite_jdbccfg.yml
Manage jdbccfg cr was missing a ; at the end of the url and also had an empty space at the end. 
This was causing manage selenium tasks to fail while connecting to manage db
> [patch] Fix Db2 jdbc_url generated value

- ibm/mas_devops/roles/db2/README.md
- ibm/mas_devops/roles/db2/defaults/main.yml
- ibm/mas_devops/roles/suite_db2_setup_for_manage/tasks/main.yml
This update address a number of issues with the db2u role:
`oc copy` command in `suite_db2_setup_for_manage` does not specifcy a container in the pod to copy to.
`oc copy` command in `suite_db2_setup_for_manage` has been reported to be unreliable, however when re-running the role it works; to address this a simple retry logic has been added to the role so that it will automatically retry.  This does not rule out future additional work if we can determine the cause of the unreliability.
- Reported in issue #503 
PR #479 updated the spec in `Db2uCluster` to add `spec.environment.instance.dbmConfig.INSTANCE_MEMORY`, in discussions with the Db2u team we have been advised this in an error as that setting should never be used with the operator.
- Reported in issue #604 
> The engine does not …
> [patch] Multiple Db2 role bug fixes

- ibm/mas_devops/roles/suite_install_digest_cm/tasks/main.yml
Whatever the problem is with Manage in airgap post 8.4.3 it's not an issue with the digest image map, which was fixed in the 8.4.4 release to the expected name of `ibm-mas-manage-image-map`.
> [patch] Revert #638

- ibm/mas_devops/roles/suite_install_digest_cm/tasks/main.yml
Added a new block to create a new ibm-manage-image map when the case release is manage 844 or 845.
> [patch] Add image-map workaround for manage v8.4.4-8.4.5

- ibm/mas_devops/playbooks/uninstall_core.yml
- ibm/mas_devops/roles/common_services/tasks/actions/install.yml
- ibm/mas_devops/roles/common_services/tasks/actions/uninstall.yml
- ibm/mas_devops/roles/common_services/tasks/main.yml
The uninstall task for common_services role was not working as intended. When deleting the ibm-common-services namespace the IBM NamespaceScope Operator gets deleted with it but the NamespaceScope CRs then get stuck on their finalizer ultimately blocking the deletion of the namespace.
- I have added an oc command to delete the NamespaceScope CRs before deleting the ibm-common-services namespace.
- I have also re-arranged the order of roles in the uninstall_core playbook to match the reverse of how we install core.
- Changed some pieces in common_services according to ansible lint recommendations. Should really be done for all files. But this serves as an example.
- I have tested various scenarios manually
> [patch] Fix common services uninstall

- docs/playbooks/oneclick-core.md
- ibm/mas_devops/roles/ibm_catalogs/tasks/install/development-catalog.yml
- ibm/mas_devops/roles/ibm_catalogs/templates/development-catalog.yml.j2
- ibm/mas_devops/roles/install_operator/templates/ibm-entitlement-with-artifactory.json.j2
- ibm/mas_devops/roles/ocp_simulate_disconnected_network/defaults/main.yml
- ibm/mas_devops/roles/ocp_simulate_disconnected_network/tasks/main.yml
- ibm/mas_devops/roles/suite_install/README.md
- ibm/mas_devops/roles/suite_switch_to_olm/README.md
All Docker repositories can now be accessed using a path-based mechanism.
for example the Docker URL reference:
```
wiotp-docker-local.artifactory.swg-devops.com
```
should become:
```
docker-na-public.artifactory.swg-devops.com/wiotp-docker-local
```
https://github.com/ibm-mas/ansible-devops/issues/681
> [patch] Updates to support new Artifactory hostnames

- ibm/mas_devops/playbooks/mirror_core.yml
- ibm/mas_devops/roles/mirror_case_prepare/README.md
- ibm/mas_devops/roles/mirror_case_prepare/defaults/main.yml
- ibm/mas_devops/roles/mirror_case_prepare/tasks/main.yml
Instead of downloading dependencies, and then deleting them, we will use `--skip-dependencies`.  This also avoids the issue with one of the corrupted dependencies (ibm-mas-assist) blocking mirroring today.
> [patch] More efficient ibm-pak command for MAS Core

- ibm/mas_devops/roles/sls/README.md
- Added info to set ARTIFACTORY_APIKEY and ARTIFACTORY_USERNAME which are required if you want to pull from Artifactory. If you don't set these the pull of the sls operator image from artifactory will fail.
- A little reorganization to put the similar variables together
> [patch] Add Artifactory variable info to sls role doc

- ibm/mas_devops/roles/uds/README.md
Document the fact that `install_suds` or `uninstall_suds` can be defined for the `UDS_ACTION` environment variable
> [patch] Document UDS_ACTION values for suds (un)install

- ibm/mas_devops/common_vars/casebundles/v8-230314-amd64.yml
Update the digest for the 230314 catalog image. 
https://github.com/ibm-mas/ansible-devops/issues/695
> [patch] Use correct digest for 230314 catalog image

- ibm/mas_devops/roles/mirror_case_prepare/tasks/main.yml
- ibm/mas_devops/roles/mirror_case_prepare/tasks/uds-209-fix.yml
- ibm/mas_devops/roles/mirror_case_prepare/templates/uds209fix/direct.txt.j2
- ibm/mas_devops/roles/mirror_case_prepare/templates/uds209fix/from-filesystem.txt.j2
- ibm/mas_devops/roles/mirror_case_prepare/templates/uds209fix/to-filesystem.txt.j2
Remove the entitled image that was included in the UDS 2.0.9 CASE bundle
> Airgap mirror workaround for UDS 2.0.9

- ibm/mas_devops/roles/appconnect/templates/dashboard.yml.j2
Update AppConnect dashboard deployment to enable useCommonServices by default.
CLI PR to disable appconnect in the tekton pipeline: https://github.com/ibm-mas/cli/pull/216
> [patch] Enable useCommonServices in Appconnect Dashboard by default

- ibm/mas_devops/roles/configure_manage_eventstreams/README.md
The name of the role is wrong in the documentation. Fixing it.
> [patch] Fix role name in configure_manage_eventstreams README

- ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_edge_certificate.yml
- ibm/mas_devops/roles/suite_dns/templates/dnsentries.yml.j2
- ibm/mas_devops/roles/suite_dns/templates/edge_certificate_routes.yml.j2
During patch testing we found out that Optimizer has a route that was not yet included in the cname entries for suite_dns.
it's the `api.optimizer` and `{{ mas_workspace_id }}.api.optimizer`.. so this PR fixes this problem going forward.
> [patch] Fix api.optimizer CNAME entries

- build/bin/copy-role-docs.sh
- docs/changes.md
- ibm/mas_devops/README.md
- ibm/mas_devops/playbooks/ocp_fyre_provision.yml
- ibm/mas_devops/roles/ocp_provision/README.md
- ibm/mas_devops/roles/ocp_provision/defaults/main.yml
- ibm/mas_devops/roles/ocp_provision/tasks/providers/fyre.yml
- ibm/mas_devops/roles/ocp_provision/tasks/providers/ipi.yml
- ibm/mas_devops/roles/ocp_provision/templates/fyre/product_group.json.j2
- ibm/mas_devops/roles/ocp_provision/templates/fyre/quick_burn.json.j2
- ibm/mas_devops/roles/ocp_provision/templates/ipi/install-config.yaml.j2
- ibm/mas_devops/roles/ocp_update_apiserver/README.md
- ibm/mas_devops/roles/ocp_update_apiserver/defaults/main.yml
- ibm/mas_devops/roles/ocp_update_apiserver/tasks/main.yml
- ibm/mas_devops/roles/ocp_update_apiserver/tasks/update-apiserver.yml
- mkdocs.yml
https://github.com/ibm-mas/ansible-devops/pull/749 was raised in a forked repo, and don't have any permissions in that fork to address the merge, so porting the changes into a development branch here.
When invoking Kubernetes APIs from IBM Java Semeru runtimes an error indicating no cipher suites in common can be observed. This is because currently (as of IBM Java Semeru 11.0.16.1) the JVM has a limited set of ciphers available in FIPS mode. It is suggested to simply extend the default by three ciphers to accommodate the IBM Java Semeru runtime. This can be done by create a custom tls profile.
- https://github.ibm.com/wiotp/tracker/issues/11556
Have created the cluster in fips mode on fyre and tested the Core and SLS are fine in fips mode.
> [minor] Update API Server tlsSecurityProfile to support IBM Java Semeru

- docs/playbooks/oneclick-update.md
- ibm/mas_devops/playbooks/mirror_add_assist.yml
- ibm/mas_devops/playbooks/mirror_add_hputilities.yml
- ibm/mas_devops/playbooks/mirror_add_iot.yml
- ibm/mas_devops/playbooks/mirror_add_manage.yml
- ibm/mas_devops/playbooks/mirror_add_monitor.yml
- ibm/mas_devops/playbooks/mirror_add_optimizer.yml
- ibm/mas_devops/playbooks/mirror_add_predict.yml
- ibm/mas_devops/playbooks/mirror_add_visualinspection.yml
- ibm/mas_devops/playbooks/mirror_core.yml
- ibm/mas_devops/playbooks/oneclick_add_assist.yml
- ibm/mas_devops/playbooks/oneclick_add_iot.yml
- ibm/mas_devops/playbooks/oneclick_add_manage.yml
- ibm/mas_devops/playbooks/oneclick_add_monitor.yml
- ibm/mas_devops/playbooks/oneclick_add_optimizer.yml
- ibm/mas_devops/playbooks/oneclick_add_predict.yml
- ibm/mas_devops/playbooks/oneclick_add_visualinspection.yml
- ibm/mas_devops/playbooks/oneclick_core.yml
- ibm/mas_devops/roles/ibm_catalogs/README.md
- Update all default channels in install playbooks for MAS 8.10 release
- Update default catalog choice in mirror playbooks to `v8-230328-amd64`
> [patch] Update all defaults for MAS 8.10

- docs/changes.md
- ibm/mas_devops/README.md
- ibm/mas_devops/roles/db2/README.md
- ibm/mas_devops/roles/db2/defaults/main.yml
- ibm/mas_devops/roles/db2/tasks/main.yml
- ibm/mas_devops/roles/db2/templates/db2u_namespace.yaml
- ibm/mas_devops/roles/db2/templates/db2u_operandrequest.yml.j2
- ibm/mas_devops/roles/db2/templates/db2u_subscription.yml.j2
- ibm/mas_devops/roles/kafka/README.md
- ibm/mas_devops/roles/kafka/defaults/main.yaml
- ibm/mas_devops/roles/kafka/templates/redhat/subscription.yml.j2
- Db2u operator requires manual subscription management to install with a more appropriate subscription channel.  Using `OperandRequest` will only provide the `v2.2` channel, which is not supported on OCP 4.12
- AMQ Streams Kafka was subscribing to a specific versioned channel (old), that is no longer supported on OCP 4.12.  The subscription has been switched to `stable` channel now, and the version of the Kafka instance provisioned by default has been updated to v3.2.3 (from 2.7.0)
> [minor] Support for Db2u and AMQ Streams on OCP 4.12

- ibm/mas_devops/roles/nvidia_gpu/tasks/nfd_setup.yml
Depending on the version of NFD there may also be a nfd-master DaemonSet, but because newer versions use a combined worker-master model we will only wait for the nfd-worker DaemonSet so that this will work regardless of the version of OCP/NFD that is being used.
> [patch] Remove checks for nfd-master

- ibm/mas_devops/roles/mirror_case_prepare/tasks/prepare-released.yml
Invocation of the UDS 2.0.9 fix was accidentally deleted during the recent restructure of the mirror case prepare role.
> [patch] Reinstate the airgap uds 209 fix

- ibm/mas_devops/roles/install_operator/templates/ibm-entitlement-with-artifactory.json.j2
As part of this PR: https://github.com/ibm-mas/ansible-devops/pull/764
I made a change to `install_operator` role that I should not have done and this broke the SLS install while testing the pre-release version of cli. I'm reverting the change back to what it was.
> [patch] Fix install_operator role

- ibm/mas_devops/roles/ocs/tasks/main.yml
Set the local storage operator channel to `stable` for all OCP releases. The `stable` channel can be used for all OCP releases as it is the same as the stable-{ocpversion} channel
> [patch] Set local storage operator channel to stable

- ibm/mas_devops/roles/kafka/tasks/provider/redhat/install.yml
Fixes https://github.com/ibm-mas/ansible-devops/issues/781 to make the kafka role idempotent. Now if you run the kafka role again on an existing environment then it will detect the maskafka-credentials secret in the kafka namespace, and if there is a password it will use that rather than create a new random password.
Also fixes https://github.com/ibm-mas/ansible-devops/issues/546 which now checks the cluster to see if it supports the api `integreatly.org/v1alpha1` and if it does then the grafanadashboard resources are installed.
This is the output from a rerun of the kafka role (you can see that it checked the cluster supported the `integreatly.org/v1alpha1` api, and that the kafka user was not modified) :
> [patch] check for exisitng user + supports integreatly

- ibm/mas_devops/roles/mirror_extras_prepare/vars/mongoce_4.4.21.yml
The airgap for mongo have two entries for the mongo kubernetes operator (0.7.8 and 0.7.9) however the oc mirror can only cope with one named image, so we have to set this to be the default of 0.7.9. There is no logically reason why anyone would choose 0.7.8 over 0.7.9 anyway.
> [patch] Don't duplicate mongo airgap image name

- ibm/mas_devops/roles/ocp_provision/tasks/providers/rosa.yml
Resolves https://github.com/ibm-mas/ansible-devops/issues/788
The rosa cli deprecated the use of `--compute-nodes` last year and have now removed the option completely in the lastest rosa cli version (1.2.21). The replacement is to use `--replicas` which has the same meaning/fiunction just with a different name.
> [patch] Change to use rosa cmd with --replicas

- ibm/mas_devops/roles/cluster_monitoring/tasks/install/opentelemetry.yml
As part of my refactoring to consolidate monitoring stack management into a single role I missed a re-name of the OpenTelemetry subscription template.
> [patch] Fix OT subscription template name

- ibm/mas_devops/roles/aws_documentdb_user/README.md
- ibm/mas_devops/roles/aws_documentdb_user/defaults/main.yml
- ibm/mas_devops/roles/aws_documentdb_user/tasks/main.yml
- ibm/mas_devops/roles/mongodb/README.md
- ibm/mas_devops/roles/mongodb/tasks/providers/aws/install.yml
The mongodb role has the `aws` provider which installs DocDB. The readme for this was missing variables that are required, and a variable that is required but not marked as required. The associated role `aws_documentdb_user` also had a variable marked as required but it isn't needed at all so it was removed.
I tested both these roles when deploying docDb
This resolves https://github.com/ibm-mas/ansible-devops/issues/818
> [patch] Fix docDb role readme and remove unrequired vars

- ibm/mas_devops/roles/kafka/README.md
- ibm/mas_devops/roles/kafka/defaults/main.yaml
The AMQ Streams stable operator 2.4.0 was released yesterday which brings the minimum level of kafka to above the default kafka that the ansible-devops collection tries to use. The result is that the kafka cr fails with:
```
Unsupported Kafka.spec.kafka.version: 3.2.3. Supported versions are: [3.3.1, 3.4.0]
```
This PR updates the kafka default version from 3.2.3 to 3.3.1. The release notes for 3.3.0 https://archive.apache.org/dist/kafka/3.3.0/RELEASE_NOTES.html don't indicate breaking changes.
> [patch] Update Kafka default to 3.3.1

- ibm/mas_devops/roles/gencfg_jdbc/README.md
- ibm/mas_devops/roles/gencfg_watsonstudio/README.md
- mkdocs.yml
The link for gencfg_jdbc role at https://ibm-mas.github.io/ansible-devops/ opens contents for the entitlement_key_rotation role. 
A correction was made in the mkdocs to point to the right role. The document heading was changed to reflect what the role was about to avoid confusion since two roles had suite-config as their titles
> [patch] Fix document link and titles

- ibm/mas_devops/common_tasks/get_ingress_cert.yml
- ibm/mas_devops/roles/uds/tasks/install/udscfg.yml
- ibm/mas_devops/roles/uds/templates/bascfg.yml.j2
Not really sure why we need to do this, but in testing on TechZone cluster it appears to do the trick, and this code path was completely broken before I delivered #831 anyway so low risk anyone was using this successfully the way it worked before anyway.
> [patch] Only add the first certificate in the chain to BasCfg

- ibm/mas_devops/roles/mirror_extras_prepare/vars/mongoce_4.4.21.yml
The wrong digest was added for the mongo 4.4.21 (it was copied from the 4.2.23 image digest). Without this change then the default MongoDb install on airgap can not work as the image is not mirrored.
This was missed in testing as we can't currently block quay.io https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/ocp_simulate_disconnected_network/defaults/main.yml#L3
Resolves https://github.com/ibm-mas/ansible-devops/issues/835
> [patch] Fix incorrect mongo 4.4.21 digest

- ibm/mas_devops/common_vars/digests/ibm-data-dictionary/1.1.4.yaml
- ibm/mas_devops/playbooks/mirror_add_monitor.yml
- ibm/mas_devops/roles/suite_app_install/tasks/monitor.yml
For Monitor 8.10.0, there were extra images that we needed to make it work. We had a workaround that assumed that all consecutive versions would apply but that is not the case so I added a condition to only apply this workaround for 8.10.0 only leaving the newer versions out until we need it again. This is causing a false fail in fvt810x airgap mirroring at the moment. Here is the fix. I tested and it passed for both new and old version except for 8.10.1 which had an unfixable bug.
Also added digest for DD 1.1.4. It turned out that it was not fully supported in OM 1.6
> [patch] Exclusive workaround for Monitor mirroring

- ibm/mas_devops/roles/kafka/tasks/provider/redhat/install.yml
Fix for: 
```
TASK [ibm.mas_devops.kafka : Debug information] ********************************
Saturday 03 June 2023  20:49:03 +0000 (0:00:00.029)       0:00:04.794 ********* 
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'amqstreams_defauilt_channel' is undefined\n\nThe error appears to be in '/opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/kafka/tasks/provider/redhat/install.yml': line 68, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# -----------------------------------------------------------------------------\n- name: \"Debug information\"\n  ^ here\n"}
```
> [patch] Fix amqstreams_defauilt_channel typo

- ibm/mas_devops/roles/nvidia_gpu/tasks/main.yml
A rogue ":" is appended to "status.defaultChannel" that needs to be removed
> [patch] Fix typo in nvidia_gpu role's set_fact

- ibm/mas_devops/roles/kafka/templates/redhat/subscription.yml.j2
Another mistake, we are referencing `amqstreams_manifest.status.defaultChannel` instead of `amqstreams_manifest.defaultChannel`.
> [patch] Fix amqstreams_manifest.defaultChannel typo

- ibm/mas_devops/roles/cluster_monitoring/README.md
- ibm/mas_devops/roles/cluster_monitoring/defaults/main.yml
- ibm/mas_devops/roles/cluster_monitoring/tasks/install/main.yml
- ibm/mas_devops/roles/cluster_monitoring/tasks/uninstall/main.yml
Using `cluster_monitoring_include_opentelemetry` a customer can choose to add OpenTelemetry to the monitoring stack, but by default it will be not included.
> [patch] Make opentelemetry an optional part of stack

- ibm/mas_devops/roles/ocp_simulate_disconnected_network/defaults/main.yml
`quay.io` was accidentally added to the block list in the simulated disconnected network role, we're not at the point where the sim airgap environment can block quay.io.
> [patch] Remove quay.io from sim disconnected network

- docs/playbooks/uninstall-core.md
This just adds official MAS uninstall documentation link to our automation documentation as per customer feedback:
https://github.ibm.com/wiotp/tracker/issues/12684#issuecomment-58176587
It seems there was an understanding that MAS uninstall playbook was going to take care of the uninstall without any type of debug or intervention, which ideally is what we expect, but sometimes if the MAS instance is not healthy for whatever reasons, the uninstall might not gracefully complete.
> [patch] Add link to product uninstall documentation

- ibm/mas_devops/roles/suite_dns/README.md
- ibm/mas_devops/roles/suite_dns/defaults/main.yaml
- ibm/mas_devops/roles/suite_dns/tasks/cp4d.yml
- ibm/mas_devops/roles/suite_dns/tasks/run.yml
- ibm/mas_devops/roles/suite_dns/templates/cp4d/cp4d-certificate.yml.j2
- ibm/mas_devops/roles/suite_dns/templates/cp4d/cp4d-route.yml.j2
This fixes the issue while configuring public well-known certs for CPD within the `suite_dns` role. We had many undefined references in the task that sets the CPD route, so I'm fixing that based on recent feedback.
Expected results to have public certs added to the CPD route:
> [patch] fix cpd custom route

- ibm/mas_devops/roles/mirror_extras_prepare/tasks/extras.yml
MIrror extras does not create the directories required, it assumes this has been done outside the role.  Simple update to correct this.
> [patch] Create working dir if missing

- ibm/mas_devops/roles/db2/defaults/main.yml
Previous bad merge resulted in a change to the default values for CPU & memory resource requests & limits.
> [patch] Fix db2u resource defaults

- ibm/mas_devops/roles/suite_certs/templates/dnsentries.yml.j2
- ibm/mas_devops/roles/suite_dns/tasks/providers/cloudflare/main.yml
- ibm/mas_devops/roles/suite_dns/templates/dnsentries.yml.j2
- ibm/mas_devops/roles/suite_dns/templates/edge_certificate_routes.yml.j2
Newer versions of MAS have new routes. We should add the DNS settings for them - they won't do any harm on releases that do not need them.
> [patch] Add edgeconfig.iot and edgeconfigapi.iot routes

- ibm/mas_devops/plugins/action/verify_workloads.py
Debug messages in the `ocp_verify` were actually the wrong way around:
Example:
```
[NOTREADY] ibm-odf-validation-webhook/managed-storage-validation-webhooks = 3 replicas/3 ready/3 updated/3 available
[READY]    ibm-sls/ibm-sls-controller-manager = 2 replicas/1 ready/1 updated/1 available
```
This does not affect the functionality of the verification, but is confusing.
> [patch] Fix READY / NOTREADY debug msgs

- ibm/mas_devops/roles/uds/tasks/uninstall/main.yml
UDS uninstall has been broken for a few releases ... this update restores the capability to working status.
> [patch] Fix UDS uninstall

- ibm/mas_devops/roles/suite_install/defaults/main.yml
https://github.ibm.com/wiotp/tracker/issues/12960
- Changes are here to pickup the DataDictionary channel for running fvts
> [patch] fix DD channel for fvts

- ibm/mas_devops/roles/cos/templates/ibm/objectstoragecfg.yml.j2
- ibm/mas_devops/roles/cos/templates/ocs/objectstoragecfg.yml.j2
- ibm/mas_devops/roles/uds/templates/bascfg.yml.j2
Fixes for https://github.com/ibm-mas/ansible-devops/issues/570:
- this adds root cert for let's encrypt so it works for ibm cloud hosted ocs (similar to what we have for uds)
- also removes invalid/expired leaf cert from the cos certificate chain
> [patch] Add let's encrypt root cert to ocs config yaml

- ibm/mas_devops/roles/ocp_deprovision/tasks/providers/fyre.yml
- ibm/mas_devops/roles/ocp_provision/tasks/providers/fyre.yml
Fixing issue reported by @jeancrg 
https://ibm-watson-iot.slack.com/archives/C0195MVCEUD/p1687807344114479
This changes the fyre api and the `when` condition used to check if cluster exists prior provisioning or deprovisioning the quickburn cluster.
> [patch] Fix FYRE API provision/deprovision logic

- ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
Spotted this problem introduced by one of the changes in `15.0.0-pre.master` testing:
```
TASK [ibm.mas_devops.suite_install : Create suite.ibm.com/v1 CR] ***************
Wednesday 12 July 2023  14:04:35 +0000 (0:00:00.029)       0:00:36.503 ******** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:                          ^
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1689170675.3339348-267-195451354536423/AnsiballZ_k8s.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1689170675.3339348-267-195451354536423/AnsiballZ_k8s.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, …
```
> [patch] Fix suite template

- ibm/mas_devops/roles/db2/defaults/main.yml
Detected a bad merge in the work to support db2 node labelling (#854).
> [patch] Remove dbmConfig.INSTANCE_MEMORY

- ibm/mas_devops/roles/db2/defaults/main.yml
The default for `db2_instance_dbm_config` was left pointing at `db2_default_config.dbmConfig`, which has been removed as part of the previous fix.
> [patch] More dbm_config cleanup

- ibm/mas_devops/roles/kubeturbo/templates/turbonomic-secret.yml.j2
Update turbonomic update key name - to username and password
Ref: https://github.com/turbonomic/kubeturbo/wiki/OpenShift-Operator-Hub-Details#credentials-via-k8s-secret
CC: @pseemung
> [patch] Fix Turbonomic secret field names

- ibm/mas_devops/roles/suite_uninstall/tasks/main.yml
Not 100% clear why, but sometimes the child Truststores don't get automatically removed when their parent is deleted.
> [patch] Fix uninstall

- ibm/mas_devops/roles/suite_dns/tasks/providers/cis/main.yml
Based on feedback, i'm reverting the fix that was initially intended to check if provided CIS CRN in fact corresponds to a valid CIS instance in the logged IBM Cloud account here: https://github.com/ibm-mas/ansible-devops/pull/870
It seems like the used cis command can return unexpected output depending on the name of the cis instance being looked up and on top of that it uses `ibmcloud cis` plugin which is not installed as part of the cli (and wont be installed most of the times by customers) so it just creates more downsides than benefits.
> [patch] Revert cis_crn validation

- ibm/mas_devops/roles/db2/tasks/upgrade/main.yml
Changes to the Db2 role update action such that it checks if the namespace exists.  And when the namespace does not exist, it reports success and skips doing the update.  
Tested code these changes both when the namespace does not exist and when it exists.
> [patch] Update Db2 role when namespace does not exist

- ibm/mas_devops/roles/suite_db2_setup_for_manage/templates/setupdb.sh.j2
This update removes the explicit heapsize setting added in #942, because it will cause problems when used with resource limits less than 16Gb.
> [patch] Remove db2 heapsize setting

- ibm/mas_devops/roles/cluster_monitoring/defaults/main.yml
- ibm/mas_devops/roles/cluster_monitoring/tasks/install/main.yml
- ibm/mas_devops/roles/cluster_monitoring/tasks/uninstall/main.yml
- ibm/mas_devops/roles/mirror_ocp/README.md
- ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
We continue to face issues where customers are unable to mirror OCI images due to lack of support on the base OCP product.  Until this is addressed all we can really do is work around the issue by making Grafana an optional part of the cluster monitoring stack that we set up :(
Ref:
- https://access.redhat.com/solutions/6997884
- https://issues.redhat.com/browse/CFE-780
> [minor] Support cluster monitoring config without grafana

- ibm/mas_devops/roles/suite_app_install/vars/iot.yml
`EdgeConfig` component takes a long time to be ready. It has been experienced twice in a Fyre cluster. Refer to slack thread: https://ibm-watson-iot.slack.com/archives/C031Q7W21FZ/p1693519332957449?thread_ts=1692690544.888749&cid=C031Q7W21FZ
> [patch] Increase IoT install retries because of EdgeConfig

- ibm/mas_devops/roles/mongodb/README.md
- ibm/mas_devops/roles/mongodb/defaults/main.yml
- ibm/mas_devops/roles/mongodb/tasks/providers/community/install.yml
Remove MongoDB community dependency on the ibm catalog version.  Instead dynamically lookup the installed catalog version or fallback to the default MongoDB version.
> [patch] MongoDB version fix

- ibm/mas_devops/roles/kafka/README.md
- ibm/mas_devops/roles/kafka/defaults/main.yaml
Update default kafka in amq-streams to 3.5.1. 
Redhat amq-streams v2.5 was released recently which supports kafka 3.4.x or greater. so we ll use the laetst 3.5.x  - kafka 3.5.1.
https://archive.apache.org/dist/kafka/3.5.1/RELEASE_NOTES.html
https://access.redhat.com/documentation/en-us/red_hat_amq_streams/2.5/html/release_notes_for_amq_streams_2.5_on_openshift/enhancements-str
> [minor] set kafka default to 3.5.1 to support amq-streams 2.5.0

- ibm/mas_devops/playbooks/oneclick_core.yml
In `oneclick_core.yaml` we assert whether we have both `SLS_LICENSE_ID` and `SLS_LICENSE_FILE` but this is only required for SLS up to 3.6.0. From SLS 3.7.0 we will only need `SLS_ENTITLEMENT_FILE`. Hence, I made the assertion check for either (`SLS_LICENSE_ID` and `SLS_LICENSE_FILE`) or (`SLS_ENTITLEMENT_FILE`). The rest of the conditions are handled by the SLS role itself. 
- https://github.com/ibm-mas/ansible-devops/issues/962
> [patch] Fix SLS pre-condition in one_click_core

- ibm/mas_devops/roles/kafka/README.md
- ibm/mas_devops/roles/kafka/defaults/main.yaml
Update default kafka in amq-streams to 3.5.0.
Redhat amq-streams v2.5  supports kafka 3.4.0 or 3.5.0 only. it doesn't support 3.5.1
https://archive.apache.org/dist/kafka/3.5.0/RELEASE_NOTES.html
> [patch] fix default amq streams kafka version to 3.5.0

- ibm/mas_devops/roles/ocs/tasks/upgrade/main.yml
Sometimes the StorageCluster spec version is not available so use status version to determine if the StorageCluster needs an upgrade.
> [patch] Check StorageCluster Version using Status for ocs upgrade

- ibm/mas_devops/roles/cluster_monitoring/README.md
- ibm/mas_devops/roles/cluster_monitoring/defaults/main.yml
the Prometheus PVC's consume almost 1.2 TB of storage on the cluster. this is a lot of unused storage that affects the cluster performance. 
reducing the default storage limits to 20Gi, 20 X 4 = 80Gi should be sufficient, this has a successful fvt run .
Slack discussions:
https://ibm-watson-iot.slack.com/archives/CNDB5GZ3P/p1694118152787259
> [patch] Reduce default prometheus cluster_monitoring storage consumption

- ibm/mas_devops/common_vars/compatibility_matrix.yml
Adding 8.11.x to compatibility matrix.
Fix for https://github.com/ibm-mas/ansible-devops/issues/1028
> [patch] add 8.11.x to compatibility matrix

- ibm/mas_devops/roles/entitlement_key_rotation/tasks/rotate-ibm-entitlement.yml
- ibm/mas_devops/roles/entitlement_key_rotation/tasks/rotate-wiotp-docker-local.yml
- ibm/mas_devops/roles/install_operator/tasks/main.yml
- ibm/mas_devops/roles/install_operator/templates/ibm-entitlement-with-artifactory.json.j2
- ibm/mas_devops/roles/sls/README.md
- ibm/mas_devops/roles/sls/tasks/install/main.yml
SLS 3.8.0 does no longer need the ibm-entitlement pull secret because api-licensing has moved to `icr.io/cpopen`.
-  Updated README
- Deprecated `ibm_entitlement_key`, `sls_entitlement_username`, and `sls_entitlement_key` in SLS `3.8.0`
- Moved deprecated items towards bottom so that currently active ones are at the top
- minor cleanup
- Added new fact `before_sls_380`
- Ensured `sls_entitlement_key` is only needed for SLS 3.7.0 and below
- Removed `Create SLS Namespace` task because it gets created in the `install_operator` role anyway
- Ensured `icr_username` and `icr_password` are only passed on to `install_operator` role when SLS 3.7.0 or lower is deployed
- `ibm-entitlement-with-artifactory.json.j2`
- Re-structured so that it is more friendly to the eye
- Added if conditions to make …
> [minor] improve sls and install_operator role

- ibm/mas_devops/roles/kafka/tasks/main.yaml
- ibm/mas_devops/roles/ocs/tasks/upgrade/main.yml
while testing mas update cli I found these 2 code changes to be necessary.  
There's an update for kafka provider path and an update to ocs.
> [patch] Fix support for kafka/ocs in mas update  

- ibm/mas_devops/roles/mirror_case_prepare/tasks/prepare-released.yml
We can't use `manifest_version` inside `set_fact` in `mirror_case_prepare` otherwise it will conflict with use of the variable as an input to multiple calls to the `mirror_images` role in the `mirror_dependencies` playbook.
> [patch] Avoid manifest_version conflict

- README.md
Following their revamp, all the old links were dead ends.
> [patch] Update links to Ansible Galaxy

- ibm/mas_devops/playbooks/mirror_add_monitor.yml
- ibm/mas_devops/roles/mongodb/tasks/providers/community/install.yml
Add better error handling for the scenario where the ibm-operator-catalog does not include the build tag in the displayName. In this case default to the latest choice.
> [patch] Improve Mongodb catalog error handling

- ibm/mas_devops/roles/ocp_contentsourcepolicy/templates/imagecontentsourcepolicy.yml.j2
Newer release of Maximo IoT replaced the internal MessageSight MQTT message broker with [Eclipse Amlen](https://github.com/eclipse/amlen), however the ICSP has not been updated to configure mirroring for Amlen in quay.io, which means IoT can not be installed in a disconnected environment using our ICSP without the user adding further policies.
> [patch] Add Amlen entry to MAS ICSP

- ibm/mas_devops/roles/kafka/tasks/main.yaml
Recently the kafka role main task was updated from 
```include_tasks: tasks/provider/{{ kafka_provider }}/{{ kafka_action }}.yml```
to
```include_tasks: ../roles/kafka/tasks/provider/{{ kafka_provider }}/{{ kafka_action }}.yml```
This update worked for running "mas update" however it broke the performance teams scripts, they apparently have their own playbooks.
Therefore I am updating the code to be
```include_tasks: "{{ role_path }}/tasks/provider/{{ kafka_provider }}/{{ kafka_action }}.yml"```
> [patch] Update kafka role path

- ibm/mas_devops/common_tasks/get_ingress_cert.yml
During a customer call we found out that if the proxy/cluster resource has 
```yaml
spec: {}
```
rather than
```yaml
spec:
trustedCA:
name: ''
```
Then the "Check private root CA" task would fail.
I have changed it so that when `spec` is empty or `spec.trustedCA.name` is empty it still works as intended. 
Also no shell commands are used.
In my fyre cluster I did:
- Set `spec: {}` in proxy/cluster - task runs `get_signed_ingress_cert.yml` as intended
- Set `spec.trustedCA.name: ''` - task runs `get_signed_ingress_cert.yml `as intended
- Set `spec.trustedCA.name: 'admin-kubeconfig-client-ca'` gets `ca-bundle.crt` and sets `cluster_ingress_tls_crt` as intended
- Set `spec.trustedCA.name: 'openshift-service-ca.crt'` - `ca-bundle.crt` not defined and assertion fails as intended
> [patch] Fix private CA name when spec is empty

- ibm/mas_devops/common_vars/casebundles/v8-231004-amd64.yml
Existing customers on MAS 8.9.x airgap couldn't get their digest maps updated for Core and Manage. This is because the 8.9.x channel was removed from the `v8-231004-amd64` casebundle vars.
[update-digest-maps.yml](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/ibm_catalogs/tasks/install/update-digest-maps.yml) looks for this channel in the casebundle vars, so adding it back.
> [patch] add 8.9.x channel to all apps  in 231004 case vars

- build/bin/copy-role-docs.sh
- mkdocs.yml
The DRO PR https://github.com/ibm-mas/ansible-devops/pull/1049 was missing the copyDoc entry to copy over the role docs. This PR also adds some missing roles form the navigation (suite_certs, ibm_catalogs and common-services)
> [patch] Fix DRO role in docs + add missing docs

- .gitignore
- ibm/mas_devops/roles/ocp_provision/README.md
- ibm/mas_devops/roles/ocp_provision/defaults/main.yml
- ibm/mas_devops/roles/ocp_provision/tasks/providers/mcsp.yml
- ibm/mas_devops/roles/ocp_provision/templates/mcsp/cloudrockcluster.yaml.j2
https://jsw.ibm.com/browse/MASCORE-484
Logs in to MCSP Control Plane OCP, verifies required cluster resources are present (Secrets, SOS VPC), creates a `CloudRockerCluster` CR and blocks until is reconciled successfully.
NOTE: this is an initial delivery for development use. Will be expanded in future to e.g.:
- support authentication with MCSP control plane via a functional ID (at present a manually-generated token must be supplied).
- allow control of additional cluster configuration parameters.
> [patch] Add MCSP provider to ocp_provision role

- ibm/mas_devops/roles/suite_upgrade/tasks/check_app_compatibility.yml
Example: When upgrading from MAS 8.10 to 8.11 with HPU installed:
Before:
```
TASK [ibm.mas_devops.suite_upgrade : hputilities : Check that upgrade is supported from current channel] ***
fatal: [localhost]: FAILED! => 
msg: |-
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'hputilities'
The error appears to be in '/opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/suite_upgrade/tasks/check_app_compatibility.yml': line 20, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: "{{ check_app.id }} : Check that upgrade is supported from current channel"
^ here
We could be wrong, but this one looks like it might be an issue with
missing …
```
> [patch] Validate that the application itself is supported in the new release

- ibm/mas_devops/common_vars/application_info.yml
Visual Inspection's `kind` should be `VisualInspectionApp`, not `VisualInspection`
```
TASK [ibm.mas_devops.suite_upgrade : visualinspection : Check that the CR exists] ***
assertion: app_info.resources | length == 1
evaluated_to: false
msg: Upgrade failed, ibm-mas-visualinspection operator has been deployed, but fvtupgrade/VisualInspection.apps.mas.ibm.com/v1 has not been created in namespace mas-fvtupgrade-visualinspection
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
localhost                  : ok=123  changed=0    unreachable=0    failed=1    skipped=25   rescued=0    ignored=0   
```
```
oc -n …
```
> [patch] Fix visualinspection kind

- ibm/mas_devops/roles/suite_upgrade/tasks/main.yml
Follow up to https://github.com/ibm-mas/ansible-devops/pull/1078, found another place in the code where the `kind` value is incorrect.
> [patch] Fix MVI kind in a second file

- ibm/mas_devops/roles/dro/tasks/uninstall/main.yml
[MASCORE-711](https://jsw.ibm.com/browse/MASCORE-711) : Delete redhat-marketplace-pull-secret as part of DRO uninstall
The [redhat-marketplace-pull-secret](https://console-openshift-console.apps.plgtest1.cp.fyre.ibm.com/k8s/ns/redhat-marketplace/secrets/redhat-marketplace-pull-secret) is not being deleted as part of dro uninstall role. So when a user adds a wrong key the first time. there is no way to change it .
delete [redhat-marketplace-pull-secret](https://console-openshift-console.apps.plgtest1.cp.fyre.ibm.com/k8s/ns/redhat-marketplace/secrets/redhat-marketplace-pull-secret) as part of uninstall.
> [patch] Delete redhat-marketplace secret during DRO during uninstall

- ibm/mas_devops/common_vars/application_info.yml
Inspection's workspace kind is not the expected `VisualInspectionWorkspace`, but rather `VisualInspectionAppWorkspace`.
> [patch] Inspection workspace kind fix

- ibm/mas_devops/roles/suite_app_upgrade/tasks/check_app_compatibility.yml
```
TASK [ibm.mas_devops.suite_app_upgrade : visualinspection : Check that the Application CR is in a healthy state] ***
assertion: app_cr_lookup.resources | json_query('[*].status.conditions[?type==`Ready`][].reason') | select ('match','Ready') | list | length == 1
evaluated_to: false
msg: Upgrade failed because fvtupgrade/VisualInspectionApp.apps.mas.ibm.com/v1 is not healthy
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
localhost                  : ok=23   changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
```
However, when checking the cluster shortly after we can see that the application is …
> [patch] Fix Inspection upgrade failure

- ibm/mas_devops/common_vars/casebundles/v8-230725-amd64.yml
- ibm/mas_devops/common_vars/casebundles/v8-230829-amd64.yml
- ibm/mas_devops/common_vars/casebundles/v8-230926-amd64.yml
- ibm/mas_devops/common_vars/casebundles/v8-231004-amd64.yml
- ibm/mas_devops/common_vars/casebundles/v8-231031-amd64.yml
- ibm/mas_devops/playbooks/mirror_add_iot.yml
- ibm/mas_devops/roles/mirror_extras_prepare/vars/amlen_1.0.1.yml
After improving our airgap testing environments to block quay.io we disovered that we have a gap in the image mirroring for IoT; the Amlen operator image and bundle image are not being mirrored along with the rest of the IoT content.  This update remedies that by introducing a new amlen extras configuration.
This configuration has been applied to all catalogs since the July 25th catalog update.  Catalog versions before July are already unsupported due to end of life for OCP 4.10 in September.
> [patch] Fix missing mirroring for Amlen operator image

- ibm/mas_devops/roles/dro/tasks/install-dro/main.yml
The change from `install` to `install-dro` left behind a reference to `install`.
> [patch] Fix path to determine-storage-classes

- ibm/mas_devops/roles/mongodb/README.md
Adding a bit more context around the support of MongoDB 5 and 6. Specifically call out the following:
- MongoDB 4.4 will reach end of life soon
- Always take backups before any upgrade
- Specifically which versions of MongoDB 5 and 6 the automation can configure
- If MongoDB hosted by third party or on prem consult applicable documentation
> [patch] mongodb doc updates for v5 and v6

- ibm/mas_devops/common_tasks/pod_templates/get_pod_templates.yml
- ibm/mas_devops/common_tasks/pod_templates/main.yml
- ibm/mas_devops/roles/dro/tasks/install-dro/main.yml
- ibm/mas_devops/roles/dro/templates/bascfg.yml.j2
- ibm/mas_devops/roles/sls/tasks/gencfg/main.yml
- ibm/mas_devops/roles/sls/tasks/install/main.yml
- ibm/mas_devops/roles/sls/templates/licenseservice.yml.j2
- ibm/mas_devops/roles/sls/templates/slscfg.yml.j2
- ibm/mas_devops/roles/smtp/tasks/main.yml
- ibm/mas_devops/roles/smtp/templates/sendgrid/smtpcfg.yml.j2
- ibm/mas_devops/roles/suite_install/README.md
- ibm/mas_devops/roles/suite_install/tasks/main.yml
- ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
- ibm/mas_devops/roles/uds/tasks/install/main.yml
- ibm/mas_devops/roles/uds/tasks/install_suds/main.yml
- ibm/mas_devops/roles/uds/templates/bascfg-suds.yml.j2
- ibm/mas_devops/roles/uds/templates/bascfg.yml.j2
- Refactored podTemplates code into a common one under common_tasks
- We can now merge multiple podTemplates into one (used for Suite CR e.g. suite and coreidp) by passing in `vars -> combine_into`
- Auto generates the fact e.g., `ibm-mas-suite.yml` -> `ibm_mas_suite_pod_templates`
- Added support for `ibm-data-dictionary-assetdatadictionary.yml` podTemplates
- Updated suite_install README
- Tested in fyre cluster
> [minor] Add ADD podTemplates support

- ibm/mas_devops/common_vars/casebundles/v8-231031-amd64.yml
https://github.com/ibm-mas/cli/issues/644
UDS 2.0.11 was mirrored though 2.0.12 was available in 231031 catalog. 
This change should allow mirror-images role to pick up 2.0.12 for 231031 catalog.
> [patch] update uds_version to 2.0.12 for airgap mirroring

- ibm/mas_devops/roles/mirror_ocp/tasks/actions/to-filesystem.yml
- ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
- ibm/mas_devops/roles/nvidia_gpu/README.md
- ibm/mas_devops/roles/ocp_contentsourcepolicy/templates/redhat-catalogs.yml.j2
- Expands the scope of content included in the `ImageSetConfiguration`
- Adds new entries to the MAS Red Hat Catalog `ImageContentSourcePolicy`
- Corrects the default channel in Nvidia role documentation
> [patch] Fixes and tweaks for better Red Hat content mirroring

- ibm/mas_devops/common_vars/casebundles/v8-231128-amd64.yml
- ibm/mas_devops/roles/mirror_extras_prepare/vars/amlen_1.0.2.yml
https://github.ibm.com/maximoappsuite/ibm-maximo-operator-catalog/pull/327
Update Nov catalog digest and it now contains Amlen 1.0.2
> [patch] update nov catalog digest and amlen 1.0.2 extras

- ibm/mas_devops/common_tasks/pod_templates/main.yml
- ibm/mas_devops/roles/suite_dns/tasks/providers/route53/create-cnames.yml
- ibm/mas_devops/roles/suite_dns/templates/route53/create-cnames.json.j2
- Fix for #[547](https://github.com/ibm-mas/cli/issues/547) and #[548](https://github.com/ibm-mas/cli/issues/548)
We are simply adding the cluster's ingress as "A" type entry on the record list for the hosted zone in order to resolve the certificate requests coming from the target cluster.
> [patch] Adding cluster's ingress in DNS record list for Route53 hosted zone

- ibm/mas_devops/common_tasks/get_signed_ingress_cert.yml
We are not checking whether `cluster_ingress_tls_crt_remove_it` is defined before using the variable.
- Fix for #1130
> [patch] Ensure cluster_ingress_tls_crt_remove_it is defined

- ibm/mas_devops/roles/db2/README.md
- ibm/mas_devops/roles/db2/tasks/install/main.yml
- ibm/mas_devops/roles/db2/tasks/upgrade/run-db2-instances-upgrade.yml
Starting with db2u v`s11.5.8.0-cn3`, the 's' prefix is removed in db2u-license-keys causing installation issues , we were recommended to use `db2u-release` configmap instead of `db2u-license-keys` secret.
This change is in preparation for November curated content from IBM operator catalog. and also backward compatible.
> [patch] get db2u version from db2u-release configmap instead of secret

- ibm/mas_devops/playbooks/ocp_fyre_provision.yml
This is primarily used in airgap testing, we don't want to install the cluster storage before we switch to the mirror catalog source.
> [patch] Allow FYRE provision without storage configuration

- ibm/mas_devops/roles/dro/tasks/main.yml
DRO install failing with the asseert as `install` is passed from the uds_action. https://github.com/ibm-mas/cli/blob/master/tekton/src/tasks/dependencies/uds.yml.j2#L118
TASK [ibm.mas_devops.dro : Assert DRO_ACTION values] ***************************
assertion: dro_action in ["install-dro", "uninstall"]
evaluated_to: false
msg: Incorrect value set for DRO_ACTION
> [patch] add install in the DRO_ACTION list

- build/bin/initbuild.sh
This update allows the build system to build a branch when there's no patch/minor/major commit ... we will assume that the update is a patch update by default.
>  Default to patch version bump when no commit prefix provided

- ibm/mas_devops/common_tasks/detect_cert_manager.yml
- ibm/mas_devops/roles/suite_dns/tasks/run.yml
- ibm/mas_devops/roles/suite_install/tasks/main.yml
The condition to run `detect_cert_manager` task in `suite_install` had a bug... we should use `cert_manager_cluster_resource_namespace` in that condition as this is the var that must be set in order to set it properly in Suite CR, but we were using `cert_manager_namespace` var instead which is not used at all in that role.
`detect_cert_manager` task is supposed to detect if and which namespace cert-manager is installed and also set `cert_manager_cluster_resource_namespace` if not yet defined.
> [patch] Fix condition that sets cert_manager_cluster_resource_namespace

- ibm/mas_devops/roles/mirror_ocp/tasks/main.yml
Removes sensitive information (docker registry authentication information) from the `mirror_ocp` role logs.
> [patch] Disable logging of docker credentials from mirror_ocp role

- ibm/mas_devops/roles/sls/README.md
- ibm/mas_devops/roles/sls/defaults/main.yml
- ibm/mas_devops/roles/sls/templates/slscfg.yml.j2
Make the licensing sync cronjob sync frequency configable in slscfg.
The default value is  30 min `'*/30 * * * *'`
> [patch] add licensing sync cronjob sync frequency in slscfg

- ibm/mas_devops/roles/suite_install/README.md
- ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
The default ipFamilyPolicy and ipFamilies are now changed to SingleStack and IPv6 to better test IPv6-only configurations.
> [patch] change to use SingleStack and IPv6 only when ipv6_test is true

- ibm/mas_devops/roles/cert_manager/tasks/prereqs-migration.yml
- ibm/mas_devops/roles/cert_manager/tasks/provider/redhat/install.yml
1. Added a fix for Red Hat certificate manager install where we were trying to disable the operand request from `ibm-common-services` namespace but there might be cases where the `ibm-common-services` namespace will not be present yet and cert-manager role will fail at this point. So the fix will ensure that the ODLM is installed first prior trying to disable the OperandRequest by adding the ibm-cpp-config config map.
2. Changed the order of how IBM cert-manager resources are deleted during the red hat migration because deleting operand request will cause certmanager custom resource to also be deleted, and in some cases both might end up being stuck in terminating status due certmanager cr taking too long to be gone. So deleting certmanager custom resource first might simplify the …
> [patch] Check ODLM is installed prior disabling certmanager operand request

- ibm/mas_devops/roles/suite_install/tasks/main.yml
Minor fix on the condition that checks if `cert_manager_cluster_resource_namespace` is empty, this property must be defined.
Then it will run `detect_cert_manager` task that is supposed to detect if and which namespace cert-manager is installed and also set `cert_manager_cluster_resource_namespace` if not yet defined.
> [patch] Fix condition that sets cert_manager_cluster_resource_namespace (part 2)

- ibm/mas_devops/roles/mongodb/defaults/main.yml
- ibm/mas_devops/roles/mongodb/tasks/providers/community/check-mongo-exists.yml
- ibm/mas_devops/roles/mongodb/tasks/providers/community/install-mongo.yml
- ibm/mas_devops/roles/mongodb/tasks/providers/community/validate-upgrade.yml
This PR tries to simplify the logic that defines and validates the correct and matching versions to be upgraded for MongoDB.
Since now we can upgrade within patch versions (and not only minor versions) the existing code has some gaps that hopefully will be addressed with this change. An issue identified was that we expect that if mongo is version 5.0, the target can only be v6: and does not consider that you could go from 5.0.21 to 5.0.23:
```
fatal: [localhost]: FAILED! => changed=false assertion: target_mongodb_version == mongo_compatible_target_version evaluated_to: false msg: - You have an existing Mongo database instance that is running on version 5.0.21, which cannot be directly upgraded to version 5.0.23. - In order to upgrade your current instance to 5.0.23, you must first upgrade …
```
> [patch] Fix mongo compatibility matrix logic and validations

- ibm/mas_devops/playbooks/ocp_convert_to_disconnected.yml
- ibm/mas_devops/roles/ocp_contentsourcepolicy/tasks/trust.yml
- ibm/mas_devops/roles/ocp_contentsourcepolicy/tasks/update-pull-secret-dev.yml
- ibm/mas_devops/roles/ocp_contentsourcepolicy/tasks/update-pull-secret.yml
This update adds a new playbook that can be used to easily convert an online OCP install to an offline install.
> [minor] Add playbook to convert OCP to a disconnected install

- ibm/mas_devops/roles/mirror_extras_prepare/tasks/catalog.yml
- ibm/mas_devops/roles/mirror_images/tasks/main.yml
Per the title .. adds `no_log: true` to a couple of tasks that otherwise expose sensitive information in the logs.
> [patch] Hide sensitive info in debug logs when mirroring images

- ibm/mas_devops/roles/cos/templates/ibm/objectstoragecfg.yml.j2
- ibm/mas_devops/roles/cos/templates/ocs/objectstoragecfg.yml.j2
The ObjectStorageConfig being created in the `cos` role should have the `type` set in the spec. This was failing the FVT tests when an existing config was attempted to be reapplied, as the check for the `type` failed. Tested again in https://dashboard.masdev.wiotp.sl.hursley.ibm.com/tests/pfvtajw1304 and this fixes the internalapi tests.
> [patch] ObjectStorage config should have type

- ibm/mas_devops/roles/configure_manage_eventstreams/tasks/main.yml
- ibm/mas_devops/roles/cos/templates/ibm/objectstoragecfg.yml.j2
- ibm/mas_devops/roles/kafka/templates/redhat/kafkacfg.yml.j2
Some of the cert aliases being set don't conform to the expect value that the MAS API expects. This means it won't be possible to apply (or re-apply) a configured config via the MAS API. For example the kafka role creates the config with an alias of `maskafka-ca`, this is then picked up by the operator with no issue. However if you try to apply this same config via the MAS API (using the values as the payload rather than creating the kube resource) then you get the error:
```
message: 'AIUCO1000E: The request was not valid. Review the constraint violations
provided [1 violations]'
uuid: fb0a723e-b90f-494f-b722-395e166b647c
violations:
- exception:
id: AIUCO2008E
properties:
- - - '''maskafka-ca'' does not match ''^[.&a-zA-Z0-9]{2,32}$'''
message: 'AIUCO2008E: Invalid input violation: …
```
> [patch] Set cert aliases to conform to api

- ibm/mas_devops/roles/mongodb/tasks/providers/community/validate-upgrade.yml
`mongodb_v5_upgrade` and `mongodb_v6_upgrade` parameters only need to be set to confirm major version upgrades, but currently they are required for any version change.
> [patch] Mongo update does not require upgrade confirmation flag

- ibm/mas_devops/roles/dro/tasks/install-dro/main.yml
fix fvt failures. 
slack discussions on this issue
https://ibm-watson-iot.slack.com/archives/C031Q7W21FZ/p1706014726848299
- wait for marketplaceConfig to be ready before  applying the CR
Manual testing passed.
> [patch] wait for marketplaceConfig to be ready before applying the CR

- ibm/mas_devops/roles/mongodb/defaults/main.yml
Currently `4.2.23` is only support 4.2.x version we can update from, but very early MAS installs may still be on `4.2.6` so we need to be able to provide an update path for those too.
> [patch] Support update from Mongo v4.2.6

- ibm/mas_devops/roles/mongodb/tasks/providers/community/check-mongo-exists.yml
- ibm/mas_devops/roles/mongodb/tasks/providers/community/install.yml
When updating a Mongo instance, the current process does not take into account the scenario where the storage capacity is different from the default value of `20Gi`.
This also fixes an issue with the Mongo version detection regex.
- #1157
> [patch] Handle custom storage capacities in Mongo update

- ibm/mas_devops/common_vars/casebundles/v8-240130-amd64.yml
Manifest vars for Jan catalog contain the incorrect versions of ibm-mas-manage, this update corrects them:
- 8.10.x: 8.6.9
- 8.11.x: 8.7.4
> [patch] Correct Manage versions

- .gitignore
- ibm/mas_devops/common_tasks/detect_cert_manager.yml
This addresses a timing issue where `cert-manager-cainjector` was showing twice in the shell cmd that searches for it.
With the fix we just care about knowing whether cert-manager is running in multiple and different namespaces as we know there would be just one instance running in each namespace.
> [patch] Fix duplicate namespaces in detect certmanager task

- docs/playbooks/oneclick-core.md
This slight enhancement is meant to add steps for enabling login with self-certificates. 
This approach is similar as in the one documented at IBM Docs 
The enhancement added is the same as documented in IBM Docs https://www.ibm.com/docs/en/mas-cd/continuous-delivery?topic=configuring-setting-up-maximo-application-suite but if might be useful to hold that same information in the ansible-devops docs to avoid going back and forth between several links.
> [patch] Documentation enhancement for OneClick Installer (#1186)

- ibm/mas_devops/roles/cert_manager/defaults/main.yml
This PR changes Red Hat Certificate Manager as default provider for certificate management in MAS across ansible-devops. IBM certificate manager will be migrated automatically once Red Hat version is installed.
> [patch] Set Red Hat Certificate Manager by default

- ibm/mas_devops/common_tasks/get_signed_ingress_cert.yml
Added a 4th option to lookup for the default cluster's ingress secret based on the Cluster Ingress Controller configuration.
This has been useful to address a [customer case](https://ibmsf.lightning.force.com/lightning/r/Case/5003p00002rIG8aAAG/view) that was having issues with a self managed AWS cluster in `ocp_verify` where the ingress certificate was not being found, but the IngressController configuration contained the default ingress certificate secret information.
Also improved the debugging for troubleshooting purposes. If none of the 4th attempts finds the TLS secret, we will assert that before erroring with a `cluster_ingress_tls_crt undefined`
```
TASK [ibm.mas_devops.ocp_verify : Record that we have found the router-certs-default cert secret] …
```
> [patch] Lookup cluster ingress certificate secret based on IngressController

- ibm/mas_devops/roles/mongodb/tasks/providers/community/install-mongo.yml
Fix for `MongoDB update to 5.0.23 leaves Mongo replica set in unknown state` : https://github.com/ibm-mas/ansible-devops/issues/1168
With this change, if we are running a Mongo upgrade, we delete the existing statefulsets to force Mongo operator to properly recreate it with right version/image digests.
Tested the upgrade scenario from Mongo 5.0.21 > 5.0.23 > 6.0.10 > 6.0.12 - all good
> [patch] Fix for mongo patch upgrades not reconciling properly

- ibm/mas_devops/roles/dro/tasks/main.yml
Fix for this problem introduced in #1203:
```
TASK [ibm.mas_devops.dro : UDS to DRO migration (mas update scenario)] *********
skipping: [localhost] => changed=false 
false_condition: dro_migration != "" and dro_migration == "true"
skip_reason: Conditional result was False
TASK [ibm.mas_devops.dro : gencfg for new installation] ************************
fatal: [localhost]: FAILED! => 
msg: |-
The conditional check 'dro_action not in [uninstall, install]' failed. The error was: error while evaluating conditional (dro_action not in [uninstall, install]): 'uninstall' is undefined. 'uninstall' is undefined
The error appears to be in '/opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/dro/tasks/main.yml': line 34, column 3, but may
be elsewhere in the file …
```
> [patch] Fix syntax error in DRO install

- ibm/mas_devops/roles/mirror_ocp/README.md
- ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
Attempting to install MAS in a disconnected environment when using the offline Red Hat catalogs generated by the `mirror_ocp` role will fail due to a missing package: `openshift-cert-manager-operator`.
```
status:
conditions:
- message: 'constraints not satisfiable: no operators found from catalog redhat-operators
in namespace openshift-marketplace referenced by subscription openshift-cert-manager-operator,
subscription openshift-cert-manager-operator exists'
reason: ConstraintsNotSatisfiable
status: "True"
type: ResolutionFailed
- lastTransitionTime: "2024-02-18T11:24:53Z"
message: targeted catalogsource openshift-marketplace/redhat-operators missing
reason: UnhealthyCatalogSourceFound
status: "True"
type: CatalogSourcesUnhealthy
lastUpdated: "2024-02-18T11:24:53Z"
```
This update adds …
> [patch] Add openshift-cert-manager-operator to ISC

- ibm/mas_devops/roles/configure_manage_eventstreams/tasks/retrieve-es-certs.yml
- ibm/mas_devops/roles/kafka/tasks/provider/ibm/retrieve-eventstreams-certs.yml
- ibm/mas_devops/roles/suite_manage_customer_files_config/tasks/retrieve-cos-certs.yml
- ibm/mas_devops/roles/suite_manage_doclinks_config/tasks/retrieve-cos-certs.yml
- ibm/mas_devops/roles/suite_manage_logging_config/tasks/retrieve-cos-certs.yml
Looks like IBM Cloud has finally removed the broken intermediate cert from Let's Encrypt chain... the assertion is failing because it always expected 3 pieces in the cert chain but now it only has 2
> [patch] Fix IBM Cloud cert chain assertion

- ibm/mas_devops/roles/cluster_monitoring/tasks/uninstall/grafana-v4.yml
- ibm/mas_devops/roles/cluster_monitoring/tasks/uninstall/grafana-v5.yml
Delete grafana namespace without using template file.
Tested by manually running cluster monitoring role to uninstall grafana v4 and v5 in fvtcore
> [patch] fix the grafana uninstall namespace code

- ibm/mas_devops/roles/mirror_extras_prepare/vars/amlen_1.0.3.yml
slack thread - https://ibm-watson-iot.slack.com/archives/C02PUHKQB5L/p1709027799764109
In Amlen v.1.0.3, we are using digest for this kube-rbac-proxy image. so it needs to be added to the extras image content.
> [patch] add kubebuilder/kube-rbac-proxy extras image for Amlen v1.0.3

- ibm/mas_devops/roles/cert_manager/README.md
Fix for https://github.com/ibm-mas/ansible-devops/issues/1235
> [patch] Fix cert-manager default provider in readme

- ibm/mas_devops/roles/kafka/defaults/main.yaml
Looks like `community-operators` catalog is now installing strimzi-cluster-operator.v0.40.0 (released [yesterday](https://github.com/strimzi/strimzi-kafka-operator/commit/223552bff5143bd69448500f87096555e37175bf)) with `stable channel` which only supports [3.6.0, 3.6.1, 3.7.0] versions whereas our current default version is `3.5.1` so kafka task will fail with 'Unsupported Kafka.spec.kafka.version: 3.5.1. Supported versions are: [3.6.0, 3.6.1, 3.7.0]' ...
> [patch] Bump strimzi v0.40 supported kafka versions up to 3.7.0

- ibm/mas_devops/roles/mongodb/README.md
- Refactor current information about MongoDB Community operator CA renewal into a specific MongoDB troubleshooting section. 
- Add specific information related to MongoDB v5 and above related to platform requirements
- Specifically point out that MongoDB 5+ requires the AVX instruction set
> [patch] create mongodb troubleshooting section

- ibm/mas_devops/roles/cert_manager/README.md
- ibm/mas_devops/roles/cert_manager/tasks/provider/redhat/uninstall.yml
This PR addresses problems found in https://github.com/ibm-mas/cli/issues/868
It is all about including Certificate Manager CRD to be deleted in `cert_manager role` during `uninstall` action. Without that, during common services reinstall, ibm common services operator will lookup Certificate CRD and will find it and think certmanager is installed and call cert manager webhook pod (which is not present because it was deleted during certmanager uninstall) and then fail to proceed with ibm-common-services reinstall...
Tests done:
CertManager CRDs before uninstall:
All Certmanager CRDs are  gone:
Then, re-running `mas install` command after a `mas uninstall` allows reinstalling ibm common services and cert-manager just fine:
> [major] Delete all CertManager CRDs with cert-manager uninstall

- ibm/mas_devops/roles/kafka/tasks/provider/ibm/retrieve-eventstreams-certs.yml
We're dealing with an inconsistent failure in Kafka where the logs aren't helping, so we're adding more retries to the openssl command and increasing verbosity.
https://jsw.ibm.com/browse/MASCORE-2143
Added logs:
> [patch] Add retries and debugging statements for Kafka server certificates pulling

- ibm/mas_devops/plugins/filter/filters.py
- ibm/mas_devops/roles/suite_app_upgrade/tasks/upgrade.yml
- ibm/mas_devops/roles/suite_upgrade/tasks/upgrade.yml
Format functions used in upgrade roles (suite and apps) used to make "pre" versions comparable with the ones in CR
> [patch] Formating pre-versions to be comparable with reconciled versions in Operators

- ibm/mas_devops/roles/cp4d/tasks/prereqs/install-ibm-licensing.yml
Fixes the ibm-licensing package manifest lookup as it's using `label_selectors` we don't need `name` in the `k8s_info` lookup. This can cause the `label_selectors` to be overruled.
> [patch] Fix ibm licensing packagemanifest lookup

- ibm/mas_devops/roles/cluster_monitoring/README.md
- ibm/mas_devops/roles/cluster_monitoring/tasks/update_grafana/determine-storage-config.yml
- ibm/mas_devops/roles/cluster_monitoring/tasks/update_grafana/main.yml
- ibm/mas_devops/roles/cluster_monitoring/templates/grafana/v5/grafana.yml.j2
Fixing Issue https://jsw.ibm.com/browse/MASCORE-2363
Modify the Grafana update to get the V5 storage class and size from the V4 config and reuse the same values.
This also fixes the Grafana V5 persistent storage configuration which was previously incorrectly set, resulting in grafana deployments with no persistent storage
Tested in personal FVT environment
> [patch] During grafana update, get storage config from v4.

- ibm/mas_devops/roles/dro/tasks/install-dro/main.yml
[MASCORE-2328](https://jsw.ibm.com/browse/MASCORE-2328): update-uds task fails when ibm_entitlement_key secret is not avaliable on ibm-common-services namespace, added chnages to look at core namespace and pick up the ibm-entitlement-key.
> [patch] MASCORE-2328: Fix ibm-entitlement-key lookup while dro_migration

- docs/changes.md
- ibm/mas_devops/roles/db2/README.md
update to the db2 role documentation to add a referene to the db2 doc for setup of the storage class.
> [patch] update db2 role storage class doc for ref to db2 doc

- ibm/mas_devops/roles/db2/tasks/upgrade/run-db2-subscription-upgrade.yml
Probably due a back merge, the code that uses `template/db2u_subscription.yml.j2` has been added back to the `db2` role... this change fixes the code back to use `common_tasks/create_subscription.yml` to install/update the db2 subscription. Here's the initial commit that [added it](https://github.com/ibm-mas/ansible-devops/commit/c2a2e2d96aa6e2e4d416752e1ea8ac3122db540e)
With the fix, we'll be updating the subscription channel using same common task that is used during the db2 provisioning: https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/db2/tasks/install/main.yml#L160
> [patch] Fix DB2 role to use common_tasks/create_subscription.yml

- ibm/mas_devops/roles/kafka/tasks/provider/redhat/lookup-supported-kafka-versions.yml
This PR just fixes a minor bug in the strimzi subscription where we were not waiting for `status` property to be present before moving forward.
> [patch] Fix lookup kafka subscription

- ibm/mas_devops/roles/common_services/defaults/main.yml
- ibm/mas_devops/roles/common_services/tasks/main.yml
- ibm/mas_devops/roles/cp4d/tasks/prereq-check/check-cpfs-version.yml
add a check in `common_services role` in ansible-devops to check if v4 version of cpfs is already installed
if it is then skip `common_services` v3 install
this will add a safe guard on our side when we enable cpd 4.8
we don't want `common_services` role to run when v4 is already installed because if v3 is attempted to be installed in an env with v4 already installed, it will mess things up
Tests via mas install cmd in cli showing it is skipping the v3 install:
Ultimately it's easier to skip that directly in the ansible-devops rather than anticipate all possible conditions that we should cover to skip this in mas cli logic.
> [patch] Skip common-services v3 install if v4 is already installed

- docs/playbooks/oneclick-core.md
- ibm/mas_devops/playbooks/oneclick_core.yml
- ibm/mas_devops/roles/dro/defaults/main.yml
- switch bas_provider to install DRO by default from onclick_core playbook 
- Adjust the DRO contact env variables to look up UDS onces by default if they are not provided by the user to ensure the old flow does not break and users dont have to modify any existing automation.
> [minor] Make DRO default in oneclick_core playbook

- ibm/mas_devops/roles/ocp_cluster_monitoring/tasks/install.yml
The path to the determine-storage-classes is incorrect.
> [patch] Corrected path to determine-storage-classes task in ocp_cluster_monitoring role

- ibm/mas_devops/roles/kafka/README.md
kafka role was updated to have version 3.7.0 as the default, this change updated the doc to reflect it.
> [patch] update default kafka version (3.7.0) in kafka README

- ibm/mas_devops/roles/ibm_catalogs/tasks/install/main.yml
Remove the reference to the deleted tasks as part of major changes - https://github.com/ibm-mas/ansible-devops/pull/1233/files#diff-5a3be8443a58558655f0f07948c2dbfccfb9ccf250174fd13bf8594896f6fed3
This is a blocker on airgap install.
> [patch] remove the missing update-digest-map task reference

- ibm/mas_devops/roles/ocp_verify/tasks/main.yml
Tested in fvt811x (run 2922), fvtstable (run 2925) and fvtcpd (run 2919)
> [patch] Reduce ocp_verify timeout

- ibm/mas_devops/roles/kafka/defaults/main.yaml
With the current version of AMQ Streams selected by default here, the latest version of the operator fails with:
```
'Unsupported Kafka.spec.kafka.version: 3.5.0. Supported versions are: [3.6.0, 3.7.0]'
```
Bumping the version of AMQ streams to 3.7.0 to be compatible.
> [patch] Update AMQ Streams default Kafka version to 3.7

- ibm/mas_devops/roles/eck/tasks/install.yml
This update adds `when: eck_enable_logstash` clause to the step that waits for logstash server to be ready, without it the role used without logstash enabled will hang indefinitely.
> [patch] Add missing condition in wait for logstash

- ibm/mas_devops/roles/uds/tasks/uninstall/main.yml
When performing a MAS uninstall we will try to ensure that both UDS & DRO are removed from the cluster, in the case where UDS has never been previously installed the uninstall will fail because the CRDs are not even registered, so although it already handles "is not currently installed", it can not handle "it has never been installed, ever":
```
TASK [ibm.mas_devops.uds : uninstall : Delete the GenerateKey] *****************
msg: Failed to find exact match for uds.ibm.com/v1.GenerateKey by [kind, name, singularName, shortNames]
```
> [patch] Fix UDS uninstall handling UDS never installed before

- ibm/mas_devops/roles/ocp_provision/tasks/providers/fyre.yml
We check that when provisioning in fyre that a valid site has been entered
> [patch] Guard that when provisioning fyre the site is specified and supported

- ibm/mas_devops/roles/aibroker/tasks/aibroker/main.yml
- ibm/mas_devops/roles/kmodels/defaults/main.yml
- ibm/mas_devops/roles/kmodels/templates/regcred-secret.json.j2
- ibm/mas_devops/roles/odh/defaults/main.yml
- ibm/mas_devops/roles/odh/tasks/authorino-operator.yml
- ibm/mas_devops/roles/odh/tasks/odh-operator.yml
- ibm/mas_devops/roles/odh/tasks/serverless-operator.yml
- ibm/mas_devops/roles/odh/tasks/servicemesh-operator.yml
This PR adds standard ansible vars to set `mas_entitlement_key` and `mas_entitlement_username` properties while creating ibm-entitlement-key secrets
> [patch] fix mas entitlement default vars

- ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_edge_certificate.yml
This PR has logic to invoke cis certificate-order cli command in batch of 50
Tested in fvt env were we have more than 50 edge certificates to create
> [patch] invoke cis certificate-order in batch of 50

- ibm/mas_devops/roles/ocp_efs/tasks/efs-setup.yml
ROSA (HCP) does not include the "worker" filter in the Name tag for the security group. Instead, it assigns a unique tag. See #1369
> [patch] efs-setup security group lookup for HCP ROSA clusters

- ibm/mas_devops/common_tasks/get_signed_ingress_cert.yml
In ROSA with HCP, valid certificates are stored as type Opaque. This patch searches _all_ secrets in the openshift-ingress namespace for pattern matching. See #1367
> [minor] Discover Opaque TLS secrets for ingress on ROSA HCP

- ibm/mas_devops/playbooks/oneclick_core.yml
Common_services role is not required for core any more. it serves no purpose currently. 
Common_services is only installed as part of cp4d. CP4D role will install common-services v4.3.0.
This will resolve airgap issue.
> [patch] Remove common_services role from oneclick_core 

- ibm/mas_devops/plugins/filter/filters.py
Refer to run 3337 of fvtstable, error in manage-cfg:
Code was expecting wsapp as binding string, but it is workspace-application.
> [patch] Fix manage attachment filter

- ibm/mas_devops/roles/suite_install/defaults/main.yml
- ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
This PR will allow suite SSO CR setting to be configured at install time using cli.
- https://jsw.ibm.com/browse/MASCORE-2125
I set up a personal FYRE environment and followed the MAS installation process to configure both default and personal settings. Please refer to the images below for details:
> [minor] Allow Suite SSO CR settings to be configured at install time - MASCORE-2125

- ibm/mas_devops/plugins/action/verify_workloads.py
We are seeing consistent failures for this pod in CP4D to be ready:
```
[NOTREADY] ibm-cpd/ax-wdp-notebooks-api-deploy = 1 replicas/None ready/1 updated/None available
```
It's out of our control to fix this, and it's non-critical to MAS, so failures will be ignored when running workload validation.
> [patch] Ignore failures in ax-wdp-notebooks-api-deploy

- ibm/mas_devops/plugins/action/verify_workloads.py
This PR updates verify_workloads.py to include the name of deployments and statefulsets in the Error message which are not healthy.
https://jsw.ibm.com/browse/MASCORE-3352
Tested in a fyre cluster: https://dashboard.masdev.wiotp.sl.hursley.ibm.com/tests/core3352/testsuite/ibm-mas-devops/post-install-verify
> [patch] Updates ocp_verify to display notReady resources in error

- ibm/mas_devops/roles/kafka/templates/redhat/grafana-json/kafka-exporter.json
- ibm/mas_devops/roles/kafka/templates/redhat/grafana-json/kafka-zookeeper.json
- ibm/mas_devops/roles/kafka/templates/redhat/grafana-json/kafka.json
- ibm/mas_devops/roles/mongodb/templates/community/dashboards/json/mongodb-overview-grafana.json
In grafana 5 several dashboards in Mongo and Kafka roles have deprecation warnings.  The "graph" type has been deprecated and should be replaced with "timeseries".  
In addition, the `mongodb_repl_ismaster` prometheus metric query has been replaced with `mongodb_repl_isWritablePrimary` in recent versions of Mongo.  The Grafana dashboard has been updated accordingly.
> [patch] replace deprecated "graph" type with "timeseries" and update the mongo isprimary query on the mongo dashboard

- ibm/mas_devops/roles/suite_manage_customer_files_config/tasks/main.yml
Similar verification steps use `kubernetes.core.k8s_info` instead of `community.kubernetes.k8s_info`
> [patch] Use correct name of k8s_info library

- ibm/mas_devops/roles/sls/README.md
The instructions for the SLS role have incorrect environment variables when reusing an existing SLS. PR fixes this.
> [patch] Correct env name in README

- ibm/mas_devops/roles/suite_install/README.md
- ibm/mas_devops/roles/suite_install/defaults/main.yml
- ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
There is a system setting for "Guided Tours" (spec->settings->walkme) in Suite CR. It is enabled by default and can be configured from the admin UI. Due to the pop of "what's new" some of the UI test cases from Manage are failing, hence, that needs to be turned off for all fvt environments by default. As a fix, an environment variable (MAS_ENABLE_WALKME) has been introduced to control the 'walkme' setting. FVT pipelines need to use this env to disable the setting. 
Testing: Changes have been tested locally as well as on the pfvt (fyre-envs) env.
Bug details and snap shots of the FVT run can be found here: MASCORE-3444
> [patch] Introduce env variable to control walkme setting

- ibm/mas_devops/playbooks/mirror_dependencies.yml
- ibm/mas_devops/roles/mirror_images/defaults/main.yml
- ibm/mas_devops/roles/mirror_images/tasks/main.yml
This update reduces the size of the content mirrored for IBM Db2u from 78G to 40G by removing the non-amd64 images from the manifest generated by `ibm-pak`
```
mas mirror-images -m to-filesystem -d /pvc/mirror/db2-amd64only --no-confirm \
-H $REGISTRY_PRIVATE_HOST -P $REGISTRY_PRIVATE_PORT -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD \
--ibm-entitlement $IBM_ENTITLEMENT_KEY \
-c v9-240730-amd64 -C 9.0.x \
--mirror-db2
```
```
[ibmmas/cli:10.7.1]mascli$ du -hs /pvc/mirror/db2
78G     /pvc/mirror/db2
```
```
[ibmmas/cli:10.7.1]mascli$ du -hs /pvc/mirror/db2-amd64only2
40G     /pvc/mirror/db2-amd64only2
```
Additionally, we have removed mirroring of the **11.5.8.0** operand images, to further reduce the size of the mirrored content to **24G**:
```
du -hs /pvc/mirror/db2-amd64only3
24G …
```
> [patch] Optimize Db2 image mirroring

- ibm/mas_devops/roles/suite_manage_import_certs_config/templates/imported-certs.yml.j2
Patch for #1419 -- if no imported certs (I suspect because we use LetsEncrypt?), return an empty list instead of an empty string (invalid type).
> [patch] Return empty list if no certs in manage_certificates

- ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
Ref: https://github.com/ibm-mas/ansible-devops/pull/1297/files
https://ibm-watson-iot.slack.com/archives/C031Q7W21FZ/p1724134258818859
> [patch] fix gpu-operator-certified mirror error by using default v24.6 channel

- ibm/mas_devops/roles/mirror_ocp/README.md
- ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
- ibm/mas_devops/roles/ocp_contentsourcepolicy/README.md
- ibm/mas_devops/roles/ocp_contentsourcepolicy/templates/redhat-catalogs.yml.j2
- ibm/mas_devops/roles/registry/templates/certs/certificate.yml.j2
- ibm/mas_devops/roles/registry/templates/deployment.yml.j2
Adds the **LVM Storage Operator** the the MAS subset of Red Hat Operator Catalog Content.  This operator is not directly used in any of our automation, but is the standard storage classes used in Single Node OpenShift environments.
> [minor] Include LVM Storage Operator in MAS ISC and ICSP

- ibm/mas_devops/roles/cp4d/tasks/install-cp4d.yml
- ibm/mas_devops/roles/cp4d/tasks/wait/wait-zenmetastore-edb.yml
- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-ccs.yml
- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-couchdb.yml
Fixing issue https://jsw.ibm.com/browse/MASCORE-3583
CP4D installation can fail due to Pods failing to mount Persistent Volumes:
- CPD core - zen-metastore-edb pods fail
- CPD services - couchdb pods fail
This fix puts in tasks to wait for these pods to successfully deploy and restarts them if they fail
Manually tested against FVT Stable (which showed the failure), then tested in personalfvt pfvtcpd5
> [patch] restart cpd pods if they fail during installation

- ibm/mas_devops/roles/db2/README.md
- ibm/mas_devops/roles/db2/tasks/install/determine-storage-classes.yml
- ibm/mas_devops/roles/db2/templates/db2ucluster.yml.j2
To fix the bug reported on https://github.com/ibm-mas/ansible-devops/issues/1424
The changes on public Ansible role ibm.mas_devops.db2 tested successfully on AWS stg cluster `sa-s05n-euce1`, the playbook as follow:
```
Using below playbook to execute the ibm.mas_devops.db2 role,
Target cluster is on AWS SaaS.
=================================================================================================
- hosts: localhost
any_errors_fatal: true
vars:
mas_instance_id: test01
ibm_entitlement_key: xxxxxxxxxxxxxxxxxxxxxxxxx
db2_namespace: "mas-{{ mas_instance_id }}-db2u-manage"
db2_instance_name: "{{ mas_instance_id }}db2umanage"
db2_ldap_username: "{{ mas_instance_id | replace('-', '') | replace('_', '') }}managedb"
db2_ldap_password: "{{ lookup('password', '/dev/null length=8 …
```
> [patch] Fix DB2 logs/backup/temps/storage optionally condition

- docs/playbooks/oneclick-manage.md
- ibm/mas_devops/playbooks/oneclick_add_manage.yml
- ibm/mas_devops/roles/suite_app_config/README.md
- ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/health.yml
- ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/manage.yml
- ibm/mas_devops/roles/suite_app_config/vars/health.yml
- ibm/mas_devops/roles/suite_app_config/vars/manage.yml
`MAS_APP_SETTINGS_DB2_SCHEMA` (& `mas_app_settings_db2_schema`) are now referred to as `MAS_APP_SETTINGS_DB_SCHEMA` (& `mas_app_settings_db_schema`) in the docs and code - although the db2_schema variables are still compatible and viable options. This is not a breaking change.
Testing done to confirm new logic won't cause a breaking change:
For: https://github.com/ibm-mas/ansible-devops/issues/1343
> [patch] Add MAS_APP_SETTINGS_DB_SCHEMA as alt for MAS_APP_SETTINGS_DB2_SCHEMA

- ibm/mas_devops/roles/ocp_provision/README.md
- ibm/mas_devops/roles/ocp_provision/defaults/main.yml
- ibm/mas_devops/roles/ocp_provision/tasks/main.yml
This adds two special OCP versions, "default" and "rotate".
default - uses the default_ocp_version as specified in the defaults, useful for long lived test/staging environments
rotate - uses an ocp_version based on the day of the week, useful for daily test environments
The versions only specify a minor number so will not work on aws where the patch needs to be specified
> [patch] Support OCP version aliases

- ibm/mas_devops/common_vars/casebundles/v9-240625-amd64.yml
- ibm/mas_devops/common_vars/casebundles/v9-240730-amd64.yml
- ibm/mas_devops/playbooks/mirror_dependencies.yml
Failing when creating wml and wsl service in airgap with error message of missing of ibm-elasticsearch-operator operator image,
Adding back task to mirror ibm-elasticsearch-operator
> [patch] mirror ibm-elasticsearch-operator with wsl

- ibm/mas_devops/roles/suite_app_config/README.md
- ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/health.yml
- ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/manage.yml
- ibm/mas_devops/roles/suite_app_config/vars/health.yml
- ibm/mas_devops/roles/suite_app_config/vars/manage.yml
For ibm-mas/cli#1216
Corresponding issues:
- https://github.com/ibm-mas/python-devops/pull/22
- https://github.com/ibm-mas/cli/pull/1217
Aligning variable name usage across our devops tools:
- Any instance of `mas_app_settings_base_language` has been changed to `mas_app_settings_base_lang`
- Any instance of `mas_app_settings_secondary_languages` has been changed to `mas_app_settings_secondary_langs`
Also aligning the impacted readMe in `suit_app_config` to have a consistent method of declaring optional variables. This is in a separate commit to make it easier to review changes
> [patch] Align base language variable names

- ibm/mas_devops/roles/ocp_contentsourcepolicy/README.md
- ibm/mas_devops/roles/ocp_contentsourcepolicy/defaults/main.yml
- ibm/mas_devops/roles/ocp_contentsourcepolicy/templates/redhat-catalogs.yml.j2
For https://github.com/ibm-mas/ansible-devops/issues/1257
Adds a prefix variable (`redhat_catalogs_prefix` & `REDHAT_CATALOGS_PREFIX` naturally) to allow the user to add a prefix to the redhat catalogs created by the [ocp_contentsourcepolicy](https://github.com/ibm-mas/ansible-devops/tree/master/ibm/mas_devops/roles/ocp_contentsourcepolicy) role.
Prefix defaults to nothing, resulting in no change of behaviour therefore making sure this isn't a breaking change. If the prefix is not nothing when the role is run it will also add a dash to the end of the prefix. 
When running without a prefix set the catalog sources point to an address the same way they always have:
```yaml
spec:
displayName: Certified Operators
publisher: Red Hat
image: …
```
> [patch] Add Red Hat catalog prefix

- ibm/mas_devops/roles/ocp_verify/defaults/main.yml
- ibm/mas_devops/roles/ocp_verify/tasks/main.yml
General Fix for issue https://jsw.ibm.com/browse/MASCORE-3583
CP4D installation, Iot and DB2 installs fail due to persistent volume storage issues (see https://github.ibm.com/alchemy-containers/armada-storage/issues/6503)
Manually tested against FVT Stable (which showed the failure), then tested against fvt811x, confirmed the upgrade to the storage driver
> [patch] Patch the ibmcloud-block-storage-driver DaemonSet

- ibm/mas_devops/roles/mongodb/templates/community/0.7.9/cr.yml.j2
- ibm/mas_devops/roles/mongodb/templates/community/0.8.3/cr.yml.j2
Grant the admin user the dbAdminAnyDatabase role.  Among other things, this role allows the admin user to enable profiling on any mongodb database in the cluster.
> [patch] grant dbAdminAnyDatabase role to the admin user

- ibm/mas_devops/roles/ocp_provision/tasks/providers/fyre.yml
FYRE rate limits the provisioning API globally - we are competing with all other FYRE users for limited "slots" to provision new OCP+ clusters, when this happens we will see an error like this with a RC of 429:
> overall (across all product groups and users) rate limit (3 in 5 minutes) exceeded
To mitigate this we have a retry in place, but it will also trigger retries due to any other failure condition.  We will retry for approximately half an hour before giving up.
> [patch] Add retries to fyre provisioning API

- ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
problem:
1. mas install 
In step 12) Single Sign-On (SSO) ,  enter values like below. 
Many aspects of Maximo Application Suite's Single Sign-On (SSO) can be customized:
- Idle session automatic logout timer
- Session, access token, and refresh token timeouts
- Default identity provider (IDP), and seamless login
- Brower cookie properties
Configure SSO properties? [y/n] y
Idle session logout timer (seconds) 60
Session timeout (e.g. '12h' for 12 hours) 12h
Access token timeout (e.g. '30m' for 30 minutes) 30m
Refresh token timeout (e.g. '12h' for 12 hours) 12h
Default Identity Provider
fixes
```
RESULT:   TASK [ibm.mas_devops.suite_install : Create suite.ibm.com/v1 CR] ***************
error: 422
msg: 'Suite masdemo: Failed to create object: …
```
> [patch] Fix the field value type to string instead of integer for idp timeouts

- ibm/mas_devops/playbooks/mirror_dependencies.yml
- ibm/mas_devops/roles/mirror_images/defaults/main.yml
- ibm/mas_devops/roles/mirror_images/templates/auth-secret.json.j2
We needed the `redhat_connect_username` and `redhat_connect_password` for mirroring UDS images because some images were in the RedHat container registry instead of the IBM container registry.  Now that we have completed the migration to DRO there is no need for this anymore/mirroring UDS is no longer supported as UDS has been shut down.
> [major] Remove UDS image mirroring support

- .github/workflows/ansible-publish.yml
- .github/workflows/ansible.yml
- ibm/mas_devops/roles/cp4d/tasks/create-cpd-core-service-accounts.yml
- ibm/mas_devops/roles/cp4d/tasks/install-cp4d.yml
- ibm/mas_devops/roles/cp4d_service/tasks/create-cpd-service-accounts.yml
- ibm/mas_devops/roles/cp4d_service/tasks/install.yml
- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-ccs.yml
- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-elasticsearch.yml
- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-wml-etcd.yml
Fixing Issue https://jsw.ibm.com/browse/MASCORE-3802
409 conflicts occur when applying changes client side as the resource changed has been modifed server side by the time the api call has succeeded. To fix this we use kubernetes server-side apply.
**Testing** 
I tested the new code against pfvtcpd48 cluster, the roles succeeded which doesn't necessarily mean that this intermittent failure is fixed but shows that the server side apply works and doesn't break things further
> [patch] apply kubernetes changes server side to avoid version conflicts

- ibm/mas_devops/roles/cos/README.md
- ibm/mas_devops/roles/cos/defaults/main.yml
- ibm/mas_devops/roles/cos/tasks/providers/ibm/provision.yml
- ibm/mas_devops/roles/cos/templates/ibm/objectstoragecfg.yml.j2
Manage App requires COS instance with HMAC encrypted accesskey and secretkey.
We have tested 2 scenarios:
1). Set HMAC as True. Created build and manage app -instance fvt27929
it sets accesskey, and secret key along with username and password:
objectstorage config is in Ready State:
I have further tested consuming this accesskey and secret key for manage tests and those are working.
2). Set HMAC as False. Created build and manage app -instance fvt28915
it does not set accesskey, and secret key. However it sets username and password as per existing code.
objectstorage config is in Ready State:
> [minor] Added HMAC support for cos

- ibm/mas_devops/common_tasks/detect_cert_manager.yml
Sometimes, awk cmd used here seem to not work in some systems. 
```
- name: Lookup Certificate Manager installations
shell: oc get pods -A | grep cert-manager-cainjector | awk '{print $1}'
register: cert_manager_webhook_lookup
```
Hence, awk is replaced with k8s_info to fetch the pod using label_selectors: **app=cainjector**
https://github.com/ibm-mas/ansible-devops/issues/1323
https://jsw.ibm.com/browse/MASCORE-3809
Tested in a quickburn cluster by installing core. As seen below, k8s_info fetches the pods by label selector successfully and then json_query finds the namespaces from the fetched pods.
[Masdev Install Log.log](https://github.com/user-attachments/files/16905857/Masdev.Install.Log.log)
> [patch] replaces awk cmd with k8s_info in detect_cert_manager

- ibm/mas_devops/roles/ocp_provision/tasks/providers/fyre/nfs/install_nfs.yml
The logic is inverted, we only set up NFS if the NFS storage class is already installed :)
> [patch] Fix NFS idempotency checks

- ibm/mas_devops/roles/cos/README.md
- ibm/mas_devops/roles/cos/defaults/main.yml
- ibm/mas_devops/roles/cos/tasks/providers/ibm/provision.yml
As `use_hmac` parameter refers to cos, we must use `cos_` prefix to follow the standard for cos parameters.
We have three PRs that must be merged together:
- https://github.com/ibm-mas/cli/pull/1241
- https://github.com/ibm-mas/ansible-devops/pull/1467
- https://github.ibm.com/maximoappsuite/ansible-fvt/pull/478
-----
Tested in fvt-personal (pfvtaleq):
And `cos` role/task has passed:
> [patch] Add cos prefix in use_hmac parameter

- ibm/mas_devops/roles/cos/tasks/providers/ibm/provision.yml
Simple debug statement for cos hmac. 
Test results:
```
TASK [ibm.mas_devops.cos : debug access_key_id] ********************************
ok: [localhost] => 
msg:
- access_key_id ..... <redacted>
```
> [patch] debug statement for cos hmac

- ibm/mas_devops/common_tasks/create_subscription.yml
https://jsw.ibm.com/browse/MASCORE-3864 Is caused by an update to catalogs while the cert manager is being installed. To avoid this, the install pipeline has been changed to run the cert-manager role after the ibm-catalogs role (see https://github.com/ibm-mas/cli/pull/1249).
This change tests that the subscription successfully reaches "AtLatestKnown" state before continuing processing, giving an early failure if the subcription fails to resolve.
**Testing**
Tested by running in pfvtpds cluster:
> [patch] wait for subscription to complete when creating

- ibm/mas_devops/roles/grafana/tasks/install/main.yml
- ibm/mas_devops/roles/grafana/templates/grafana/v4/grafana-prometheus-serviceaccount.yml.j2
- ibm/mas_devops/roles/grafana/templates/grafana/v5/grafana-prometheus-serviceaccount.yml.j2
- ibm/mas_devops/roles/suite_install/defaults/main.yml
I fixed this by copying the rbac rules from the prometheus user workload serviceaccount and allowing us to create our own and modify the rules. The missing rules were:
```
- verbs:
- get
- create
apiGroups:
- monitoring.coreos.com
resources:
- prometheuses/api
- prometheus/api
- prometheuses
- prometheus
```
I am not sure if this is a a new feature that was added to 4.15 OpenShift, but we didn't have the ability to manipulate the rules in the existing service account. This should guarantee we have control over the roles and permissions of Grafana going forward so we do not hit 401 and 403 errors and if we do we can easily update the file and redeploy.
> [patch] [MASCORE-3733] grafana dashboard not working after upgrade openshift to v4.15

- ibm/mas_devops/roles/suite_app_config/vars/health.yml
- ibm/mas_devops/roles/suite_app_config/vars/manage.yml
- ibm/mas_devops/roles/suite_manage_pvc_config/tasks/determine-storage-classes.yml
No related issue to this but found a bug around the storage class `nfs-client` setup not being defaulted for manage and health as well as not setting it as the cluster primary storage when installing quick burn Fyre clusters.
> [patch] fix nfs for manage and health

- ibm/mas_devops/common_tasks/detect_cert_manager.yml
Currently, the task for namespace lookup in detect_cert_manager fails if the certificate_manager_provider is used as ibm since, it has a different app label compared to redhat provider. This change adds the label for ibm provider as well.
https://jsw.ibm.com/browse/MASCORE-3918
Tested in a quickburn with 2 scenarios having certificate manager as ibm and redhat.
**Certificate manager provider is ibm:**
**Certificate manager provider is redhat:**
> [patch] Fix namespace lookup when cert provider is ibm

- ibm/mas_devops/roles/gencfg_mongo/README.md
- ibm/mas_devops/roles/gencfg_mongo/defaults/main.yml
- ibm/mas_devops/roles/gencfg_mongo/tasks/main.yml
- ibm/mas_devops/roles/gencfg_mongo/templates/suite_mongocfg.yml.j2
- ibm/mas_devops/roles/mongodb/README.md
Previously for the convenience role `gencfg_mongo` there was no mention of how to configure LDAP authentication. LDAP authentication is available when the MongoDB instance is MongoDB EE. When using LDAP authentication the `authMechanism` in the MongoCfg must be set to `PLAIN` and the `configDb` field should be set to `$external`
This PR will introduce documentation related to LDAP authentication and update the `gencfg_mongo` role to allow setting of the `authMechanism` and `configDb`.
**note**
In the MongoCfg the filed `configDb` refers to the MongoDB authentication database. 
All scenarios of the `gencfg_mongo` role have been testing with respect to `authMechanism` and `configDb`. This includes default settings as well as setting `authMechanism` to DEFAULT and PLAIN.
> [patch] allow setting of PLAIN authentication for MongoDB

- ibm/mas_devops/common_vars/default_storage_classes.yml
This PR is for support storage classes for cluster provisioned in techzone
This was tested by me on Mas Core + AI Broker deployment
> [patch] add support for default storage classes in techzone clusters

- ibm/mas_devops/roles/turbonomic/tasks/main.yml
No major changes, just moving the secret creation higher in the list for the authenticating pod to use later.
> [patch] Bump secret creation earlier in Turbonomic role

- ibm/mas_devops/roles/grafana/tasks/install/main.yml
@cuddlyporcupine  ran into an issue where short hand api version wasn't working, this works in both older and newer clusters
> [patch] use apiVersion instead of api in grafana role

- ibm/mas_devops/roles/mongodb/README.md
- ibm/mas_devops/roles/mongodb/defaults/main.yml
- ibm/mas_devops/roles/mongodb/tasks/providers/community/install-mongo.yml
When running load test Eric discovered that we ran into an issue with Mongo being scaled down and having all of it's setting overwritten during an upgrade. We do no preserve Mongo settings meaning the environment variables need to be set to what you have or you lose everything.
This new functionality will preserve your settings by default and adds a new environment variable that allows you to revert spec or overwrite the spec how you see fit to allow the existing functionality to still be used.
> [patch] [MASCORE-3990] Mongo v7 upgrade wipes existing stateful set cpu/memory requests/limits

- ibm/mas_devops/roles/mongodb/templates/community/dashboards/json/mongodb-overview-grafana.json
Grafana v5 timeseries panels require config changes to the panel tooltip and legend.  The necessary changes have been made for the mongodb Grafana v5 dashboard.
> [patch] updates to mongodb grafana v5 dashboard

- docs/playbooks/oneclick-core.md
Fixes mixing of the expected storageclass type in the readme
> [patch] Update block vs file storageclass in oneclick_core readme

- docs/playbooks/oneclick-core.md
- ibm/mas_devops/common_vars/cp4d_supported_versions.yml
- ibm/mas_devops/roles/cp4d/tasks/wait/wait-zenmetastore-edb.yml
Update the license configuration for the zenmetastore-edb postgres database which expired on 1 October 2024
following these instructions https://www.ibm.com/support/pages/node/7158524
Fixing https://jsw.ibm.com/projects/MASCORE/issues/MASCORE-4051 
I also removed the unnecessary code to restart any Pending ZenMetastore pods, that was a tactical workaround when we had storage class issues and was permanently fixed with https://github.com/ibm-mas/ansible-devops/pull/1440
**Testing**
Tested in pfvtcpd48 cluster and fvtstable clusters
> [patch] update expired zenmetastore-edb license

- ibm/mas_devops/roles/suite_app_config/README.md
- ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/health.yml
- ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/manage.yml
- ibm/mas_devops/roles/suite_app_config/vars/health.yml
- ibm/mas_devops/roles/suite_app_config/vars/manage.yml
Added variable for setting Vargraphic option in Manage and Health database configuration. By default sets to True to avoid breaking changes.
> [patch] Add variable for vargraphic setting for Manage and Health

- ibm/mas_devops/roles/grafana/tasks/install/main.yml
The current prometheus token expires after 1 hour, resulting in dashboards rendering 403 error codes 1 hour after grafana is installed.  With this change the prometheus token expiration is much larger.
> [patch] add large expiration time to the prometheus token creation in the grafana ansible role

- ibm/mas_devops/roles/grafana/tasks/install/main.yml
- ibm/mas_devops/roles/grafana/templates/grafana/v5/grafana-prometheus-serviceaccount.yml.j2
In order not to use the 'oc cli'. We switch the creation of the token of the prometheus service account via the creation of a dedicated secret and we retrieve it via the ansible k8s_info module.
Since Openshit 4.16, the creation of an SA no longer automatically generates a token. So we have to create it.
> [patch] Switch Prometheus SA token creation from oc cli to ansible module

- ibm/mas_devops/common_vars/casebundles/v9-241107-amd64.yml
- ibm/mas_devops/roles/mirror_extras_prepare/vars/amlen_1.1.2.yml
Prior to this fix if the operator is restarted whilst it is configuring Amlen it can leave the Amlens in a state that the operator doesn't cover them from. This includes a fix to that timing window.
> [patch] Include amlen operator 1.1.2 with small fix for a timing window

- ibm/mas_devops/roles/ocp_efs/tasks/efs-setup.yml
Small change to allow the efs role to distinguish between similar named clusters.
Adding the `-` means we can find the cluster `fvtsaas` when we also have a `fvtsaas2` cluster. The value in the tags for the vpc has the vpic id like `fvtsaas-xgsrr-vpc`
> [patch] Add dash to the cluster name to have indenitifer the vpc in ocp_efs role

- ibm/mas_devops/roles/ocp_provision/tasks/main.yml
Adding OCP 4.16 to the OCP rotation, 4.15 is still the default and still runs over the weekend. The reason for choosing monday was that anyone analyzing test results on monday will typically be looking at tests from Friday and the weekend so it's nice for them to all be using the same OCP level.
Runs on OCP 4.16 have found no problems with Core or IoT so this expands coverage to the other Apps.
> [PATCH] Add OCP 4.16 into the rotation

- ibm/mas_devops/common_vars/casebundles/v9-241107-amd64.yml
- ibm/mas_devops/playbooks/mirror_dependencies.yml
- ibm/mas_devops/roles/cp4d/templates/catalog_sources/5.0.0.yml
Changes to the catalog to include the new versions needed for CPD 5.0.0 and changes to the mirroring tasks to support them.
> [MINOR] change from CPD 4.8.0 to 5.0.0

- ibm/mas_devops/playbooks/br_health.yml
- ibm/mas_devops/playbooks/br_iot.yml
- ibm/mas_devops/playbooks/br_manage.yml
- ibm/mas_devops/playbooks/br_monitor.yml
- ibm/mas_devops/playbooks/br_optimizer.yml
When running a backup/restore playbook that runs the action in a job, it is not passing the DB2_NAMESPACE that is set and so defaults to `db2u`
Updated each br playbook that backusp db2.
Tested here shows the namespace set, when I exported `DB2_NAMESPACE` before running the `br_manage` playbook:
> [patch] Add db2_namespace to backup/restore job

- ibm/mas_devops/roles/suite_app_uninstall/tasks/main.yml
Uninstall for manage fails intermittently as it gets timed out after 5 mins waiting for namespace to be deleted. This change updates the waiting timeout to 10 mins.
https://dashboard.masdev.wiotp.sl.hursley.ibm.com/tests/fvtuninstall/testsuite/ibm-mas-devops/app-manage-uninstall
> [patch] Updates wait_timeout for namespace deletion in suite_app_uninstall

- ibm/mas_devops/roles/suite_app_config/tasks/main.yml
- ibm/mas_devops/roles/suite_dns/README.md
After post-configuration is executed for Manage in suite-app-config, there is no checking to ManageWorkspace is healthy before the role is finished. This PR adds the same verification performed before post-configuration runs, afterwards.
Test completed in fvt personal:
----
@durera it includes a quick update in cis_email README as we briefly talked yesterday during your tests
> [patch] Add additional verification after manage config

- build/ee/requirements.yml
The publishing of the release of the execution environment is broken as the galaxy requirements was still using file. This is only seen in the publish phase
> [patch] Fix Execution Environment publish release

- .github/workflows/ansible-publish.yml
Need to push the versioned imaged as well as latest on publish. For now I have manually created the 23.4.0 image from the latest in quay.io. This change will push that as part of the release.
> [patch] Push versioned container image of ansible-devops-ee on publish

- ibm/mas_devops/common_tasks/backup_restore/copy_storage_files_to_pod.yml
This update corrects the syntax of a couple of `shell` tasks when transferring files out of pods when running the backup/restore in non-local mode.
- Fixes #1531
> [patch] Fix oc exec commands

- ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
nvidia pushed a new version of the gpu-certified-operator (version 24.9.0) on 31/10/24 this broke our ability to mirror the redhat operators. Tested with 4.14 but should fix all OCP releases as it's common code. Specific command tested:
```
mas mirror-redhat -m direct -d /tmp/mirror --no-confirm \
-H $REGISTRY_HOST -P $REGISTRY_PORT -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD \
--pullsecret /mnt/pullsecret/pull-secret.json \
--release 4.14 \
--mirror-operators
```
> [patch] Fix gpu-certified-operator default channel

- ibm/mas_devops/roles/mongodb/tasks/providers/community/validate-upgrade.yml
https://jsw.ibm.com/browse/MASCORE-4343
- Fixes #1507
> [patch] prevent mongo upgrade when featureCompatibilityVersion is not defined or set incorrectly

- ibm/mas_devops/roles/suite_upgrade/tasks/upgrade.yml
Fixes an issue where the upgrade check is getting the version in the operatorcondition that is not the final version of the operator. This happens when doing an upgrade and OLM goes from 8.11.10 -> 9.0.0 -> 9.0.3. The verification was catching the operatorcondition at the 9.0.0 and was then expecting that to be the final reconciled version.
The check is tricky as when upgrading to a level that has no patch levels then it is only one hop i.e. from 9.0.3 -> 9.1.0.
The suite_app_upgrade task has a 5 minute pause for this exact issue so we can copy that for now.
> [patch] Wait for olm to update operatorcondition on upgrade

- ibm/mas_devops/roles/grafana/tasks/install/main.yml
- ibm/mas_devops/roles/grafana/templates/cluster-monitoring-config.yml.j2
This fixes a bug where if the user had his own stuff defined in his config map for grafana we would just overwrite the entire configmap with our own and they would lose all their settings. This helps make sure we check if the configmap exists first and if so we carry the settings over and append the one setting we're trying to set.
> [patch] [MASCORE-4344] Grafana role overwriting critical k8s configuration resource

- ibm/mas_devops/roles/kafka/templates/redhat/clusters/large.yml.j2
- ibm/mas_devops/roles/kafka/templates/redhat/clusters/small.yml.j2
Add parameter `Kafka.spec.clusterCa.validityDays: 7200` (20 years) to Kafka for Cluster CA certificates.
https://strimzi.io/docs/operators/latest/deploying#con-certificate-renewal-str
The default validity period for Kafka Cluster CA certificates is 365 days. This patch adds parameter `Kafka.spec.clusterCa.validityDays: 7200` / 20 years.
Without this parameter the Kafka Operator generates a new CA certificate every year that needs to be imported into MAS.
Just for the record. The following steps are required in MAS after the Kafka CA certificate has been renewed.
Import new certificate
```
oc get secret maskafka-cluster-ca-cert \
-n strimzi \
-o=jsonpath='{.data.ca\.crt}' | base64 -d > maskafka-ca.crt
```
```
instance=dev
```
```
openssl x509 -in maskafka-ca.crt -noout -dates -subject …
```
> [minor] Add Kafka Cluster CA certificate validityDays

- ibm/mas_devops/roles/suite_manage_imagestitching_config/tasks/main.yml
Slack discussion:
https://ibm-watson-iot.slack.com/archives/C031Q7W21FZ/p1730994652345789
Jira item: https://jsw.ibm.com/browse/MAXMIS-897
Older releases are using a version of the workspace schema where deployimagestitching is not present
I've added a check for this attribute and skip the role if not present
To test I deployed a pod in Civil's FVT cluster using the latest CLI and ran this playbook:
```
- hosts: localhost
any_errors_fatal: true
vars:
mas_instance_id: civil
mas_workspace_id: masdev
mas_ws_cr_name: civil-masdev
mas_domain: civil.ibmmasfvt.com
manage_namespace: mas-civil-manage
stitching_pvcname: manage-imagestitching
stitching_storage_class: nfs-client
stitching_storage_size: 20Gi
stitching_storage_mode: ReadWriteMany
stitching_storage_mountpath: imagestitching
roles:
- …
```
> [patch] MAXMIS-897: check if attribute 'deployimagestitching' is defined

- ibm/mas_devops/roles/appconnect/README.md
- ibm/mas_devops/roles/cp4d/README.md
- ibm/mas_devops/roles/cp4d_service/README.md
- ibm/mas_devops/roles/db2/README.md
- ibm/mas_devops/roles/dro/README.md
- ibm/mas_devops/roles/grafana/README.md
- ibm/mas_devops/roles/kafka/README.md
- ibm/mas_devops/roles/mongodb/README.md
- ibm/mas_devops/roles/ocp_cluster_monitoring/README.md
- ibm/mas_devops/roles/registry/README.md
- ibm/mas_devops/roles/suite_app_config/README.md
- ibm/mas_devops/roles/suite_app_install/README.md
- ibm/mas_devops/roles/suite_manage_imagestitching_config/README.md
- ibm/mas_devops/roles/suite_manage_pvc_config/README.md
- ibm/mas_devops/roles/uds/README.md
Document the access mode in roles readmes
- https://github.com/ibm-mas/ansible-devops/issues/924
- MASCORE-4346
> [doc] Document storage class access mode

- ibm/mas_devops/roles/nvidia_gpu/README.md
- ibm/mas_devops/roles/nvidia_gpu/defaults/main.yml
- ibm/mas_devops/roles/nvidia_gpu/tasks/main.yml
- ibm/mas_devops/roles/nvidia_gpu/tasks/nfd_setup.yml
- ibm/mas_devops/roles/nvidia_gpu/templates/clusterpolicy-customversion.yml.j2
- ibm/mas_devops/roles/nvidia_gpu/templates/clusterpolicy-v2.yml.j2
* update the cluster policy template to not specify a driver version and use the latest driver by default
* add another cluster policy template to use specific driver version when associated env variable `GPU_DRIVER_VERSION` is used
* skip NDF setup if associated daemon worker is already running
* skip GPU setup if associated cluster policy is Ready
* update default GPU channel version
Addresses the following bugs:
- Fixes https://github.com/ibm-mas/ansible-devops/issues/1453
- Fixes https://github.com/ibm-mas/ansible-devops/issues/1384
- Fixes https://github.com/ibm-mas/ansible-devops/issues/1454
- Fixes https://github.com/ibm-mas/ansible-devops/issues/1453
> [patch] Address several issues w/ Nvidia playbook

- ibm/mas_devops/roles/suite_db2_setup_for_manage/vars/main.yml
https://jsw.ibm.com/browse/MASCORE-4517
TS017131353 (SC) - DB config is not applied during db2u instance startup
A few of the db2 configs applied jus before Manage install is causing conflits and resulting in 
```
SQL1668N  The operation failed because the operation is not supported with 
this environment. Reason code: "9".
```
The fix was discussed with the db2 team on this slack thread: https://ibm-cloudplatform.slack.com/archives/C019EJ0QH4Y/p1729189859898779?thread_ts=1728336840.156449&cid=C019EJ0QH4Y 
i have tested this manually on tech foundation cluster and i was able to apply the updated db2config successfully 
`update db cfg for BLUDB using  APPLHEAPSZ 8192 AUTOMATIC AUTHN_CACHE_DURATION 10 AUTHN_CACHE_USERS 100 AUTO_DB_BACKUP OFF AUTO_DEL_REC_OBJ ON AUTO_MAINT ON AUTO_REORG OFF …
> [patch] fix conflicting DB config

- ibm/mas_devops/roles/suite_db2_setup_for_manage/tasks/apply-db2-config-version.yml
- ibm/mas_devops/roles/suite_db2_setup_for_manage/vars/main.yml
issue: https://github.com/ibm-mas/ansible-devops/issues/1061
https://github.com/ibm-mas/ansible-devops/pull/1567 modifies the db2config to use `/mnt/backup' . we dont need to create a folder for /mnt/backup/MIRRORLOGPATH' anymore as it wont be used due to the above PR. 
db2 will create NODE0000 directory under /mnt/backup and automatically set MIRRORLOGPATH to /mnt/backup/NODE0000/LOGSTREAM0000/ , so we set MIRRORLOGPATH to /mnt/backup. 
Refer below slack thread for detailed info. 
https://ibm-cloudplatform.slack.com/archives/C019EJ0QH4Y/p1729023737866499?thread_ts=1728336840.156449&cid=C019EJ0QH4Y
> [patch] remove MIRRORLOGPATH folder creation 

- ibm/mas_devops/roles/suite_app_backup_restore/tasks/get-app-info.yml
- ibm/mas_devops/roles/suite_app_backup_restore/tasks/manage/pv-info.yml
- ibm/mas_devops/roles/suite_app_backup_restore/tasks/manage/restore-namespace.yml
This change will not run certain tasks in pv-info.yamk when `masbr_manage_pvc_paths` is not defined.
Also it now applies backed up manage resources.
> [patch] fix restore for manage role

- ibm/mas_devops/playbooks/mirror_dependencies.yml
The catalog_digest is not being set when executing mirroring. The variable is available in  `mas_catalog_metadata.catalog_digest` and should be set when preparing the extra images.
> [patch] Fix missing catalog_digest

- ibm/mas_devops/playbooks/mirror_dependencies.yml
With the switch to using `ibm.mas_devops.get_catalog_info` we now need an extra task to set `cpd_product_version` if it's not set explicitly using the `CPD_PRODUCT_VERSION` environment variable.
> [patch] Set cpd_product_version  from catalog metadata

- ibm/mas_devops/playbooks/mirror_dependencies.yml
We're loading `mongo_extras_version` from the catalog manifest instead of `mongo_extras_version_default`.
```
TASK [ibm.mas_devops.mirror_extras_prepare : extras : Select task to run] ******
ok: [localhost] => changed=false
ansible_facts:
task_name: extras
TASK [ibm.mas_devops.mirror_extras_prepare : extras : Generate manifests] ******
included: /opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/mirror_extras_prepare/tasks/extras.yml for localhost
TASK [ibm.mas_devops.mirror_extras_prepare : mongoce : Fail if required properties are not provided] ***
ok: [localhost] => changed=false
msg: All assertions passed
TASK [ibm.mas_devops.mirror_extras_prepare : mongoce : Load variables] *********
fatal: [localhost]: FAILED! => changed=false
ansible_facts: {} …
```
> [patch] Use correct variable for mongo extras

- ibm/mas_devops/roles/cp4d/README.md
- ibm/mas_devops/roles/cp4d_service/README.md
Added CPD estimates in the readme 
slack thread - https://ibm-watson-iot.slack.com/archives/C01ABHMP3TP/p1732632434929519?thread_ts=1732204134.914569&cid=C01ABHMP3TP
> [patch]  Add estimates for cpd in readme

- ibm/mas_devops/plugins/action/get_default_storage_classes.py
We don't want to fail if we can't find any default storage classes, doing so will result in roles/playbooks failing in environments where none of the default storage classes are available.  We use the success=false to track when we couldn't find a default storage class, which does not trigger Ansible treating the action as failed.
> [patch] get_default_storage_classes should always set failed=False

- ibm/mas_devops/roles/db2/tasks/install/main.yml
- ibm/mas_devops/roles/db2/templates/certs/certificate.yml.j2
- ibm/mas_devops/roles/db2/templates/db2ucluster.yml.j2
Currently if multiple DB2 instances are installed and configured the existing Certificate Resource contents will be overwritten by the last install. This becomes a problem as the dnsNames entries (SAN) will be updated. This will result in pre-existing instances using a certificate that contains no matching SAN entry in the certificate for the hostname. 
This is being tracked internally with the following JIRA:
- https://jsw.ibm.com/browse/MASCORE-4553
After this change there will be a unique Certificate and correpsonding Secret resource for each DB2 instance. The unique Certificates will have the same CA however. Take for example a DB2 install for an instance identified by `db2u-db01. A Certificate and Secret named `db2u-certificate-db2u-db01` will be created:
```bash
oc get Certificate …
```
> [patch] create unique certificate for each db2 instance

- ibm/mas_devops/roles/cos/tasks/providers/ibm/deprovision.yml
Deprovision of COS in IBM Cloud is failing because of incorrect parameter name used. Functions of ibm.cloudcollection require ibmcloud_api_key as a parameter and instead cos_apikey is passed. This changes fixes that reference.
MASCORE-4641
Tested the role locally.
> [patch] Fixes ibmcloud_api_key issue in COS deprovision for ibmcloud

- ibm/mas_devops/roles/ocp_deprovision/tasks/providers/rosa.yml
Deprovision time for ROSA is sometimes taking more than an hour. Increase wait time to 1.5 hours to cover this.
> [patch] Increase rosa deprovision wait time

- ibm/mas_devops/roles/suite_dns/defaults/main.yaml
Fixes issue with non boolean default values causing wrong assertions when running this role.
Before this fix when cis_enhanced_security was set to a string False value
```
TASK [ibm.mas_devops.suite_dns : cis : running standard cis suite dns] *********
skipping: [localhost] => changed=false 
false_condition: not cis_enhanced_security
skip_reason: Conditional result was `False`
```
After fix:
```
TASK [ibm.mas_devops.suite_dns : cis : running standard cis suite dns] *********
included: /opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_suitedns_basic.yml for localhost
```
> [patch] fix default booleans for suite_dns

- ibm/mas_devops/roles/cos/README.md
- ibm/mas_devops/roles/cos/defaults/main.yml
There's almost no scenario in which we want to use IBM COS without HMAC encrypted credentials, because it prevents some applications in MAS using that COS instance.
> [patch] Enable HMAC by default for IBM COS

- .github/workflows/ansible-publish.yml
- .github/workflows/ansible.yml
- ibm/mas_devops/requirements.txt
We're preparing a major version bump that will remove support for ICSP and replace it with IDMS support.  Ahead of this we need to ensure that the current version of the Ansible Collection is set up to not automatically pick up the v2 release of mas-devops from PyPi.
> [patch] Lock mas-devops less than v2

- ibm/mas_devops/roles/cos_bucket/tasks/providers/ibm/create.yml
- ibm/mas_devops/roles/cos_bucket/tasks/providers/ibm/delete.yml
Different env settings are required based on provider to provide Resource group and cos_resourcegroup is ignored for 'IBM' even though it is being assigned with ibm_cloud_resourcegroup by default. Hence, updating the script to use cos_resourcegroup while creating/deleting the bucket. 
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/cos_bucket/defaults/main.yml#L15
Changes have been tested in pfvt (with different branch - svtemp) and results are here => https://dashboard.masdev.wiotp.sl.hursley.ibm.com/tests/stfin
> [patch] Fix cos_bucket picking incorrect resourcegroup

- ibm/mas_devops/roles/ocp_provision/tasks/main.yml
Removing ocp 12 from cluster version rotation.
> [patch] Remove OCP 4.12 & 4.13 from rotation

- ibm/mas_devops/roles/suite_app_uninstall/app_specific/tasks/pre/manage.yml
When executing suite_app_uninstall role, the manage namespace deletion gets stuck in terminating state because it waits for ManageServerBundle and ManageDeployment CRs to be deleted. Hence, for a clean uninstall, I have added pre-steps in the role to be executed for manage which will delete those CRs first.
MASCORE-4950
Tested in a quickburn with 1 and multiple server bundles.
Cluster with 1 server bundle:
[HTNew Uninstall Logs 250103.log](https://github.com/user-attachments/files/18314332/HTNew.Uninstall.Logs.250103.log)
Cluster with multiple server bundles:
[HTNew Uninstall Log 250104.log](https://github.com/user-attachments/files/18314335/HTNew.Uninstall.Log.250104.log)
> [patch] Fixes manage namespace uninstall stuck in terminating state

- ibm/mas_devops/common_tasks/backup_restore/check_backup_vars.yml
- ibm/mas_devops/common_tasks/backup_restore/check_restore_vars.yml
- ibm/mas_devops/common_tasks/backup_restore/copy_pod_files_to_storage.yml
- ibm/mas_devops/common_tasks/backup_restore/copy_storage_files_to_pod.yml
- ibm/mas_devops/common_tasks/templates/backup_restore/backup-namespace-resources.sh.j2
- ibm/mas_devops/roles/suite_app_backup_restore/tasks/restore-pv.yml
Sorry for the misleading branch title, the issue was originally assigned under SLS before I realized it was a manage specific issue for backup and restoring pod files. 
Steps to test this were as follows
Run the back up using these commands:
```
export MASBR_ACTION=backup
export MASBR_MANAGE_PVC_PATHS="manage-doclinks:/DOCLINKS"
export MASBR_STORAGE_LOCAL_FOLDER=/tmp/backup
export ROLE_NAME="suite_app_backup_restore"
export MAS_WORKSPACE_ID=masdev
rm -rf /tmp/backup
mkdir -p /tmp/backup
ansible-playbook ibm.mas_devops.run_role
```
Backup complete successfully:
Specific task we want to see succeed
```
TASK [ibm.mas_devops.suite_app_backup_restore : Copy files from pod folder to local storage folder] **************
changed: [localhost] => (item={'src_folder': '/DOCLINKS', 'dest_folder': …
```
> [patch] [MASCORE-5063] Problems with Restoring PV data - DT420492

- ibm/mas_devops/roles/cp4d/tasks/wait/wait-zenmetastore-edb.yml
Fix description
----
Edited wait-zenmetastore-edb.yml to include the api version of the Postgres cluster
This is a minor fix to solve issue reported at https://github.com/ibm-mas/ansible-devops/issues/1612
Tested locally by editing the file and manually running cp4d role
```
TASK [ibm.mas_devops.cp4d : wait-zenmetastore-edb : Wait for ZenMetastore pods to be become ready] *****************************************************************************************************************
ok: [localhost] => changed=false 
api_found: true
attempts: 1
resources:
- apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
...
conditions:
- lastTransitionTime: '2025-01-08T05:56:07Z'
message: Cluster is Ready
reason: ClusterIsReady
status: 'True'
type: Ready
- lastTransitionTime: …
```
> [patch] Add missing api_version to k8s_info lookup

- ibm/mas_devops/roles/suite_app_upgrade/tasks/check_app_compatibility.yml
Replaces assert condition's 1 time check with a wait condition to check for ready state in compatibility check for upgrade. The current wait timer is set to 40 mins (2 mins delay) same as how the check is after the upgrade.
MASCORE-5257
Tested in a quickburn.
[HTNew Upgrade Logs 250128 0905.log](https://github.com/user-attachments/files/18571924/HTNew.Upgrade.Logs.250128.0905.log)
> [patch] Adds wait timer in app compatibility check for upgrade

- ibm/mas_devops/galaxy.yml
cos_bucket role is failing due to the latest version of ibm.cloudcollection version (1.71.2). Hence, setting the max version to 1.51.0 until ansible-devops is ready to adopt 1.71.2 version. 
Bug reference: MASCORE-5436
Tested the fix using cli:
> [patch] set ibm.cloudcollection max version to 1.51.0

- ibm/mas_devops/roles/mirror_ocp/tasks/main.yml
- We will only generate the docker config and combine if registry_public_url is provided otherwise we move the redhat_pullsecret file directly into .../config.json
- https://github.com/ibm-mas/ansible-devops/issues/1635
- I tested the relevant piece of code locally
> [patch] Make registry_public_url optional in mirror_ocp

- ibm/mas_devops/common_tasks/backup_restore/copy_storage_files_to_pod.yml
When fixing the backup, I managed to let an untested change get through causing it to fail. I must've not saved my final change when committing.
> [patch] used asterisk where . should be

- Makefile
- ibm/mas_devops/galaxy.yml
- ibm/mas_devops/plugins/action/apply_subscription.py
- ibm/mas_devops/plugins/action/get_default_storage_classes.py
- ibm/mas_devops/plugins/action/update_ibm_entitlement.py
- ibm/mas_devops/plugins/action/verify_app_version.py
- ibm/mas_devops/plugins/action/verify_catalogsources.py
- ibm/mas_devops/plugins/action/verify_core_version.py
- ibm/mas_devops/plugins/action/verify_subscriptions.py
- ibm/mas_devops/plugins/action/verify_workloads.py
It's been pointed out to me that the Ansible dependencies in this project have not been being maintained, this update brings our dependency stack up to date, with the exception of `ibm.cloudcollection` which we know there is a breaking change in the newest version: https://github.com/ibm-mas/ansible-devops/pull/1634
- Update kubernetes.core to `>=5.1.0`
- Update ansible.utils to `>= 5.1.2`
- Update community.general to `>=10.3.0`
> [patch] Update Ansible dependencies

- docs/playbooks/backup-restore.md
- ibm/mas_devops/common_tasks/backup_restore/check_restore_vars.yml
- ibm/mas_devops/common_tasks/backup_restore/copy_storage_files_to_pod.yml
Customer has requested that we offer the choice to overwrite data when restoring instead of just failing if there is existing data in the directory. This adds a new required environment variable that asks the customer to confirm if they want to overwrite data or fail if we detect any. 
User will be shown this error if they use false and there are directories that have existing data
```
TASK [ibm.mas_devops.suite_app_backup_restore : Detect if there is any data in destination folders] ***
failed: [localhost] (item={'src_folder': 'pv/manage-doclinks/DOCLINKS', 'dest_folder': '/DOCLINKS'}) => {"ansible_loop_var": "item", "changed": true, "cmd": "oc exec fvt28830-masdev-manage-maxinst-557b754965-f49lm -c manage-maxinst-maxinst -n mas-fvt28830-manage -- bash -c '[ \"$(ls -A /DOCLINKS)\" ] && { …
```
> [patch] add option to overwrite on restore

- ibm/mas_devops/roles/suite_app_config/tasks/main.yml
What Changed?
Added retries (15 times) with a delay (20s per retry) to ensure that k8s_info fetches fresh application status.
Previously, the readiness check ran only once, leading to random failures when the application was slow to start.
Now, the playbook waits properly before failing, reducing unnecessary test failures.
Why Was This Changed?
The test was failing intermittently because the application wasn’t always Ready immediately.
Without retries, the playbook failed too soon if the application took extra time to start.
This fix ensures the readiness check waits properly while still failing if the app is truly not Ready
> [patch] Adding retries for application status on application ws config

- ibm/mas_devops/roles/suite_upgrade/tasks/main.yml
When running the oneclick_upgrade playbook and explicitly specifying the [mas_channel](https://github.com/ibm-mas/ansible-devops/tree/master/ibm/mas_devops/roles/suite_upgrade#mas_channel) the upgrade role will fail. This happens because information from the current ibm-mas subscription is always required now.
As part of addressing label selectors with:
- https://github.com/ibm-mas/ansible-devops/pull/1586
- https://github.com/ibm-mas/ansible-devops/pull/1589
The current ibm-mas subscription is always required. For example here:
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_upgrade/tasks/upgrade.yml#L8
The subscription needs to be looked up even if the new mas_channel to upgrade two is explicitly provided.
> [patch] always lookup current ibm-mas subscription on upgrade

- ibm/mas_devops/roles/mongodb/tasks/providers/community/backup-restore/backup-database.yml
Within the Monitor database in MongoDB `mas_{{ instanceId }}_monitor` is a single collection named `sessions`. Documents in the `sessions` collection are for temporary storage of Monitor UI session data. There is no need to back them up as any Monitor UI session can be re-established.
> [patch] mongodb backup of monitor database is not required

- ibm/mas_devops/roles/nvidia_gpu/tasks/main.yml
- ibm/mas_devops/roles/nvidia_gpu/tasks/nfd_setup.yml
- ibm/mas_devops/roles/nvidia_gpu/templates/nfd-instance.yml.j2
NFD supports different images based on the ocp version. When ocp is version 4.17 and above, the image is expected to be http://registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9@sha256:45192fef5a1250ee573975ced1e897662116d5a30a1f8f4baa4497f64933fba3 and when it is below 4.17, the image should be registry.redhat.io/openshift4/ose-node-feature-discovery@sha256:cc09665d75447c53a86a5acb5926f9b9fb59294533e04bfa432001d2b41efebc
Related to jira issue: [MASCORE-6014](https://jsw.ibm.com/browse/MASCORE-6014)
> [patch] Add support for nfd image for OCP 4.17

- ibm/mas_devops/roles/cp4d/tasks/prereqs/install-cpfs.yml
- ibm/mas_devops/roles/suite_app_upgrade/tasks/upgrade.yml
Retry the patching of CommonService is it fails, fixing https://jsw.ibm.com/browse/MASCORE-6004
**Testing** 
I re-ran the modified role on an FVT cluster to check that the ansible task was configured correctly.
> [patch] Retry CommonService Patch if it faIls

- ibm/mas_devops/roles/kafka/README.md
The kafka version defaults were updated https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/kafka/defaults/main.yaml#L7 but not the docs. Updating the docs
> [doc] Fix Kafka version in role README.md

- ibm/mas_devops/roles/nvidia_gpu/tasks/main.yml
Fix for issue #1651 
gpu_driver_version is technically defined as Null so Ansible role attempt to create Cluster Policy with custom driver
```
oc get clusterpolicy gpu-cluster-policy -o yaml|yq .spec.driver|egrep "version|repository"
repository: nvcr.io/nvidia
version: ""
```
This empty version will cause the Daemonset to have incorrect image:
`Failed to apply default image tag "nvcr.io/nvidia/driver:-rhcos4.16": couldn't parse image name "nvcr.io/nvidia/driver:-rhcos4.16": invalid reference format`
Workaround in the issue should work but for the intended purposes of this role and to use the "latest" driver available, added small fix in PR to validate if gpu_driver_version is not empty
Tested on my local configuration as I was attempting to install MVI:
```
TASK [ibm.mas_devops.nvidia_gpu …
```
> [patch] Fix ClusterPolicy creation for nvidia_gpu role

- ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
- ibm/mas_devops/roles/ocp_efs/tasks/efs-setup.yml
This Fix is a pre-requisite for  https://jsw.ibm.com/browse/MASCORE-5250 and https://jsw.ibm.com/browse/MASCORE-5245
The current task at ibm/mas_devops/roles/ocp_efs/tasks/efs-setup.yml will filter security group based on the tag "worker", which will fail for OCP version 4.17
```
- name: "efs-setup : Get Security Group of the EC2 Instance"
shell: aws ec2 describe-security-groups --filters Name=vpc-id,Values={{ vpcid }} Name=tag:Name,Values='*worker*' --query "SecurityGroups[*].{ID:GroupId}[0]"
register: security_group
``` 
We need to add a condition on above task so that for version below ocp 4.17 above shell script can be continued and for version 4.17.0 & above use another condition for filtering as below:
```
- name: "efs-setup : Get Security Group of the EC2 Instance"
shell: >
{% if …
```
> [patch] Fix efs-setup in ocp_efs role to get securitygroup for cluster 4.17 

- ibm/mas_devops/plugins/modules/cis_dns_entries.py
According to [CIS API Docs](https://cloud.ibm.com/apidocs/cis#create-dns-record-e2ec84) the `dns_records` APIs do not support `PATCH`. To check I tested this myself against both the `/dns_record` and `/dns_record/{id}` APIs:
```
HTTP 405 {"trace": "xxx", "errors": [{"code": null, "message": "405 Method Not Allowed"}]}
```
As far as I can tell, all this PATCH call is doing is increasing our chances of hitting the CIS API's aggressive rate limits, especially as it is issued around 54 times (once for each entry in the [dnsentries.yml.js template](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_dns/templates/dnsentries.yml.j2)) every time the suite_dns role is run.
> [patch] Remove unnecessary HTTP PATCH call from suite_dns role

- ibm/mas_devops/roles/ocp_provision/tasks/main.yml
Referring story: [https://jsw.ibm.com/browse/MASCORE-5249](url)
Raising PR to update rotate_ocp_version and add 4.17. Currently, 4.16 runs on Monday, Thursday, and Sunday—I've modified it so that Monday and Sunday now run 4.17 instead.
> Update rotate_ocp_version and add 4.17 as part of OCP version testing

- .github/pull_request_template.md
Add a basic pull request template derived from the one shared in the IBM-internal Playbook.
* PRs are being delivered with little consistency. A quick look at the PR history will show PRs with an entirely empty description, or at least no standardization on how they are filled in.
* I have deliberately modified the IBM-internal template shared in the playbook to reference issue (work item) **ID numbers** rather than providing links to issues; such links will only work within the IBM network and this is a public GitHub repository.
* I have removed the Backporting section as it does not appear relevant to the repository.
> [patch] Add PR template

- ibm/mas_devops/roles/cp4d/tasks/prereqs/install-cpfs.yml
Retry the patching of CommonService if it fails, fixing https://jsw.ibm.com/browse/MASCORE-6337
this is a modification of the fix made here https://github.com/ibm-mas/ansible-devops/pull/1687 for https://jsw.ibm.com/browse/MASCORE-6004
**Testing** 
I ran the original ansible devops role against personal FVT cluster and saw that the retry confuration wasn't causing retries. We need to specify an until clause (despite what is said here https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html#retrying-a-task-until-a-condition-is-met
`If until is not specified, the task will retry until the task succeeds but at most retries times`)
I added the until clause and reran the task, forcing the error condition by scaling down the ibm-common-service-operator to 0 …
> [patch] Retry CommonService Patch if it faIls 

- ibm/mas_devops/roles/arcgis/tasks/main.yml
- ibm/mas_devops/roles/arcgis/templates/ingress-cluster-rbac.yml.j2
- ibm/mas_devops/roles/arcgis/templates/ws-cluster-rbac.yml.j2
Ws operator and Ingress controller of ArcGis failing due to not enough rbac permissions.
After upgrading ArcGIS to version 11.4, a few cluster-level resources are required by the Workspace Operator. To enable this, certain ClusterRoles and ClusterRoleBindings need to be created for the ArcGIS components.
This changes were tested by successfully deploying the End to End ArcGis application on openshift cluster. Attaching the screenshots for successful deployment of application with its UI and Home page
<hr/>
> Arcgis 11.4 Release

- ibm/mas_devops/roles/aibroker_tenant/defaults/main.yml
- ibm/mas_devops/roles/aibroker_tenant/templates/aibroker/aibrokerworkspace.yml.j2
MASAIB-882
Set the tenant's AI Service entitlement info in the AI Broker Workspace CR. These new fields are required, except for the `type` which defaults to `standard`.
Deployed the CR with the new build of the AI Broker's workspace operator and observed that the tenant was configured correctly. No errors observed. Confirmed that entitlement info was picked up correctly by the operator.
<hr/>
> [major] AI Service entitlement in tenant CR

- ibm/mas_devops/roles/suite_dns/README.md
- ibm/mas_devops/roles/suite_dns/defaults/main.yaml
- ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_edge_certificate.yml
MASCORE-6647
When a CIS instance domain includes the MAS instance ID (i.e. the CIS is likely dedicated for use by a single MAS instance),  the default "universal" edge cert provided by CIS will include the MAS instance ID in its hostnames already.
This breaks the current logic in suite-dns as it is "tricked" into thinking the universal edge cert is the "dedicated" certificate provisioned by suite-dns in a previous run. 
The universal cert only covers routes down one subdomain level, but MAS routes use lower levels. This means that, when `override_edge_certs: false` is used, a dedicated edge cert will not be ordered for the MAS instance and TLS won't work correctly for many of its routes.
This PR establishes a tactical fix for this problem by also checking that the certificate type is …
> [patch] ensure default CIS cert is excluded when searching for existing edge certs

- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-ccs.yml
MASCORE-6233
Upgrading from CPD 5.0.0 to CPD 5.1.0 can cause a downgrade of elasticsearch from 2.18 to 2.17 which isn't supported. If we detect this problem we need to purge the elasticsearch cluster (delete statefulset and PVCs)
Watched an update and checked it went through the correct steps and ended up with a working CPD 5.1.0
> Automatically recover elasticsearch in 5.0.0 to 5.1.0 upgrade

- docs/playbooks/ocp.md
- ibm/mas_devops/playbooks/ocp_convert_to_disconnected.yml
- ibm/mas_devops/playbooks/ocp_fyre_provision.yml
- ibm/mas_devops/playbooks/ocp_roks_provision.yml
- ibm/mas_devops/roles/cp4d_service/tasks/wait/wait-ccs.yml
- ibm/mas_devops/roles/mirror_ocp/README.md
- ibm/mas_devops/roles/ocp_cluster_monitoring/README.md
- ibm/mas_devops/roles/ocp_provision/defaults/main.yml
Revert OCP 4.17 as default, set 4.16 back
Revert cpd51 changes
<hr/>
> [patch] revert ocp 417 and cpd 51 changes

- docs/playbooks/oneclick-manage.md
- ibm/mas_devops/playbooks/oneclick_add_assist.yml
- ibm/mas_devops/playbooks/oneclick_add_iot.yml
- ibm/mas_devops/playbooks/oneclick_add_manage.yml
- ibm/mas_devops/playbooks/oneclick_add_monitor.yml
- ibm/mas_devops/playbooks/oneclick_add_optimizer.yml
- ibm/mas_devops/playbooks/oneclick_add_visualinspection.yml
- ibm/mas_devops/roles/suite_app_config/README.md
Adding Manage Foundation support to the docs
The oneclick_add_manage playbook was executed with `IS_FULL_MANAGE=false` and `MAS_APPWS_COMPONENTS` unset and Manage Foundation was successfully installed instead of Full Manage.
> [patch] Adding Manage Foundation support to the docs

- ibm/mas_devops/roles/sls/tasks/install/sls-verify.yml
The api-licensing pod takes a long time to start, causing the SLS pod to fail.
In fvts390x using fyre cluster, the api-licensing pod takes a long time to start, causing the SLS pod to fail because the LicenseService exceeds its retry limit while waiting to become ready.
> [patch] Increase time for LicenseService to be in ready state

- ibm/mas_devops/roles/dro/tasks/install-dro/main.yml
While checking regression in amd64 for power catalog, UDS pod is failing in mas personal fvt pipelines because rhm-data-service is taking longer time to be in ready state.
> [patch] Increase retries for rhm-data-service readiness check in DRO

- ibm/mas_devops/roles/aibroker/defaults/main.yml
- ibm/mas_devops/roles/aibroker/templates/aibroker/aibrokerapp.yml.j2
- ibm/mas_devops/roles/aibroker_tenant/defaults/main.yml
MASAIB-862
* Put the word "TENANT" in the environment variables for tenant S3 configuration. This avoids clashes with the variables for configuring shared S3 configuration in the AI Broker.
* Add some comments to clarify the distinction between AI Broker-level and tenant-level S3 configuration.
<hr/>
> [patch] refactor AI Broker tenant var names

- ibm/mas_devops/roles/aibroker_tenant/defaults/main.yml
- ibm/mas_devops/roles/aibroker_tenant/tasks/main.yml
- ibm/mas_devops/roles/aibroker_tenant/tasks/namespace/install/main.yml
- ibm/mas_devops/roles/aibroker_tenant/tasks/namespace/main.yml
- ibm/mas_devops/roles/aibroker_tenant/tasks/namespace/remove/main.yml
- ibm/mas_devops/roles/aibroker_tenant/tasks/tenant/install/main.yml
Create the tenant namespace as the first task so that it's available for other tasks that need to copy secrets there.
Deleted the tenant namespace and ran a tenant installation from scratch.
<hr/>
> [patch] fix namespace creation

- ibm/mas_devops/roles/suite_db2_setup_for_facilities/templates/db2/scripts/db2configdb.sh.j2
This db2configdb.sh.j2 expects to be db2inst1. this was wrongly changed.
> [patch] revert changes in mref db2configdb.sh.j2

- ibm/mas_devops/roles/suite_db2_setup_for_facilities/README.md
- ibm/mas_devops/roles/suite_db2_setup_for_facilities/defaults/main.yml
the default DB user should not be admin user,  changing default to `tridata`.
> [patch] changing default MREF db user to tridata

- ibm/mas_devops/roles/aibroker/templates/aibroker/aibrokerapp.yml.j2
https://jsw.ibm.com/browse/MASAIB-768
Ensure the AI Broker operator has the label `app.kubernetes.io/instance`. This uniquely identifies the operator instance if for example multiple instances are running in the cluster. This is intended to be a replacement for the `mas.ibm.com/instanceId` label as the AI Service is designed to be independent from MAS.
N/A
<hr/>
> [patch] add new instance label

- ibm/mas_devops/roles/suite_certs/templates/dnsentries.yml.j2
pmscheduleragent in renamed to maintenanceagent in MREF.
> [patch] rename dns entry pmscheduleragent to maintenanceagent for facilties

- ibm/mas_devops/roles/suite_app_config/vars/facilities.yml
MREF workspace takes 3-5 hours depending upon the size of the app, cluster and performace of db. So increasing the max wait time to 5 hours to allow FacilitiesWorkspace to get activated.
<hr/>
> [patch] increasing the default wait and retry for MREF workspace to get ready

- ibm/mas_devops/roles/aibroker_tenant/templates/aibroker/aibrokerworkspace.yml.j2
MASAIB-768
Ensure the AI Broker operator has the label `app.kubernetes.io/instance`. This uniquely identifies the operator instance if for example multiple instances are running in the cluster. This is intended to be a replacement for the `mas.ibm.com/instanceId` label as the AI Service is designed to be independent from MAS.
N/A
<hr/>
> [patch] add instance label to AI workspace CR

- ibm/mas_devops/roles/odh/defaults/main.yml
Delete unused tenant name variable in ODH role:
Playbook does not throw any errors. This variable is unused.
<hr/>
> [patch] delete unused variable

- ibm/mas_devops/playbooks/oneclick_add_assist.yml
- ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/assist.yml
Removal of all CPD-related components and dependencies.
[ASSIST-517](https://jsw.ibm.com/browse/ASSIST-517) 
The Salesforce customer Case ID: TS019208936 
As per the customer's request to proceed with the installation of Assist without CPD, we have updated the Ansible playbook accordingly. The following changes were made:
Removed all CPD-related components and dependencies.
Removed Watson Discovery bindings.
Validated the playbook to ensure Assist installs correctly without CPD.
The updated playbook was tested successfully, and Assist is now installable as requested.
Successfully installed Assist after removing all CPD and Watson-related bindings and variables. The deployment completed without issues, and the application is functioning as expected.
<hr/>
* Ensure you have understood the …
> [major] Removal of CPD related dependencies from Assist playbook

- ibm/mas_devops/roles/ocp_provision/tasks/providers/rosa/provision_rosa.yml
📡**Issue#:** MASR-3736
✅**Description:**✅
This merge request contains the alteration in role name **OCP_PROVISION (ROSA)** to create role for ROSA Cluster being utilised by FVTSAAS and FVTSAAS-TRANSITION.
This edition will seprate the IAM roles utilised for scheduling and operating both FVTSAAS and FVTSAAS-TRANSITION environment. Also in case, in future if we upgradge the version (Major/Minor), It will create the AWS IAM role as per the OCP_VERSION we define in environment pipeline. 
⚒️**Test Result:**🛠️
The changes of this role has been tested on FVTSAAS_TRANSITION on the date 24th MAY, 3:55 PM UTC, Saturday. The Created role can be seen and reviewed in respective AWS Account, region (for EC2 inspection as both environments are deployed in diff region).
**Owner of issue#:** @IanBoden …
> [patch] Changes for OCP 4.18 AWS IAM ROLE Creation process

- ibm/mas_devops/roles/aibroker/defaults/main.yml
- ibm/mas_devops/roles/aibroker/templates/aibroker/aibrokerapp.yml.j2
- ibm/mas_devops/roles/aibroker_tenant/defaults/main.yml
- ibm/mas_devops/roles/aibroker_tenant/templates/aibroker/aibrokerworkspace.yml.j2
MASAIB-768
Add the ability to set the AI Broker operator log level (applies to both app and workspace operators). See https://sdk.operatorframework.io/docs/building-operators/ansible/reference/advanced_options/#ansible-verbosity
Set level to 7 and saw debug logs in the operator output.
<hr/>
> [minor] ability to set operator log level

- ibm/mas_devops/roles/suite_db2_setup_for_facilities/tasks/db2/preparedb.yml
- ibm/mas_devops/roles/suite_db2_setup_for_facilities/tasks/main.yml
It was reported a bug in the fvt pipelines regarding oc commands that were not retrying. Therefore, it was added `retries` and `delay` in all `oc exec` tasks.
- Removal of the schema check, since the db2 role was integrated with the configuration steps.
- Adding retries in the `oc exec` functions.
<hr/>
> [patch] add retries to MREF db2 oc commands

- ibm/mas_devops/roles/ocp_provision/tasks/main.yml
- ibm/mas_devops/roles/ocp_provision/tasks/providers/fyre/provision_fyre.yml
- Improves error handling when provisioning FYRE clusters with an invalid/expired API key
- Adds OCP 4.18 into the `rotate` policy for `ocp_provision` role
> [patch] Add OCP 4.18 into rotation

- ibm/mas_devops/roles/suite_db2_setup_for_facilities/tasks/apply-db2-config-settings.yml
- ibm/mas_devops/roles/suite_db2_setup_for_facilities/tasks/apply-db2-config-version.yml
- ibm/mas_devops/roles/suite_db2_setup_for_facilities/tasks/db2/preparedb.yml
- ibm/mas_devops/roles/suite_db2_setup_for_facilities/tasks/main.yml
MASCORE-7202
FVT tests are failing during `suite-db2-setup-for-facilities`. One of the possible reasons is not enough wait time, therefore those were increased to avoid the error.
> [patch] increase retries for db2 facilities

- ibm/mas_devops/roles/suite_db2_setup_for_facilities/tasks/apply-db2-config-version.yml
- ibm/mas_devops/roles/suite_db2_setup_for_facilities/templates/db2_enforce_config.yaml.j2
MASCORE-7585
run the following scenario:
- Install and configure facilities db2 instance using the ansible role suite-db2-setup-facilities: Success
- Remove the db2 instance by deleting the corresponding Db2uCluster CR. 
- verified that the <db-instance-name>-enforce-mref-config is still present in the system
- Run again the ansible role  suite-db2-setup-facilities. It fails: 
```
TASK [ibm.mas_devops.suite_db2_setup_for_facilities : Check DB2 cfg is take effect] *************************************************************************************************************************************************
FAILED - RETRYING: [localhost]: Check DB2 cfg is take effect (20 retries left).
FAILED - RETRYING: [localhost]: Check DB2 cfg is take effect (19 retries left).
FAILED - RETRYING: …
```
> [patch] Inject Db2uCluster CR as owner in the enforce settings configmap

- ibm/mas_devops/roles/aibroker/tasks/config_db2/main.yml
- ibm/mas_devops/roles/aibroker/tasks/config_sls/main.yml
- ibm/mas_devops/roles/aibroker_tenant/tasks/config_sls/main.yml
MASAIB-761
Reformat ca cert for db2 and sls when we pass certs as env vars.
<hr/>
> [patch] reformat ca cert while passed from env vars for AIBroker role

- docs/playbooks/oneclick-manage.md
- ibm/mas_devops/playbooks/oneclick_add_manage.yml
- ibm/mas_devops/roles/suite_app_config/README.md
- ibm/mas_devops/roles/suite_app_config/defaults/main.yml
- ibm/mas_devops/roles/suite_app_config/tasks/manage/pre-config/main.yml
- ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/manage.yml
- ibm/mas_devops/roles/suite_app_config/vars/manage.yml
MASCORE-7612
We are removing the need of setting an specific IS_FULL_MANAGE variable when installing Manage Foundation.
This change will ensure that by default foundation is always installed if no components is set for Manage installation.
To keep compatibility with current behavior we are also change Manage oneclick playbook to always install Manage base e the env var is not set. The way to install foundation explicitly using the playbook is by setting the env var as:
export MAS_APPWS_COMPONENTS=""
I ran all sort of possible tests for this playbook including:
* Install foundation only with
export MAS_APPWS_COMPONENTS=""
* installing Manage full without set the env var;
* Installing Manage full explicitly setting the MAS_APPWS_COMPONENTS env var;
<hr/>
* Ensure you have understood the PR …
> [major] Avoid usage of an additional variable to install Manage foundation

- ibm/mas_devops/roles/ocp_provision/templates/fyre/product_group.json.j2
https://jsw.ibm.com/browse/MASCORE-5890
We're wasting 12 cpu with every cluster due to a default over-speced master node.
N/A
<hr/>
> [patch] Set Fyre master nodes to 4cpu 8gb mem

- ibm/mas_devops/roles/suite_app_config/templates/manage/custom-archive-credentials.yml.j2
- ibm/mas_devops/roles/suite_app_config/vars/manage.yml
Downloading customization.zip file from Azure DevOps Git repository using a personal access token is possible.
GET https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/items?path={path}
But `wget` requires additional options in secret `"{{ mas_workspace_id }}-{{ mas_app_id }}-cl0--cac--sn"`
```
user={organization}
password={personal access token}
auth_no_challenge=on
secure-protocol=TLSv1_3
```
Otherwise `wget` fails with the following error.
```
wget $configfile https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/items?path=/Cust.zip -O customization.zip
--2024-12-06 12:42:04--  https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/items?path=/Cust.zip
Resolving dev.azure.com …
```
> [patch] Add options to custom-archive-credentials secret

- ibm/mas_devops/roles/kafka/templates/redhat/dashboards-v5/kafka-exporter.yml.j2
- ibm/mas_devops/roles/kafka/templates/redhat/dashboards-v5/kafka-zookeeper.yml.j2
- ibm/mas_devops/roles/kafka/templates/redhat/dashboards-v5/kafka.yml.j2
- ibm/mas_devops/roles/mongodb/templates/community/dashboards/mongodb-overview-v5.yml.j2
```
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
```
This CRD [does not support spec.name](https://grafana.github.io/grafana-operator/docs/api/#grafanadashboardspec). Observed when Kafka installation failed.
I did not modify the associated v4 dashboards, as I assume spec.name was supported at some point in the past.
> [patch] Remove spec.name from Grafana v5 dashboards

- .github/CODEOWNERS
- ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
https://github.com/ibm-mas/ansible-devops/issues/1826
A previous update introduced a regression in image mirroring support on OCP 4.16, by setting the minimum release for the `odf-dependencies` package to 4.16 instead of 4.17
No testing. Attacking low cost defect fixes that can be handled with a peer review alone this morning.
<hr/>
> [patch] Fix min release for odf-dependencies

- docs/playbooks/oneclick-aibroker.md
- ibm/mas_devops/roles/aibroker_tenant/defaults/main.yml
- ibm/mas_devops/roles/aibroker_tenant/templates/watsonx/secret.yml.j2
https://jsw.ibm.com/browse/MASAIB-1131
add 3 new variables to secret:
wx_instance_id
wx_version
wx_username
when specify variable WX_FULL as true and these 3 env defined
WX_FULL is true if customer have on prem watsonx installed.
when WX_FULL is false
when WX_FULL is true
<hr/>
> [patch] Add extra fields in watsonx secret in default aibroker tenant namespace 

- ibm/mas_devops/roles/ocp_provision/tasks/main.yml
https://ibm-watson-iot.slack.com/archives/C031Q7W21FZ/p1753430888295429
The provision failed with error "Unable to apply 4.14.52: the cluster operator image-registry is not available"
https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_changelog_414
Updated the rotation list for ocp 
<hr/>
> [patch] Remove 4.14 from ocp rotation

- ibm/mas_devops/roles/aiservice_kmodels/templates/istio/istio.yml.j2
[MASAIB-1108](https://jsw.ibm.com/browse/MASAIB-1108)
Enable mTLS verification for DestinationRule used by opendatahub.
Successfully tested deployment with this change.
Must gather logs: [must-gather-20250728-091618.tgz](https://github.com/user-attachments/files/21468614/must-gather-20250728-091618.tgz)
<hr/>
> [patch] Enable mTLS verification for DestinationRule used by ODH

- ibm/mas_devops/roles/ocp_provision/tasks/providers/roks/provision_roks.yml
#1859 
Add a sanitize task to add the sufix `_openshift` when not added for ROKS.
- OCP_VERSION=default
- OCP_VERSION=rotate
- OCP_VERSION=4.18
- OCP_VERSION=4.18_openshift
<hr/>
> [patch] sanitize ocp_version input for roks

- ibm/mas_devops/roles/dro/tasks/install-dro/main.yml
#1752 
Retrieve old PVC deployments and added a conditional check around the task that deploys DRO PVC. If it already exists, it's going to skip.
Step:
- Run DRO role in already installed instance and verified if the task was going to be skipped.
- Uninstalled DRO by setting `DRO_ACTION=uninstall` and running the role.
- Installed the DRO again to verify if the default functionality was not affected.
- Uninstalled and installed with `DRO_STORAGE_CLASS=ocs-storgacluster-ceph-rbd`
- Unset `DRO_STORAGE_CLASS` and run the role again.
<hr/>
> [patch] add check while applying dro pvc

- ibm/mas_devops/roles/ocp_deprovision/tasks/providers/roks.yml
No specific issue ID. This PR addresses a problem where Object Storage (COS) buckets were not being deleted during OpenShift cluster removal on IBM Cloud Classic infrastructure, resulting in continued storage costs.
This change corrects the usage of the IBM Cloud CLI flags in the cluster deletion command. Previously, the command used: `--force-delete-storage`, which is **not a valid flag**, causing persistent storage resources (like COS buckets) to remain undeleted. The corrected command is: `--force --delete-storage -f`, which ensures the cluster and all associated storage, including Object Storage buckets, are deleted properly. This change was necessary due to observed increases in IBM Cloud storage costs (~$5–6k/month) caused by orphaned storage resources that were not removed during …
> Fix cluster removal command to clean up storage properly in roks.yml

- docs/playbooks/aiservice.md
- ibm/mas_devops/roles/aiservice_kmodels/defaults/main.yml
This PR is for give warning to customer to not use minio role included in this automation. Instead customer can use own minio secure instance or AWS S3. 
Also added variable to specify custom version of kmodels components
<hr/>
> [patch] Add missing storage variables to kmodels role

- ibm/mas_devops/playbooks/aiservice.yml
- ibm/mas_devops/roles/aiservice_tenant/templates/aiservice/aiserviceworkspace.yml.j2
remove condition from aiserviceworkspace regarding of encoding of ca cert
<hr/>
> [patch] Always B64 encode AI service's JDBC cert

- ibm/mas_devops/roles/ocp_deprovision/tasks/providers/roks.yml
ROKS have changed their cli flags, we now need to set `--delete-openshift-registry-cos-bucket` otherwise some storage is left behind when a cluster is deprovisioned.
> [patch] Add --delete-openshift-registry-cos-bucket to roks deprovision

- ibm/mas_devops/roles/aiservice_odh/templates/odh/data-science-cluster.yml.j2
ODH role was failing while creating DSC CR. Root cause is while rendering template, parent key was changed for `name: knative-serving`. 
Fix for ODH role,
<hr/>
> [patch] Bug fix for DSC template in odh role

- ibm/mas_devops/roles/suite_upgrade/tasks/check_app_compatibility.yml
- ibm/mas_devops/roles/suite_upgrade/tasks/main.yml
- #1816
We primarily use the auto-detect upgrade logic, but there is a bug in the logic when a specific upgrade target is set.
Also removes compatibility checks for applications that are no longer supported (HP Utilities & Safety)
No testing done.  This change will be verified in the next run of the day2 test suites.
<hr/>
> [patch] Fix support for explicitly defined upgrade target

- ibm/mas_devops/plugins/action/update_ibm_entitlement.py
- ibm/mas_devops/roles/aiservice/tasks/aiservice/main.yml
- ibm/mas_devops/roles/aiservice_tenant/tasks/namespace/install/main.yml
- ibm/mas_devops/roles/db2/tasks/install/main.yml
- ibm/mas_devops/roles/db2/templates/db2u_namespace.yaml
- ibm/mas_devops/roles/dro/tasks/install-dro/main.yml
- ibm/mas_devops/roles/sls/tasks/install/main.yml
- ibm/mas_devops/roles/suite_app_install/tasks/main.yml
- ibm/mas_devops/roles/suite_install/tasks/main.yml
MASCORE-9195
Add `ibm.com/kyverno: audit` in all namespaces to enable Kyverno Policy audit
<hr/>
> [minor] Add ibm.com/kyverno namespace label support

- ibm/mas_devops/roles/suite_app_config/vars/customspecs/manage_components.yml.j2
MASR-3108 - Create Maximo Vegetation Management Installable component
This change adds `vegm` add-on functionality. This has been tested with `cli version 15.3.2-pre.vegm`
This has been tested and here are the screenshots after testing
<hr/>
> [minor] Add Vegetation Management (Vegm) add-on functionality for Manage

- ibm/mas_devops/roles/aiservice_tenant/tasks/namespace/install/main.yml
Unsupported parameters for (kubernetes.core.k8s) module: labels.
Added definition and moved labels under metadata.
Ran aiservice_tenant role directly on cluster.
<hr/>
> [patch] Fix unsupported parameter for aiservice_tenant namespace

- docs/playbooks/backup-restore.md
- ibm/mas_devops/common_tasks/backup_restore/check_common_vars.yml
- ibm/mas_devops/common_tasks/backup_restore/check_restore_vars.yml
- ibm/mas_devops/playbooks/br_core.yml
- ibm/mas_devops/playbooks/br_db2.yml
- ibm/mas_devops/playbooks/br_health.yml
- ibm/mas_devops/playbooks/br_iot.yml
- ibm/mas_devops/playbooks/br_manage.yml
- ibm/mas_devops/playbooks/br_monitor.yml
- ibm/mas_devops/playbooks/br_optimizer.yml
MASCORE-9435
- For MASCORE-9435, br_manage playbook wasn't having a default db2 namespace and was failing in a common check, this is not consistent with br_db2 playbook and was causing confusion.
- General docs and logs improvement
Tested playbooks locally.
<hr/>
> [patch] keep default db2_namespace consistent in b&r playbook and docs improvement

- ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
https://github.com/ibm-mas/cli/issues/1783
Mirror on OCP 4.17 doesn't work due to the odf-dependencies package not found in registry.redhat.io/redhat/redhat-operator-index:v4.17. It is present in OCP 4.18.
No error mirror-xx-ocp4.17.log when `mas mirror-redhat-images` for ocp 4.17 was ran in test.
<hr/>
> [patch] Fix again min release for odf-dependencies
